In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os

In [2]:
nr_lama = './OLAH_DATA_NRQUALITY/'
nr_baru = './OLAH_DATA_NRQUALITY_DATABARU/'

vpmi_lama = './OLAH_DATA_VPMI/'
vpmi_baru = './OLAH_DATA_VPMI_DATABARU/'

In [3]:
filename_nr_lama = sorted(os.listdir(nr_lama))
filename_nr_baru = sorted(os.listdir(nr_baru))

filename_vpmi_lama = sorted(os.listdir(vpmi_lama))
filename_vpmi_baru = sorted(os.listdir(vpmi_baru))

In [4]:
if '.DS_Store' in filename_nr_lama:
    os.remove(nr_lama + '.DS_Store')
elif '.DS_Store' in filename_nr_baru:
    os.remove(nr_baru + '.DS_Store')
else:
    pass
    
if '.DS_Store' in filename_vpmi_lama:
    os.remove(vpmi_lama + '.DS_Store')
elif '.DS_Store' in filename_vpmi_baru:
    print(True)
    os.remove(vpmi_baru + '.DS_Store')
else:
    pass

In [5]:
display(filename_nr_lama)
display(filename_nr_baru)

display(filename_vpmi_lama)
display(filename_vpmi_baru)

['RAW_ALL_DATA.xlsx',
 'RAW_PROCESSED_DATA_PNG.xlsx',
 'RGB_SKIP_RAW_CLEAN.xlsx',
 'RGB_SKIP_RAW_NOISY.xlsx',
 'RGB_WITH_RAW_CLEAN.xlsx',
 'RGB_WITH_RAW_NOISY.xlsx']

['RAW_ALL_DATA.xlsx',
 'RAW_PROCESSED_DATA_PNG.xlsx',
 'RGB_SKIP_RAW_CLEAN.xlsx',
 'RGB_SKIP_RAW_NOISY.xlsx',
 'RGB_WITH_RAW_CLEAN.xlsx',
 'RGB_WITH_RAW_NOISY.xlsx']

['RAW_ALL_DATA_VPMI.xlsx',
 'RAW_PROCESSED_DATA_VPMI.xlsx',
 'RGB_SKIP_RAW_CLEAN.xlsx',
 'RGB_SKIP_RAW_CLEAN_global.xlsx',
 'RGB_SKIP_RAW_NOISY.xlsx',
 'RGB_SKIP_RAW_NOISY_global.xlsx',
 'RGB_WITH_RAW_CLEAN.xlsx',
 'RGB_WITH_RAW_CLEAN_global.xlsx',
 'RGB_WITH_RAW_NOISY.xlsx',
 'RGB_WITH_RAW_NOISY_global.xlsx']

['RAW_ALL_DATA_VPMI.xlsx',
 'RAW_PROCESSED_DATA_VPMI.xlsx',
 'RGB_SKIP_RAW_CLEAN.xlsx',
 'RGB_SKIP_RAW_CLEAN_global.xlsx',
 'RGB_SKIP_RAW_NOISY.xlsx',
 'RGB_SKIP_RAW_NOISY_global.xlsx',
 'RGB_WITH_RAW_CLEAN.xlsx',
 'RGB_WITH_RAW_CLEAN_global.xlsx',
 'RGB_WITH_RAW_NOISY.xlsx',
 'RGB_WITH_RAW_NOISY_global.xlsx']

# NR QUALITY

In [6]:
def desc_stat(path,filename):
    alldata_excel = path + filename
    nr_data = pd.read_excel(alldata_excel)
    nr_data.index = nr_data['Row']
    nr_data = nr_data.drop('Row',axis = 1)
    return nr_data,nr_data.describe()

In [7]:
print('NR QUALITY DARI DATA LAMA\n')

for i in range(len(filename_nr_lama)):
    file = filename_nr_lama[i]
    print(file)
    df,df_stat = desc_stat(nr_lama,file)
    display(df)
    display(df_stat)
    print('-'*10)

NR QUALITY DARI DATA LAMA

RAW_ALL_DATA.xlsx

,NIQE_CLEAN,NIQE_NOISY,BRISQUE_CLEAN,BRISQUE_NOISY,PIQE_CLEAN,PIQE_NOISY
Row,,,,,,
Image_0,4.807263,10.183589,33.252180,37.164646,30.521673,49.822388
Image_1,4.477482,8.542111,34.471445,34.657420,27.247808,40.355344
Image_2,4.469463,9.377596,34.035982,38.780471,23.860546,45.907702
Image_3,4.411344,10.326775,21.206596,37.676930,23.261976,52.914290
Image_4,3.821025,10.577089,28.038603,38.008889,17.514076,54.630536
...,...,...,...,...,...,...
Image_65,4.351089,9.563215,26.195867,35.764104,26.585740,50.845708
Image_66,3.628218,8.605296,25.942057,35.220043,24.785456,48.391605
Image_67,3.624895,8.738721,20.646011,33.817543,19.595428,49.461242
Image_68,4.944341,9.235018,18.617964,35.286343,24.750198,47.348224
Image_69,4.283207,8.176219,25.500900,38.396543,27.155986,45.403734

,NIQE_CLEAN,NIQE_NOISY,BRISQUE_CLEAN,BRISQUE_NOISY,PIQE_CLEAN,PIQE_NOISY
count,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000
mean,4.112647,9.027317,29.247621,35.317592,25.493854,47.393912
std,0.622067,0.798769,7.917512,2.109429,6.880083,4.628372
min,2.990752,7.392652,14.622657,29.147250,11.400383,35.630424
25%,3.627774,8.485093,22.995044,34.449863,19.736548,44.695277
50%,4.077765,8.903183,30.044151,35.561154,25.403034,48.131898
75%,4.479180,9.546208,34.421215,36.782540,30.908638,50.755688
max,5.717184,10.824657,50.484033,39.345500,41.596690,54.630536

----------
RAW_PROCESSED_DATA_PNG.xlsx

,RAW_NIQE_CLEAN,RAW_NIQE_NOISY,RAW_BRISQUE_CLEAN,RAW_BRISQUE_NOISY,RAW_PIQE_CLEAN,RAW_PIQE_NOISY
Row,,,,,,
Image_0,6.622746,6.430719,47.048263,26.047302,74.939955,18.595126
Image_1,5.057855,8.608181,43.456440,29.260710,45.196831,16.446205
Image_2,6.876683,6.040695,43.139369,21.556374,66.597541,28.369714
Image_3,5.267125,9.520779,39.266932,26.966709,62.125728,13.564783
Image_4,6.223976,7.350291,42.019543,33.076291,42.739427,10.174149
...,...,...,...,...,...,...
Image_65,4.649406,7.692221,40.173269,21.049275,49.693494,18.709355
Image_66,3.496973,5.446120,39.888112,18.653895,37.652565,18.374747
Image_67,4.955253,8.693733,43.863835,34.050885,46.665713,9.091535
Image_68,6.048487,7.660215,45.186173,21.636373,72.846345,19.729913
Image_69,6.202757,5.425888,43.915646,20.652452,47.906230,18.457097

,RAW_NIQE_CLEAN,RAW_NIQE_NOISY,RAW_BRISQUE_CLEAN,RAW_BRISQUE_NOISY,RAW_PIQE_CLEAN,RAW_PIQE_NOISY
count,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000
mean,5.309007,7.306195,43.115718,26.531959,56.324237,15.689196
std,0.841031,1.463775,3.970028,5.250806,13.037650,5.004587
min,3.496973,4.860150,34.955500,13.994154,25.370387,5.400031
25%,4.807843,6.356305,40.193589,23.030908,46.805930,12.202274
50%,5.286747,6.992178,42.168724,25.960025,57.211155,15.535466
75%,5.813056,8.140337,46.588182,30.366045,68.067315,18.899844
max,7.908129,10.998343,51.743347,37.983927,79.272989,28.369714

----------
RGB_SKIP_RAW_CLEAN.xlsx

,niqe_ac,brisque_ac,piqe_ac,niqe_d,brisque_d,piqe_d,niqe_gi,brisque_gi,piqe_gi,niqe_um,brisque_um,piqe_um
Row,,,,,,,,,,,,
Image_0,4.840084,47.463972,59.643102,7.336255,49.078960,75.108973,4.143808,43.973370,56.443803,3.338018,32.136195,50.613205
Image_1,3.251602,36.380308,36.306845,4.671589,44.329001,61.611635,3.290627,13.612486,29.813672,4.109434,21.839076,31.171420
Image_2,4.853178,46.468617,59.905796,6.760800,51.638568,60.186901,4.820130,46.866026,55.163800,3.245967,34.169468,52.973311
Image_3,3.991444,46.942467,62.453063,5.537198,52.290765,65.018166,3.785386,44.581837,59.794590,2.760656,33.303549,50.950336
Image_4,3.390350,46.766284,52.229352,5.862921,49.295758,71.683008,3.168228,48.114543,52.392253,2.534992,30.063176,30.528786
...,...,...,...,...,...,...,...,...,...,...,...,...
Image_65,5.148777,47.724548,66.926217,5.656385,52.988105,76.872371,5.700740,45.553478,71.598316,3.537106,39.657638,54.953425
Image_66,8.091238,50.193826,74.290965,5.265791,54.575529,77.367532,5.726187,48.777805,64.216942,4.756306,48.233298,69.138806
Image_67,3.928458,53.173808,57.295832,4.589130,51.811056,71.450382,4.247719,45.772940,54.135604,2.636299,36.595633,34.497979
Image_68,4.159642,42.359528,60.969022,5.942756,54.269120,76.249909,3.638600,40.561664,57.144584,2.930545,28.894197,46.565020
Image_69,5.561706,44.327519,50.067204,6.996436,47.840494,56.863609,5.362484,43.741120,48.821767,4.131185,38.401802,47.075813

,niqe_ac,brisque_ac,piqe_ac,niqe_d,brisque_d,piqe_d,niqe_gi,brisque_gi,piqe_gi,niqe_um,brisque_um,piqe_um
count,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000
mean,4.406321,47.775119,57.121498,5.591796,51.071409,71.545296,4.547309,43.288899,56.292275,3.282581,35.549724,42.585077
std,1.264319,3.039588,11.629989,0.871312,3.272528,8.282025,1.280550,8.171792,13.794654,0.950465,7.345676,13.420482
min,2.710052,36.380308,36.306845,4.129799,44.329001,54.013427,2.543124,13.612486,18.832095,2.202083,14.538229,14.174826
25%,3.755047,46.011741,51.193487,4.881523,48.669540,65.414128,3.455754,43.332293,46.848560,2.663707,31.981659,34.294375
50%,3.996302,47.730333,56.261774,5.484609,50.319760,72.595217,4.195763,45.355045,56.794194,3.015882,36.603395,43.632990
75%,4.561725,49.760101,63.274271,5.943444,53.138294,76.961971,5.488159,47.803257,65.184124,3.409328,40.246667,50.625290
max,8.978095,54.627366,100.000000,7.917031,58.299878,89.934747,7.847039,51.187307,89.035541,7.098462,48.233298,71.280661

----------
RGB_SKIP_RAW_NOISY.xlsx

,niqe_ac,brisque_ac,piqe_ac,niqe_d,brisque_d,piqe_d,niqe_gi,brisque_gi,piqe_gi,niqe_um,brisque_um,piqe_um
Row,,,,,,,,,,,,
Image_0,5.822212,34.007463,39.881039,5.103422,27.666198,32.162258,7.111030,36.372870,46.917663,9.259671,41.124957,57.883491
Image_1,3.280825,31.460789,18.089540,4.886453,20.672783,21.705049,12.141330,43.467079,60.136195,12.080634,43.458199,67.033653
Image_2,3.551102,8.210636,23.683940,3.152409,23.974556,22.502285,3.880695,14.110744,27.853779,5.619791,33.842767,39.014638
Image_3,3.777663,13.704977,33.625858,3.390052,23.052896,29.641640,4.731631,31.527135,39.587998,6.128286,38.115719,48.045408
Image_4,6.900965,35.813480,45.633346,5.256740,17.579461,30.443586,8.920934,42.646368,62.430148,8.836224,42.004301,60.861784
...,...,...,...,...,...,...,...,...,...,...,...,...
Image_65,3.336068,17.081217,19.982366,3.342343,26.861312,29.063895,3.350959,24.052735,11.566570,4.615738,31.374868,38.292550
Image_66,5.009703,50.370410,27.306739,2.916288,23.926941,28.322488,5.919872,35.070470,37.596393,3.789060,22.001190,59.252893
Image_67,3.160193,23.806281,15.324203,3.195074,24.811161,19.167541,3.480517,20.670330,16.963759,4.547704,18.112668,29.288885
Image_68,5.338256,34.572577,43.526193,3.649432,9.680064,28.145281,8.501535,43.924099,64.070405,7.468413,43.292293,60.175608
Image_69,3.465110,20.048523,25.363692,3.169019,19.410687,25.376512,3.941363,17.856613,30.259584,5.273486,32.896585,38.351445

,niqe_ac,brisque_ac,piqe_ac,niqe_d,brisque_d,piqe_d,niqe_gi,brisque_gi,piqe_gi,niqe_um,brisque_um,piqe_um
count,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000
mean,4.260899,24.950936,27.066352,3.748595,17.911622,25.279415,5.133907,34.189356,37.323051,6.125560,32.131508,42.308162
std,1.496349,10.383180,14.426372,0.710941,5.598084,3.541043,2.273079,10.917874,14.896710,1.703789,9.405526,14.976042
min,2.516957,8.210636,7.292149,2.663374,8.912361,17.999015,2.405789,11.114714,11.566570,3.260370,9.582114,8.261938
25%,3.294768,17.392683,16.450937,3.332441,12.468966,22.671119,3.183021,24.986771,25.209612,4.564712,25.949378,31.010787
50%,3.841144,25.638699,25.326814,3.544341,19.293355,25.588265,4.253781,37.954748,34.807545,6.096711,33.646253,42.769389
75%,4.940902,31.205867,35.435878,4.194276,22.805043,27.914731,6.872923,41.632802,50.351935,7.288528,40.025210,55.377270
max,10.853911,50.370410,94.760038,6.033765,27.666198,32.162258,12.141330,50.680847,67.340490,12.080634,46.482834,67.033653

----------
RGB_WITH_RAW_CLEAN.xlsx

,niqe_ac,brisque_ac,piqe_ac,niqe_d,brisque_d,piqe_d,niqe_gi,brisque_gi,piqe_gi,niqe_um,brisque_um,piqe_um
Row,,,,,,,,,,,,
Image_0,6.286621,48.935914,66.646432,9.255798,48.279772,78.233937,5.226400,46.735045,57.665303,5.354326,47.101872,58.777379
Image_1,3.760156,44.764999,46.290908,5.044149,46.320108,62.871188,3.003171,38.421137,33.296911,2.948323,28.259804,24.610872
Image_2,6.570682,48.158461,67.525541,8.705222,46.712509,71.360492,5.768296,39.904223,51.180450,4.996072,43.190876,58.011979
Image_3,5.551171,45.517364,69.500036,8.174228,48.600008,85.418011,4.466221,40.999834,63.865937,3.932537,33.235268,57.757032
Image_4,3.957826,42.748522,56.913074,8.563735,47.726899,89.968875,5.350511,26.732162,38.438241,4.773738,24.477914,40.930149
...,...,...,...,...,...,...,...,...,...,...,...,...
Image_65,6.082716,48.469046,72.282392,7.859401,47.823907,83.083603,5.120559,44.640211,68.502696,4.073633,38.187792,60.576197
Image_66,5.055958,48.317992,65.387425,7.459659,47.861503,85.446298,4.649482,46.089107,65.508193,3.251864,40.314613,53.323665
Image_67,3.884551,49.359488,55.860244,6.293526,49.607832,77.720360,2.919069,41.369569,44.461924,3.003474,29.029148,36.093578
Image_68,4.922813,45.973005,63.231748,7.643266,46.749850,78.327846,5.867351,34.139539,55.129606,5.031172,43.123179,55.912809
Image_69,6.446021,48.449071,64.947228,8.622586,48.989642,78.141838,5.391387,40.894627,42.273184,4.480041,45.603123,53.676231

,niqe_ac,brisque_ac,piqe_ac,niqe_d,brisque_d,piqe_d,niqe_gi,brisque_gi,piqe_gi,niqe_um,brisque_um,piqe_um
count,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000
mean,4.964634,46.844078,61.644436,7.435387,48.243186,76.657064,4.411384,41.067043,52.003799,4.010995,37.482559,48.206996
std,0.921549,2.835889,8.869987,1.157218,1.793394,10.835305,1.064093,5.789312,11.781478,0.915633,6.262123,11.818284
min,3.370496,39.059190,37.857237,5.009434,43.375112,50.000000,2.865574,24.173423,14.188449,2.563853,22.829765,15.064893
25%,4.233704,45.263651,57.139300,6.531215,47.280269,68.340172,3.492531,38.450519,45.019857,3.260188,32.995735,42.695323
50%,5.018749,47.316661,64.051881,7.486249,48.048794,77.115009,4.275478,42.189658,54.263319,3.805496,37.166208,51.950186
75%,5.599950,48.607890,68.005346,8.296231,48.693848,85.439226,5.137520,45.512262,59.406159,4.518327,41.736780,57.467568
max,6.868095,52.902736,77.568785,9.895509,56.486918,100.000000,6.878714,49.497685,70.113940,6.924435,50.477293,64.477999

----------
RGB_WITH_RAW_NOISY.xlsx

,niqe_ac,brisque_ac,piqe_ac,niqe_d,brisque_d,piqe_d,niqe_gi,brisque_gi,piqe_gi,niqe_um,brisque_um,piqe_um
Row,,,,,,,,,,,,
Image_0,3.276297,32.919242,28.657024,7.987265,45.868102,52.946769,7.196789,39.987506,38.188970,5.983592,32.284334,29.451426
Image_1,2.735806,37.725503,29.982642,4.545553,49.256506,51.918106,3.031953,26.240742,16.523277,4.085552,33.140695,11.070122
Image_2,3.434603,36.851759,22.953312,6.912656,46.863733,57.269122,4.374349,32.684325,51.637149,5.181348,34.069584,26.899376
Image_3,2.659767,32.229771,30.737268,6.914327,42.754361,73.476296,3.281560,30.733927,20.707339,4.437363,28.719413,19.987385
Image_4,3.767484,31.688425,17.671701,7.180791,45.748895,77.116439,8.550956,35.938298,38.016724,7.306275,28.871131,28.764793
...,...,...,...,...,...,...,...,...,...,...,...,...
Image_65,2.777234,43.200729,38.703307,6.093615,42.938518,72.791004,3.047835,41.091030,33.320184,3.610048,26.500192,18.504890
Image_66,2.792688,45.420560,35.496964,6.173645,47.071478,76.162518,2.864139,40.500945,33.687101,3.482456,30.500025,16.092923
Image_67,2.481728,37.397029,27.618703,5.480946,49.717212,68.533362,3.520596,15.413060,12.384541,4.603362,22.157631,11.237039
Image_68,4.235943,30.809488,27.689332,6.585783,46.635878,64.392460,7.859287,42.829335,58.709732,6.734469,31.804489,36.395705
Image_69,2.946533,37.368808,30.150811,6.657780,45.894805,68.307089,4.728433,36.416902,20.686266,4.901326,35.638626,18.941309

,niqe_ac,brisque_ac,piqe_ac,niqe_d,brisque_d,piqe_d,niqe_gi,brisque_gi,piqe_gi,niqe_um,brisque_um,piqe_um
count,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000
mean,3.072077,38.236884,30.888720,6.233498,46.946157,65.182662,4.302271,34.703971,29.673550,4.692545,30.501684,20.512845
std,0.745341,5.995269,7.448244,0.900790,3.004214,11.720947,2.014050,6.440421,11.914632,1.500762,5.007489,7.513021
min,2.192811,17.626593,11.314028,4.398634,42.754361,44.604398,2.250890,15.413060,9.818016,2.859328,18.084493,7.925170
25%,2.629594,34.921833,25.830458,5.545671,45.067934,55.674970,2.898826,30.887708,21.450278,3.507020,27.261567,15.559637
50%,2.854256,38.320608,31.223137,6.241191,46.584364,64.945225,3.265356,35.098913,27.805489,4.091953,30.623914,18.989487
75%,3.273912,43.051097,36.162226,6.888211,48.141754,74.121880,5.635154,40.493330,36.706895,5.789049,33.693028,25.062310
max,5.853248,49.972660,43.848825,8.268526,57.462236,100.000000,11.218927,46.175317,60.272168,8.513856,40.621886,41.631081

----------

In [8]:
print('NR QUALITY DARI DATA BARU\n')

for i in range(len(filename_nr_baru)):
    file = filename_nr_baru[i]
    print(file)
    df,df_stat = desc_stat(nr_baru,file)
    display(df)
    display(df_stat)
    print('-'*10)

NR QUALITY DARI DATA BARU

RAW_ALL_DATA.xlsx

,NIQE_CLEAN,NIQE_NOISY,BRISQUE_CLEAN,BRISQUE_NOISY,PIQE_CLEAN,PIQE_NOISY
Row,,,,,,
Image_0,4.548092,8.323092,22.165618,36.870879,25.433407,55.887956
Image_1,4.192090,8.372120,35.122634,34.625868,28.462263,48.029247
Image_2,4.439649,8.513634,30.657262,38.200781,31.719063,52.872282
Image_3,4.133718,9.112813,26.408538,39.115313,21.156054,58.076382
Image_4,3.905036,8.760867,31.411542,37.691803,23.846171,55.586442
...,...,...,...,...,...,...
Image_65,4.742068,9.615254,33.737955,35.859414,38.980056,54.671335
Image_66,3.749178,8.531281,31.982663,35.334255,29.024030,51.835163
Image_67,3.824661,8.590417,33.644051,38.008797,31.571667,52.824399
Image_68,4.369269,8.944901,28.921229,33.871422,30.145626,53.033735
Image_69,4.770841,7.477485,29.967022,38.950805,29.015997,51.473848

,NIQE_CLEAN,NIQE_NOISY,BRISQUE_CLEAN,BRISQUE_NOISY,PIQE_CLEAN,PIQE_NOISY
count,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000
mean,4.145784,8.421384,32.400383,35.419356,30.231647,52.988624
std,0.568613,0.520106,5.181506,1.829982,5.003823,2.335924
min,2.903658,6.776010,19.619698,31.915068,17.343760,46.155711
25%,3.796993,8.117586,29.785387,34.379264,27.274893,52.036738
50%,4.110418,8.450846,32.257411,34.956406,29.977473,52.987305
75%,4.542686,8.792985,35.099813,36.243501,33.994627,54.642688
max,5.665286,9.729360,47.435017,40.829715,39.563609,58.076382

----------
RAW_PROCESSED_DATA_PNG.xlsx

,RAW_NIQE_CLEAN,RAW_NIQE_NOISY,RAW_BRISQUE_CLEAN,RAW_BRISQUE_NOISY,RAW_PIQE_CLEAN,RAW_PIQE_NOISY
Row,,,,,,
Image_0,4.666544,4.996273,46.837154,20.270464,52.427711,15.715723
Image_1,4.034291,4.407665,39.159189,21.235177,48.335758,19.669640
Image_2,4.840829,4.618355,47.136054,11.425371,41.300552,18.219623
Image_3,4.176406,5.276888,43.593544,18.121687,46.397448,13.948137
Image_4,3.954878,4.371213,46.697247,25.974656,32.138658,17.943025
...,...,...,...,...,...,...
Image_65,6.795613,5.259872,48.324206,31.429775,67.240617,22.521586
Image_66,3.987337,4.425180,48.111605,13.535381,31.854754,22.314657
Image_67,4.487527,4.847033,46.434119,26.419246,51.443329,21.256124
Image_68,5.031743,4.687940,46.984480,18.238815,52.000534,21.441008
Image_69,4.820206,4.880912,47.073434,15.488616,39.946878,21.011959

,RAW_NIQE_CLEAN,RAW_NIQE_NOISY,RAW_BRISQUE_CLEAN,RAW_BRISQUE_NOISY,RAW_PIQE_CLEAN,RAW_PIQE_NOISY
count,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000
mean,4.686674,4.686473,46.637199,23.770544,48.576802,20.304777
std,0.725855,0.364128,1.940558,4.738919,11.276924,2.932982
min,3.499190,3.594489,39.159189,11.425371,25.449708,13.347553
25%,4.171751,4.417915,46.436900,21.001388,39.990611,18.241928
50%,4.655677,4.696773,47.046587,24.342049,47.026118,20.369637
75%,5.140403,4.941376,47.688303,27.628780,54.191985,22.283719
max,6.851912,5.338031,49.313595,32.037116,75.338168,26.938211

----------
RGB_SKIP_RAW_CLEAN.xlsx

,niqe_ac,brisque_ac,piqe_ac,niqe_d,brisque_d,piqe_d,niqe_gi,brisque_gi,piqe_gi,niqe_um,brisque_um,piqe_um
Row,,,,,,,,,,,,
Image_0,3.977985,45.864190,49.184078,4.905947,55.966803,68.380367,4.641428,48.969390,57.718809,3.067477,29.090500,43.469560
Image_1,9.991110,44.417902,50.000000,4.355358,42.267647,62.504424,10.086421,44.709384,52.773253,9.310910,44.668133,54.747866
Image_2,4.091765,47.079143,43.254055,4.818656,54.653880,67.518558,4.010590,27.289724,45.218375,3.805092,37.735505,60.137645
Image_3,6.675153,46.752318,93.787800,4.402516,55.303678,67.174256,5.279452,45.901017,60.475706,4.975950,46.811476,65.484156
Image_4,6.440196,45.934106,67.463092,4.654072,53.005019,59.263038,7.100531,47.198420,72.037483,4.284752,50.266799,58.105114
...,...,...,...,...,...,...,...,...,...,...,...,...
Image_65,5.109198,45.773172,68.513959,5.542932,53.477722,77.986418,6.038304,45.802794,71.542430,3.340435,47.924114,55.483007
Image_66,8.564656,44.410169,74.084530,4.793348,52.207254,79.383489,7.319260,44.721416,63.111364,8.405463,44.679469,65.294635
Image_67,3.777377,47.721449,47.380157,4.536375,50.856912,70.905411,3.857532,43.263843,49.700888,2.753400,26.920922,38.475120
Image_68,3.410629,44.586921,45.784606,4.844063,55.066510,71.764598,3.129078,38.691661,46.230704,3.392201,27.532400,35.627850
Image_69,5.703193,48.076975,42.385488,5.256157,50.888074,64.502443,5.743792,48.977693,48.285667,4.765737,48.350293,51.301598

,niqe_ac,brisque_ac,piqe_ac,niqe_d,brisque_d,piqe_d,niqe_gi,brisque_gi,piqe_gi,niqe_um,brisque_um,piqe_um
count,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000
mean,6.232195,46.395849,65.262535,4.797202,52.064170,69.500785,6.018201,44.668684,59.744806,5.278594,42.325808,58.043050
std,2.085081,1.872239,19.729558,0.473381,3.735402,8.282219,2.062628,5.933808,9.578044,2.316031,8.032774,9.474204
min,3.355656,42.866004,28.720336,3.775358,42.267647,49.960487,3.129078,18.882344,42.855663,2.399324,21.319876,32.124099
25%,4.624236,44.678697,50.059755,4.427508,49.119761,63.975415,4.490970,44.695339,52.825943,3.523220,38.363586,52.892659
50%,5.969944,46.287946,62.509580,4.776091,51.928506,70.218457,5.852478,45.779935,59.247152,4.681632,44.694632,59.814717
75%,7.266732,47.691430,77.604510,5.097611,55.240221,76.225173,7.018227,48.051338,66.897728,6.569972,47.459726,65.186280
max,12.238925,52.564180,100.000000,6.195688,58.209588,83.786309,12.361864,51.578345,83.079994,12.479566,56.725022,79.505089

----------
RGB_SKIP_RAW_NOISY.xlsx

,niqe_ac,brisque_ac,piqe_ac,niqe_d,brisque_d,piqe_d,niqe_gi,brisque_gi,piqe_gi,niqe_um,brisque_um,piqe_um
Row,,,,,,,,,,,,
Image_0,5.461010,44.438663,100.000000,4.854351,30.539927,40.442357,2.978768,41.980014,28.252530,4.608799,43.376106,49.004874
Image_1,5.593021,44.425974,39.807526,5.725512,28.219228,39.865073,7.757315,45.160738,42.455271,8.689554,45.278043,55.120838
Image_2,3.505851,35.989471,36.284282,3.881818,19.590834,37.259432,2.578338,23.848991,18.237502,6.793271,27.981332,22.894031
Image_3,2.853612,39.030897,23.535855,3.644181,26.462236,41.659178,2.516041,28.553167,16.612536,6.204392,21.334159,19.551044
Image_4,3.029629,29.273092,18.146800,5.202266,36.250535,46.523940,3.238820,29.885975,16.739254,5.971196,26.397598,29.456923
...,...,...,...,...,...,...,...,...,...,...,...,...
Image_65,3.825591,9.771143,24.027452,6.461047,35.472807,46.289595,2.804571,29.648657,15.988878,5.767708,35.835466,42.938699
Image_66,5.306561,46.915097,73.089852,3.431084,12.776518,34.902910,10.287246,50.910882,34.838656,12.753178,50.555350,52.985223
Image_67,2.736413,36.753370,20.118784,6.475393,33.883919,45.205792,5.913861,31.721417,25.531821,8.126812,27.477288,33.396573
Image_68,3.131520,36.450484,22.302970,4.496073,29.195064,40.503434,2.852401,38.842636,22.541726,3.614510,28.391196,18.581337
Image_69,2.899214,42.347103,32.378811,3.793645,17.608270,35.388943,4.450903,33.421294,41.147796,4.496143,23.839266,51.484717

,niqe_ac,brisque_ac,piqe_ac,niqe_d,brisque_d,piqe_d,niqe_gi,brisque_gi,piqe_gi,niqe_um,brisque_um,piqe_um
count,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000
mean,4.125925,38.757633,35.872254,4.936441,29.049449,40.869183,5.046800,36.336544,33.166915,6.319510,34.767552,43.019427
std,1.656674,10.040996,18.411284,0.790615,5.014150,3.070771,2.228776,10.544440,13.895488,1.729517,9.691618,15.358123
min,2.478769,9.771143,11.619435,3.431084,12.776518,33.700894,2.351429,12.779498,10.342120,3.614510,13.541623,16.885299
25%,3.034172,32.816775,22.611191,4.309597,26.877783,39.366858,2.891603,28.362827,22.897266,4.772372,27.489237,29.022179
50%,3.494239,43.542339,34.056915,4.908701,29.661846,40.635779,4.592622,39.489151,27.793811,6.192407,33.694176,45.817214
75%,4.693204,46.479128,42.778421,5.399691,32.831840,42.752748,6.773473,44.399023,43.203656,7.605743,43.458359,56.102857
max,10.931617,49.211562,100.000000,6.475393,36.461332,49.143611,10.287246,50.951396,68.445823,12.753178,50.555350,71.471950

----------
RGB_WITH_RAW_CLEAN.xlsx

,niqe_ac,brisque_ac,piqe_ac,niqe_d,brisque_d,piqe_d,niqe_gi,brisque_gi,piqe_gi,niqe_um,brisque_um,piqe_um
Row,,,,,,,,,,,,
Image_0,6.177631,49.406291,66.579640,8.155743,46.713186,81.763503,5.369323,48.947843,63.396838,4.188347,48.624589,57.720751
Image_1,10.918987,44.422862,65.850155,5.051882,50.116532,64.386055,10.432059,44.729209,62.999096,9.553775,44.707685,64.567563
Image_2,5.923248,49.071066,60.687980,7.665385,46.457822,75.167932,4.791741,49.083714,60.480972,4.048965,49.282086,53.912776
Image_3,4.867302,47.960692,65.382895,7.031349,48.267488,82.213165,3.652891,45.362828,58.728150,3.186230,42.394253,54.166579
Image_4,4.204292,47.996766,57.795184,6.747075,48.585894,80.272231,3.184580,45.578339,46.335301,3.276316,44.493122,44.261354
...,...,...,...,...,...,...,...,...,...,...,...,...
Image_65,6.060409,50.607046,68.563931,8.904063,47.700376,94.725365,5.356770,51.427077,55.511477,4.901349,50.887635,59.063947
Image_66,5.306919,49.269980,64.421972,6.786179,46.673958,83.140170,5.268211,49.241835,65.488528,3.742448,50.365166,53.451508
Image_67,4.684915,47.710927,61.190239,6.366458,47.950742,79.660710,3.331156,46.591398,45.522478,3.296876,45.660667,44.762489
Image_68,4.931834,48.697503,63.220929,6.825423,45.684161,75.115015,6.417073,51.343547,46.912257,3.901994,49.724121,54.399251
Image_69,6.451205,49.490972,64.007864,6.414301,47.593495,76.975467,5.617554,49.180007,55.815814,4.628618,49.314494,52.827272

,niqe_ac,brisque_ac,piqe_ac,niqe_d,brisque_d,piqe_d,niqe_gi,brisque_gi,piqe_gi,niqe_um,brisque_um,piqe_um
count,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000
mean,5.450693,48.364037,61.503033,7.088829,47.636262,75.651916,5.269941,47.799968,53.508524,4.196084,46.747215,50.782026
std,1.250490,1.689575,8.492010,1.147456,1.216111,10.765676,1.859779,3.498250,10.654902,1.128592,4.209060,9.936832
min,3.925449,42.165216,42.568790,4.645516,45.306200,50.168079,3.071241,30.100373,28.465954,2.768529,32.454825,26.574019
25%,4.603388,47.584332,56.591946,6.272274,47.071453,67.257503,3.976368,46.322510,46.799812,3.524969,45.254241,44.923924
50%,5.126856,48.685771,61.785460,7.029865,47.660854,77.001139,4.543506,48.717645,53.694522,4.021137,48.327032,51.735730
75%,6.018437,49.537950,66.512951,8.006456,47.990167,83.113923,6.164677,49.709722,60.358579,4.525329,49.650282,56.464390
max,10.918987,50.824340,86.112507,9.167002,52.725400,100.000000,11.600242,52.260517,85.221950,9.553775,51.296768,74.290740

----------
RGB_WITH_RAW_NOISY.xlsx

,niqe_ac,brisque_ac,piqe_ac,niqe_d,brisque_d,piqe_d,niqe_gi,brisque_gi,piqe_gi,niqe_um,brisque_um,piqe_um
Row,,,,,,,,,,,,
Image_0,2.986558,42.018189,36.947941,6.784363,47.359694,70.588636,3.767696,44.040772,38.556634,3.764705,34.447348,17.897546
Image_1,10.779140,44.436486,62.385081,4.689139,51.374236,51.089219,11.506760,44.720918,54.450609,11.284369,44.680128,57.608602
Image_2,3.843942,46.472377,35.049675,5.890588,47.457851,56.569170,3.573312,46.009519,32.263717,5.179836,44.211949,16.105462
Image_3,2.430397,43.815834,34.642254,5.945846,46.720973,74.142274,3.131230,31.623036,20.046157,3.812508,29.066904,16.815740
Image_4,3.146070,39.432447,32.553563,5.744158,46.498642,62.562680,4.748629,35.071285,18.459561,4.864027,34.434204,17.291153
...,...,...,...,...,...,...,...,...,...,...,...,...
Image_65,3.608034,37.422075,33.525379,7.825041,48.543271,91.389131,8.364155,43.285309,43.515582,5.982902,36.448623,29.239927
Image_66,3.695366,48.642012,36.047067,5.824500,47.719222,76.467494,3.657316,47.568585,36.759173,4.435343,48.452836,16.788307
Image_67,2.975979,42.923075,40.907974,5.540124,47.224095,64.639282,3.023315,34.555283,24.161113,4.008662,34.584962,20.243962
Image_68,3.723009,47.121153,35.378023,5.802391,46.855044,65.119697,10.584683,49.420862,54.771339,6.816696,47.235803,25.802874
Image_69,3.669595,45.684312,39.348667,5.518368,47.647847,67.712835,3.381208,44.999630,37.858566,4.763136,42.367973,20.883398

,niqe_ac,brisque_ac,piqe_ac,niqe_d,brisque_d,piqe_d,niqe_gi,brisque_gi,piqe_gi,niqe_um,brisque_um,piqe_um
count,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000
mean,4.013707,43.585089,39.182003,6.069234,47.847444,63.751242,5.315103,42.430203,35.211630,5.180811,39.541724,25.978226
std,1.754188,3.549641,12.521469,0.842794,1.138408,12.104864,2.815885,5.458871,14.921080,2.103706,6.024566,12.961960
min,2.430397,34.133729,19.355952,4.238524,46.101307,33.333333,2.691357,28.676472,13.398406,2.749185,26.818160,11.950565
25%,3.091295,40.575858,33.608898,5.523807,47.131056,56.603126,3.362207,37.717081,22.975130,3.804505,34.481751,18.080878
50%,3.393682,44.437904,37.432259,5.945161,47.650302,63.221728,3.956699,43.960040,32.197552,4.428370,40.128336,20.961020
75%,4.126633,46.272120,42.132538,6.703954,48.385085,72.635320,6.944731,46.506534,43.542367,5.741808,44.563083,29.904852
max,12.398225,49.210675,100.000000,7.825041,51.746544,94.454884,12.701289,50.509025,81.580574,12.707766,49.773073,65.815257

----------

# VPMI

In [33]:
def desc_stat_vpmi(path,filename):
    alldata_excel = path + filename
    
    excel_file = pd.ExcelFile(alldata_excel)
    sheets_name = excel_file.sheet_names
    
    if 'Sheet1' in sheets_name:
        sheets_name.remove('Sheet1')
        
    sheets_name = sorted(sheets_name)
    
    for sheet in sheets_name:
        nr_data = pd.read_excel(alldata_excel,index_col = 0,sheet_name = sheet)
        print(f'Excel file on {filename} displayng data on sheet "{sheet}"')
        display(nr_data)
        display(nr_data.describe())
        print('\n')

In [34]:
print('VPMI QUALITY DARI DATA LAMA\n')

for i in range(len(filename_vpmi_lama)):
    file = filename_vpmi_lama[i]
    
    desc_stat_vpmi(vpmi_lama,file)
    
    print('-'*10)

VPMI QUALITY DARI DATA LAMA

Excel file on RAW_ALL_DATA_VPMI.xlsx displayng data on sheet "clean"

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
Image_0,5.494380,0.366636,0.332031,19.572307,0.153508,0.603689,-0.074760
Image_1,5.616277,0.827521,0.707031,19.532777,0.153198,1.351792,0.218918
Image_2,5.762044,0.813334,0.518229,34.598903,0.271364,0.721933,-0.309795
Image_3,6.100254,0.342880,0.582031,31.126869,0.244132,0.713987,-0.144453
Image_4,5.621621,0.566713,0.444010,23.245190,0.182315,0.873941,-0.050132
...,...,...,...,...,...,...,...
Image_65,6.157265,0.650945,0.721354,37.737773,0.295983,0.777976,-0.309955
Image_66,6.150773,0.444528,0.822917,34.137293,0.267743,0.901897,-0.089741
Image_67,6.222378,0.509621,0.686198,33.777521,0.264922,1.292715,0.213523
Image_68,5.602684,0.930516,0.385417,20.979915,0.164548,0.694724,-0.173743
Image_69,5.695329,0.711989,0.610677,26.813958,0.210306,0.557395,-0.439137

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000
mean,5.820865,0.465139,0.622879,27.310717,0.214202,0.874795,-0.068335
std,0.352521,0.266847,0.141219,6.981559,0.054757,0.249384,0.152087
min,4.873848,0.053145,0.316406,16.038969,0.125796,0.462451,-0.439137
25%,5.606082,0.219554,0.519531,22.529591,0.176703,0.698119,-0.152723
50%,5.808999,0.490040,0.662760,26.018839,0.204069,0.820328,-0.063690
75%,6.077336,0.685058,0.722331,31.123668,0.244107,0.995310,-0.000981
max,6.495364,0.930516,0.897135,46.343912,0.363482,1.524823,0.345833

Excel file on RAW_ALL_DATA_VPMI.xlsx displayng data on sheet "noisy"

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
Image_0,5.549827,0.408320,0.528646,19.399624,0.152154,4.698266,0.406862
Image_1,5.570945,0.615989,0.765625,19.300560,0.151377,4.581947,0.873378
Image_2,5.913414,0.772846,0.692708,34.613095,0.271475,4.856643,1.959472
Image_3,6.178752,0.426102,0.710938,30.572305,0.239783,5.042135,1.047541
Image_4,5.769070,0.497198,0.545573,22.607024,0.177310,5.049414,0.648210
...,...,...,...,...,...,...,...
Image_65,6.173882,0.636915,0.864583,37.264598,0.292271,4.995749,2.305961
Image_66,6.102731,0.455743,0.871094,33.900094,0.265883,4.665257,1.431315
Image_67,6.216190,0.568673,0.752604,33.186550,0.260287,5.288221,1.663873
Image_68,5.685593,0.762657,0.524740,20.876571,0.163738,4.329626,0.787685
Image_69,5.721459,0.653901,0.777344,26.916606,0.211111,4.380525,1.308418

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000
mean,5.849944,0.473734,0.734263,27.056604,0.212209,4.716067,0.997214
std,0.316003,0.162605,0.123679,6.853832,0.053756,0.457813,0.564082
min,5.118055,0.200035,0.455729,16.248963,0.127443,3.754532,0.148395
25%,5.685884,0.349302,0.641927,22.236837,0.174407,4.338228,0.646671
50%,5.841043,0.458956,0.761719,25.816657,0.202484,4.765628,0.837173
75%,6.066632,0.614374,0.829102,30.731008,0.241028,5.037387,1.224042
max,6.475667,0.786832,0.960938,45.690806,0.358359,5.882193,2.745356

----------
Excel file on RAW_PROCESSED_DATA_VPMI.xlsx displayng data on sheet "clean"

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
Image_0,3.626207,0.127602,0.161458,5.201941,0.040800,0.244568,-0.006193
Image_1,3.826839,0.585978,0.483073,5.822581,0.045667,0.550764,-0.042568
Image_2,4.096580,0.941928,0.247396,11.632973,0.091239,0.277615,-0.161032
Image_3,4.373950,0.156413,0.305990,10.128479,0.079439,0.312265,-0.027924
Image_4,3.915787,0.386199,0.212240,5.923364,0.046458,0.377921,-0.020933
...,...,...,...,...,...,...,...
Image_65,4.739425,0.837127,0.432292,13.338811,0.104618,0.389855,-0.243846
Image_66,4.402717,0.297633,0.571615,10.710880,0.084007,0.386044,-0.086406
Image_67,4.669734,0.544647,0.403646,10.197717,0.079982,0.542155,-0.072522
Image_68,3.579324,0.884032,0.170573,5.675718,0.044515,0.270983,-0.045259
Image_69,4.025126,0.703732,0.343750,9.036146,0.070872,0.236369,-0.143599

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000
mean,4.073923,0.344784,0.374702,8.407172,0.065939,0.381300,-0.052001
std,0.459959,0.291139,0.130188,2.990166,0.023452,0.110256,0.060492
min,3.054945,0.012333,0.138021,4.472888,0.035081,0.183667,-0.278068
25%,3.726034,0.099261,0.267904,6.003654,0.047087,0.302283,-0.062716
50%,4.041389,0.256211,0.394531,7.804493,0.061212,0.374032,-0.032344
75%,4.382089,0.562782,0.462240,9.909010,0.077718,0.455611,-0.009199
max,5.230353,0.941928,0.684896,17.514057,0.137365,0.689165,-0.000600

Excel file on RAW_PROCESSED_DATA_VPMI.xlsx displayng data on sheet "noisy"

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
Image_0,3.706887,0.211101,0.263021,5.132414,0.040254,1.019486,0.000231
Image_1,3.897556,0.501950,0.549479,5.872872,0.046062,1.274704,0.017339
Image_2,4.409656,0.894629,0.393229,11.737589,0.092060,1.338410,0.060055
Image_3,4.581224,0.274619,0.428385,9.951028,0.078047,1.350766,0.018246
Image_4,3.994368,0.340668,0.283854,6.023607,0.047244,1.180085,0.004359
...,...,...,...,...,...,...,...
Image_65,4.800746,0.793396,0.643229,13.501139,0.105891,1.480288,0.146807
Image_66,4.465646,0.291616,0.626302,10.780588,0.084554,1.356988,0.030372
Image_67,4.686955,0.580432,0.484375,10.416932,0.081701,1.509818,0.063990
Image_68,3.790709,0.700642,0.269531,5.626457,0.044129,1.028173,0.001266
Image_69,4.096880,0.672177,0.509115,9.063031,0.071083,1.122045,0.016556

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000
mean,4.179498,0.363907,0.484003,8.458489,0.066341,1.261823,0.025485
std,0.428536,0.235747,0.134298,2.995585,0.023495,0.197887,0.042344
min,3.260662,0.052692,0.244792,4.491076,0.035224,0.913035,-0.002587
25%,3.842055,0.183396,0.378255,6.120871,0.048007,1.122755,0.003282
50%,4.170171,0.292865,0.488932,7.963458,0.062458,1.240375,0.009655
75%,4.506092,0.547300,0.578451,9.882243,0.077508,1.376474,0.019483
max,5.249121,0.894629,0.821615,17.479702,0.137096,1.777892,0.201858

----------
Excel file on RGB_SKIP_RAW_CLEAN.xlsx displayng data on sheet "Clean Synthetic Image (Without "

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
Image_0,5.520986,0.373338,0.332031,19.572037,0.153506,0.524227,-0.097885
Image_1,5.623621,0.815797,0.712240,19.521323,0.153108,1.334360,0.208195
Image_2,5.769632,0.813980,0.516927,34.617846,0.271513,0.636272,-0.429951
Image_3,6.105492,0.349888,0.580729,31.150937,0.244321,0.626207,-0.204679
Image_4,5.627677,0.568038,0.447917,23.280507,0.182592,0.805881,-0.081405
...,...,...,...,...,...,...,...
Image_65,6.157151,0.651081,0.717448,37.732927,0.295945,0.686636,-0.461660
Image_66,6.151737,0.437833,0.816406,34.104856,0.267489,0.833558,-0.154485
Image_67,6.223274,0.509332,0.683594,33.773660,0.264891,1.232064,0.172808
Image_68,5.600573,0.930290,0.382812,20.969484,0.164467,0.609271,-0.234491
Image_69,5.743432,0.711905,0.610677,26.824283,0.210387,0.495525,-0.532133

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000
mean,5.834638,0.464117,0.624479,27.309625,0.214193,0.809953,-0.111695
std,0.342825,0.265931,0.143112,6.979130,0.054738,0.260957,0.175707
min,4.987271,0.052440,0.313802,16.066513,0.126012,0.392922,-0.532133
25%,5.606335,0.220024,0.519857,22.509953,0.176549,0.627775,-0.203659
50%,5.822832,0.490701,0.666667,26.014569,0.204036,0.745536,-0.081906
75%,6.085399,0.681713,0.716471,31.144168,0.244268,0.938648,-0.010656
max,6.500450,0.930290,0.907552,46.345742,0.363496,1.473581,0.271918

Excel file on RGB_SKIP_RAW_CLEAN.xlsx displayng data on sheet "Conditional Contrast Correction"

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
Image_0,5.958851,0.391115,0.528646,35.092791,0.275238,0.360609,-0.498997
Image_1,NaN,0.776337,0.503906,221.374855,0.263727,0.834401,NaN
Image_2,5.823908,0.689147,0.817708,62.420383,0.489572,0.404783,-2.096418
Image_3,6.239537,0.405021,0.885417,50.727202,0.397860,0.377433,-1.251420
Image_4,6.620443,0.607213,0.907552,52.942641,0.415236,0.562000,-1.259456
...,...,...,...,...,...,...,...
Image_65,5.786085,0.747825,0.583333,44.742740,0.350923,0.344667,-1.361164
Image_66,NaN,0.049421,0.385417,246.167257,0.069276,0.055037,NaN
Image_67,5.917215,0.530261,0.699219,54.862756,0.430296,0.525322,-0.876749
Image_68,6.341351,0.826134,0.980469,52.967372,0.415430,0.603577,-1.554275
Image_69,5.863268,0.684200,0.781250,38.445931,0.301537,0.277960,-1.745549

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,60.000000,70.000000,70.000000,70.000000,70.000000,70.000000,60.000000
mean,5.809334,0.450457,0.743062,84.828232,0.421792,0.483652,-1.055578
std,0.614222,0.235633,0.178777,64.140806,0.165950,0.242537,0.787908
min,3.579819,0.004258,0.265625,31.119027,0.003685,0.013168,-3.165916
25%,5.472950,0.236836,0.663086,48.513242,0.329114,0.370579,-1.491695
50%,5.893314,0.455280,0.765625,59.648220,0.432380,0.445101,-0.838063
75%,6.280549,0.661455,0.886393,79.262345,0.508908,0.595085,-0.495354
max,6.760688,0.935184,0.980469,254.530138,0.756261,1.432985,0.376747

Excel file on RGB_SKIP_RAW_CLEAN.xlsx displayng data on sheet "Contrast Fixing Image.jpg"

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
Image_0,6.171286,0.418516,0.506510,30.802391,0.241587,0.243973,-0.643220
Image_1,6.142153,0.839827,0.970052,28.437150,0.223036,0.944394,-0.092118
Image_2,5.740377,0.610121,0.970052,70.714332,0.554622,0.412353,-2.408218
Image_3,6.370094,0.457936,0.977865,54.349981,0.426274,0.316889,-2.016002
Image_4,6.725499,0.602470,0.975260,58.183756,0.456343,0.504902,-1.777936
...,...,...,...,...,...,...,...
Image_65,6.227214,0.512062,0.957031,50.333495,0.394773,0.342317,-1.863227
Image_66,6.213586,0.439995,0.924479,39.093046,0.306612,0.279689,-1.424447
Image_67,6.592207,0.445602,1.000000,55.298210,0.433711,0.752868,-0.521754
Image_68,6.390105,0.809717,0.990885,55.013578,0.431479,0.534941,-1.996620
Image_69,5.873263,0.597850,0.962240,45.647225,0.358017,0.253754,-2.393286

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000
mean,6.254363,0.457577,0.943080,44.716204,0.350715,0.497316,-1.056996
std,0.381382,0.238458,0.082163,12.738124,0.099907,0.251813,0.929380
min,4.886057,0.064302,0.506510,23.249625,0.182350,0.228234,-4.102095
25%,6.076282,0.235511,0.927734,34.075855,0.267262,0.316772,-1.777111
50%,6.236210,0.457329,0.970052,44.458866,0.348697,0.413806,-0.824989
75%,6.563500,0.659017,0.985677,54.630864,0.428477,0.595122,-0.345767
max,6.870866,0.939439,1.000000,79.974740,0.627253,1.351306,0.423530

Excel file on RGB_SKIP_RAW_CLEAN.xlsx displayng data on sheet "Denoised Image.jpg"

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
Image_0,5.479673,0.337353,0.321615,19.077298,0.149626,0.129719,-0.262116
Image_1,5.573687,0.836109,0.695312,18.888542,0.148145,0.629794,-0.320207
Image_2,5.697191,0.812829,0.501302,34.139794,0.267763,0.184761,-1.514384
Image_3,6.074172,0.298314,0.569010,30.663986,0.240502,0.167430,-0.639359
Image_4,5.593308,0.545538,0.419271,22.745411,0.178395,0.199365,-0.530980
...,...,...,...,...,...,...,...
Image_65,6.129086,0.649518,0.708333,37.279070,0.292385,0.225451,-1.771899
Image_66,6.104978,0.425830,0.838542,33.633147,0.263789,0.218299,-1.262583
Image_67,6.189193,0.503843,0.649740,33.199382,0.260387,0.458211,-0.594012
Image_68,5.550062,0.929722,0.365885,20.473796,0.160579,0.198488,-0.707253
Image_69,5.683348,0.706021,0.596354,26.385012,0.206941,0.142885,-1.390041

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000
mean,5.787401,0.453801,0.612277,26.782854,0.210062,0.294599,-0.619142
std,0.357680,0.274741,0.147814,6.993679,0.054852,0.162504,0.496736
min,4.896322,0.040659,0.307292,15.443368,0.121124,0.101013,-2.152440
25%,5.555968,0.198519,0.504557,21.984921,0.172431,0.193801,-0.864448
50%,5.775725,0.488707,0.643880,25.527491,0.200216,0.241349,-0.483512
75%,6.050811,0.673028,0.713216,30.656389,0.240442,0.340710,-0.272719
max,6.474314,0.934535,0.899740,45.864262,0.359720,0.796058,-0.045027

Excel file on RGB_SKIP_RAW_CLEAN.xlsx displayng data on sheet "Global Mean Contrast (Sat. Fix "

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
Image_0,4.920719,0.296069,0.221354,14.336409,0.112442,0.162055,-0.095201
Image_1,4.337053,0.684300,0.325521,9.093333,0.071320,0.399717,-0.091154
Image_2,5.737660,0.814378,0.486979,41.771487,0.327620,0.253164,-1.477453
Image_3,5.563506,0.308978,0.394531,25.795331,0.202316,0.185181,-0.333834
Image_4,5.992571,0.610716,0.531250,38.406990,0.301231,0.345738,-0.897389
...,...,...,...,...,...,...,...
Image_65,4.767133,0.900724,0.227865,12.915389,0.101297,0.140753,-0.280362
Image_66,3.205048,0.228891,0.169271,7.606988,0.059663,0.126652,-0.022086
Image_67,5.337856,0.548454,0.399740,21.279582,0.166899,0.350111,-0.295731
Image_68,6.100586,0.898736,0.529948,36.223662,0.284107,0.346409,-1.262568
Image_69,5.410496,0.746656,0.397135,22.010129,0.172628,0.158267,-0.736580

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000
mean,4.852913,0.424118,0.347228,18.969005,0.148777,0.253942,-0.294286
std,0.938059,0.280205,0.117013,11.517814,0.090336,0.115860,0.394233
min,2.843068,0.040873,0.135417,3.951034,0.030988,0.116290,-1.934907
25%,4.219897,0.160451,0.249674,9.497758,0.074492,0.171574,-0.324308
50%,4.905237,0.426696,0.337240,15.273034,0.119789,0.228340,-0.122205
75%,5.669127,0.667200,0.425130,27.109418,0.212623,0.300607,-0.050840
max,6.469994,0.920109,0.597656,51.381902,0.402995,0.723810,-0.002721

Excel file on RGB_SKIP_RAW_CLEAN.xlsx displayng data on sheet "Grayness Index.jpg"

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
Image_0,4.144715,0.299823,0.298177,15.876938,0.124525,0.326118,-0.074589
Image_1,6.398135,0.673609,0.990885,148.121507,0.838263,7.183900,10.183833
Image_2,4.252249,0.558350,0.338542,22.448315,0.176065,0.280077,-0.259842
Image_3,4.627969,0.237565,0.337240,17.877040,0.140212,0.318465,-0.085820
Image_4,5.362847,0.483249,0.401042,19.961825,0.156563,0.453131,-0.185828
...,...,...,...,...,...,...,...
Image_65,1.818280,0.339409,0.127604,2.972965,0.023317,0.194807,-0.004333
Image_66,2.262258,0.196572,0.255208,2.294516,0.017996,0.292958,-0.003618
Image_67,4.354663,0.598834,0.330729,18.366048,0.144047,0.359915,-0.183154
Image_68,5.258691,0.905811,0.381510,21.354047,0.167483,0.518929,-0.288046
Image_69,4.175452,0.510437,0.305990,14.539359,0.114034,0.238108,-0.153965

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000
mean,4.030032,0.318984,0.357310,23.760891,0.155490,0.627379,0.192890
std,1.450537,0.195833,0.213916,37.913475,0.191037,0.994157,1.320121
min,0.858197,0.040162,0.117188,0.534964,0.004196,0.104779,-0.540789
25%,2.621536,0.169377,0.195964,4.289787,0.033645,0.243937,-0.118183
50%,4.303456,0.255879,0.335938,15.247049,0.119585,0.355945,-0.017037
75%,5.249453,0.467733,0.398112,22.420241,0.175845,0.513390,-0.003699
max,6.398135,0.905811,1.000000,215.250419,0.923191,7.183900,10.183833

Excel file on RGB_SKIP_RAW_CLEAN.xlsx displayng data on sheet "Histogram Stretched.jpg"

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
Image_0,5.958851,0.391115,0.528646,35.092791,0.275238,0.360609,-0.498997
Image_1,4.532049,0.715152,0.694010,111.387270,0.873626,0.591545,-1.488447
Image_2,5.823908,0.689147,0.817708,62.420383,0.489572,0.404783,-2.096418
Image_3,6.239537,0.405021,0.885417,50.727202,0.397860,0.377433,-1.251420
Image_4,6.620443,0.607213,0.907552,52.942641,0.415236,0.562000,-1.259456
...,...,...,...,...,...,...,...
Image_65,5.786085,0.747825,0.583333,44.742740,0.350923,0.344667,-1.361164
Image_66,3.634419,0.311058,0.484375,137.234182,0.923653,0.186296,-1.226193
Image_67,5.917215,0.530261,0.699219,54.862756,0.430296,0.525322,-0.876749
Image_68,6.341351,0.826134,0.980469,52.967372,0.415430,0.603577,-1.554275
Image_69,5.863268,0.684200,0.781250,38.445931,0.301537,0.277960,-1.745549

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,69.000000,70.000000,70.000000,70.000000,70.000000,70.000000,69.000000
mean,5.573593,0.463049,0.759784,68.105553,0.522869,0.473652,-1.099067
std,0.988598,0.219288,0.149974,27.961545,0.193114,0.218606,0.777479
min,1.379431,0.069312,0.436198,31.119027,0.244071,0.157328,-3.165916
25%,5.219907,0.276711,0.672526,48.513242,0.380496,0.363023,-1.488447
50%,5.786085,0.475006,0.773438,59.648220,0.467829,0.424755,-0.876749
75%,6.238643,0.661455,0.886393,79.262345,0.621665,0.543959,-0.514846
max,6.760688,0.935184,0.980469,145.021608,0.991353,1.432985,0.376747

Excel file on RGB_SKIP_RAW_CLEAN.xlsx displayng data on sheet "S-Curve Correction.jpg"

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
Image_0,5.438120,0.323262,0.339844,20.734732,0.162625,0.234890,-0.203051
Image_1,4.792233,0.709692,0.539062,12.530904,0.098282,0.574654,-0.144010
Image_2,5.757904,0.685260,0.820312,67.366958,0.528368,0.400766,-2.255985
Image_3,6.062049,0.361392,0.661458,39.175162,0.307256,0.282113,-0.812868
Image_4,6.605491,0.603931,0.908854,59.542496,0.467000,0.567337,-1.384551
...,...,...,...,...,...,...,...
Image_65,5.275212,0.844510,0.352865,18.677866,0.146493,0.226226,-0.493774
Image_66,3.556020,0.262723,0.260417,10.824577,0.084899,0.163203,-0.054019
Image_67,5.912607,0.530320,0.664062,31.545687,0.247417,0.531618,-0.469604
Image_68,6.256465,0.836434,0.934896,56.944157,0.446621,0.562573,-1.813353
Image_69,5.699822,0.691057,0.664062,33.568587,0.263283,0.229507,-1.462299

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000
mean,5.264620,0.434012,0.575037,28.601125,0.224323,0.379944,-0.528632
std,0.938461,0.253591,0.211954,18.799240,0.147445,0.192695,0.668988
min,3.079944,0.039371,0.195312,5.267093,0.041311,0.155816,-3.244277
25%,4.636976,0.211835,0.396159,13.347169,0.104684,0.233527,-0.717689
50%,5.372894,0.450693,0.554688,22.154395,0.173760,0.344026,-0.246775
75%,6.038617,0.662544,0.720703,41.828274,0.328065,0.448031,-0.105522
max,6.605491,0.951021,0.980469,83.289424,0.653250,1.176697,0.128212

Excel file on RGB_SKIP_RAW_CLEAN.xlsx displayng data on sheet "Saturation Fixing.jpg"

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
Image_0,5.035359,0.279258,0.260417,14.654041,0.114934,0.189357,-0.101044
Image_1,4.489528,0.659600,0.403646,9.376653,0.073542,0.488542,-0.090846
Image_2,5.811955,0.767502,0.579427,41.739668,0.327370,0.292826,-1.499252
Image_3,5.841796,0.324630,0.475260,25.833427,0.202615,0.221752,-0.396821
Image_4,6.284648,0.607216,0.645833,38.277917,0.300219,0.422028,-0.920893
...,...,...,...,...,...,...,...
Image_65,4.907720,0.877049,0.268229,13.160477,0.103219,0.210198,-0.268157
Image_66,3.422115,0.228808,0.208333,7.896516,0.061933,0.145959,-0.028049
Image_67,5.520321,0.547368,0.475260,21.448893,0.168227,0.418994,-0.303189
Image_68,6.338103,0.874482,0.643229,36.280461,0.284553,0.424387,-1.254438
Image_69,5.456269,0.713878,0.475260,22.209273,0.174190,0.182017,-0.792560

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000
mean,5.012691,0.415984,0.418211,19.191281,0.150520,0.305639,-0.310961
std,0.943608,0.271279,0.141430,11.409663,0.089488,0.140014,0.410431
min,3.018292,0.030783,0.161458,4.351580,0.034130,0.145959,-2.015654
25%,4.375030,0.170891,0.301432,9.874557,0.077448,0.210537,-0.391753
50%,5.011635,0.421338,0.404297,15.524466,0.121761,0.270106,-0.130149
75%,5.836948,0.629103,0.511068,27.309581,0.214193,0.359223,-0.053066
max,6.607597,0.936419,0.726562,51.401889,0.403152,0.877588,-0.003849

Excel file on RGB_SKIP_RAW_CLEAN.xlsx displayng data on sheet "Unsharp Masking.jpg"

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
Image_0,5.998678,0.397484,0.563802,35.067070,0.275036,0.680419,-0.205390
Image_1,6.592216,0.730690,1.000000,207.184999,0.375020,9.812951,5.951584
Image_2,5.850636,0.687582,0.867188,62.392563,0.489353,0.722915,-0.799103
Image_3,6.268675,0.417315,0.933594,50.713950,0.397756,0.704426,-0.491042
Image_4,6.640276,0.612341,0.981771,52.927509,0.415118,1.100494,0.228936
...,...,...,...,...,...,...,...
Image_65,5.840271,0.748220,0.619792,44.764169,0.351092,0.640000,-0.612234
Image_66,6.355934,0.069811,0.876302,244.562641,0.081862,0.429557,-0.038803
Image_67,5.948658,0.533465,0.777344,54.868910,0.430344,0.901386,-0.159008
Image_68,6.374440,0.825385,0.988281,52.955904,0.415340,1.113426,0.334759
Image_69,5.880035,0.682778,0.815104,38.461496,0.301659,0.503437,-0.977407

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,67.000000,70.000000,70.000000,70.000000,70.000000,70.000000,67.000000
mean,5.944428,0.454368,0.854594,84.044949,0.427991,1.243048,0.072498
std,0.542287,0.227861,0.140723,62.398526,0.159439,1.334780,1.213840
min,4.632074,0.010143,0.423177,31.156768,0.019803,0.282859,-2.152597
25%,5.630164,0.258294,0.793620,48.532254,0.330422,0.714642,-0.383680
50%,5.998678,0.455437,0.901693,59.650954,0.433095,0.850309,-0.161913
75%,6.378107,0.651018,0.956706,79.278472,0.508965,1.169937,0.198351
max,6.787281,0.930711,1.000000,252.475149,0.756455,9.812951,5.951584

----------
Excel file on RGB_SKIP_RAW_CLEAN_global.xlsx displayng data on sheet "After Contrast Conditional Enha"

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
Image_0,5.958851,0.391115,0.528646,35.092791,0.275238,0.360609,-0.498997
Image_1,NaN,0.776337,0.503906,221.374855,0.263727,0.834401,NaN
Image_2,5.823908,0.689147,0.817708,62.420383,0.489572,0.404783,-2.096418
Image_3,6.239537,0.405021,0.885417,50.727202,0.397860,0.377433,-1.251420
Image_4,6.620443,0.607213,0.907552,52.942641,0.415236,0.562000,-1.259456
...,...,...,...,...,...,...,...
Image_65,5.786085,0.747825,0.583333,44.742740,0.350923,0.344667,-1.361164
Image_66,NaN,0.049421,0.385417,246.167257,0.069276,0.055037,NaN
Image_67,5.917215,0.530261,0.699219,54.862756,0.430296,0.525322,-0.876749
Image_68,6.341351,0.826134,0.980469,52.967372,0.415430,0.603577,-1.554275
Image_69,5.863268,0.684200,0.781250,38.445931,0.301537,0.277960,-1.745549

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,60.000000,70.000000,70.000000,70.000000,70.000000,70.000000,60.000000
mean,5.809334,0.450457,0.743062,84.828232,0.421792,0.483652,-1.055578
std,0.614222,0.235633,0.178777,64.140806,0.165950,0.242537,0.787908
min,3.579819,0.004258,0.265625,31.119027,0.003685,0.013168,-3.165916
25%,5.472950,0.236836,0.663086,48.513242,0.329114,0.370579,-1.491695
50%,5.893314,0.455280,0.765625,59.648220,0.432380,0.445101,-0.838063
75%,6.280549,0.661455,0.886393,79.262345,0.508908,0.595085,-0.495354
max,6.760688,0.935184,0.980469,254.530138,0.756261,1.432985,0.376747

Excel file on RGB_SKIP_RAW_CLEAN_global.xlsx displayng data on sheet "Denoised Image.jpg"

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
Image_0,5.479673,0.337353,0.321615,19.077298,0.149626,0.129719,-0.262116
Image_1,5.573687,0.836109,0.695312,18.888542,0.148145,0.629794,-0.320207
Image_2,5.697191,0.812829,0.501302,34.139794,0.267763,0.184761,-1.514384
Image_3,6.074172,0.298314,0.569010,30.663986,0.240502,0.167430,-0.639359
Image_4,5.593308,0.545538,0.419271,22.745411,0.178395,0.199365,-0.530980
...,...,...,...,...,...,...,...
Image_65,6.129086,0.649518,0.708333,37.279070,0.292385,0.225451,-1.771899
Image_66,6.104978,0.425830,0.838542,33.633147,0.263789,0.218299,-1.262583
Image_67,6.189193,0.503843,0.649740,33.199382,0.260387,0.458211,-0.594012
Image_68,5.550062,0.929722,0.365885,20.473796,0.160579,0.198488,-0.707253
Image_69,5.683348,0.706021,0.596354,26.385012,0.206941,0.142885,-1.390041

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000
mean,5.787401,0.453801,0.612277,26.782854,0.210062,0.294599,-0.619142
std,0.357680,0.274741,0.147814,6.993679,0.054852,0.162504,0.496736
min,4.896322,0.040659,0.307292,15.443368,0.121124,0.101013,-2.152440
25%,5.555968,0.198519,0.504557,21.984921,0.172431,0.193801,-0.864448
50%,5.775725,0.488707,0.643880,25.527491,0.200216,0.241349,-0.483512
75%,6.050811,0.673028,0.713216,30.656389,0.240442,0.340710,-0.272719
max,6.474314,0.934535,0.899740,45.864262,0.359720,0.796058,-0.045027

Excel file on RGB_SKIP_RAW_CLEAN_global.xlsx displayng data on sheet "Grayness Index.jpg"

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
Image_0,4.144715,0.299823,0.298177,15.876938,0.124525,0.326118,-0.074589
Image_1,6.398135,0.673609,0.990885,148.121507,0.838263,7.183900,10.183833
Image_2,4.252249,0.558350,0.338542,22.448315,0.176065,0.280077,-0.259842
Image_3,4.627969,0.237565,0.337240,17.877040,0.140212,0.318465,-0.085820
Image_4,5.362847,0.483249,0.401042,19.961825,0.156563,0.453131,-0.185828
...,...,...,...,...,...,...,...
Image_65,1.818280,0.339409,0.127604,2.972965,0.023317,0.194807,-0.004333
Image_66,2.262258,0.196572,0.255208,2.294516,0.017996,0.292958,-0.003618
Image_67,4.354663,0.598834,0.330729,18.366048,0.144047,0.359915,-0.183154
Image_68,5.258691,0.905811,0.381510,21.354047,0.167483,0.518929,-0.288046
Image_69,4.175452,0.510437,0.305990,14.539359,0.114034,0.238108,-0.153965

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000
mean,4.030032,0.318984,0.357310,23.760891,0.155490,0.627379,0.192890
std,1.450537,0.195833,0.213916,37.913475,0.191037,0.994157,1.320121
min,0.858197,0.040162,0.117188,0.534964,0.004196,0.104779,-0.540789
25%,2.621536,0.169377,0.195964,4.289787,0.033645,0.243937,-0.118183
50%,4.303456,0.255879,0.335938,15.247049,0.119585,0.355945,-0.017037
75%,5.249453,0.467733,0.398112,22.420241,0.175845,0.513390,-0.003699
max,6.398135,0.905811,1.000000,215.250419,0.923191,7.183900,10.183833

Excel file on RGB_SKIP_RAW_CLEAN_global.xlsx displayng data on sheet "Unsharp Masking.jpg"

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
Image_0,5.998678,0.397484,0.563802,35.067070,0.275036,0.680419,-0.205390
Image_1,6.592216,0.730690,1.000000,207.184999,0.375020,9.812951,5.951584
Image_2,5.850636,0.687582,0.867188,62.392563,0.489353,0.722915,-0.799103
Image_3,6.268675,0.417315,0.933594,50.713950,0.397756,0.704426,-0.491042
Image_4,6.640276,0.612341,0.981771,52.927509,0.415118,1.100494,0.228936
...,...,...,...,...,...,...,...
Image_65,5.840271,0.748220,0.619792,44.764169,0.351092,0.640000,-0.612234
Image_66,6.355934,0.069811,0.876302,244.562641,0.081862,0.429557,-0.038803
Image_67,5.948658,0.533465,0.777344,54.868910,0.430344,0.901386,-0.159008
Image_68,6.374440,0.825385,0.988281,52.955904,0.415340,1.113426,0.334759
Image_69,5.880035,0.682778,0.815104,38.461496,0.301659,0.503437,-0.977407

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,67.000000,70.000000,70.000000,70.000000,70.000000,70.000000,67.000000
mean,5.944428,0.454368,0.854594,84.044949,0.427991,1.243048,0.072498
std,0.542287,0.227861,0.140723,62.398526,0.159439,1.334780,1.213840
min,4.632074,0.010143,0.423177,31.156768,0.019803,0.282859,-2.152597
25%,5.630164,0.258294,0.793620,48.532254,0.330422,0.714642,-0.383680
50%,5.998678,0.455437,0.901693,59.650954,0.433095,0.850309,-0.161913
75%,6.378107,0.651018,0.956706,79.278472,0.508965,1.169937,0.198351
max,6.787281,0.930711,1.000000,252.475149,0.756455,9.812951,5.951584

----------
Excel file on RGB_SKIP_RAW_NOISY.xlsx displayng data on sheet "Conditional Contrast Correction"

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
Image_0,6.010435,0.443387,0.595052,30.675945,0.240596,3.758403,0.728774
Image_1,NaN,0.527243,0.436198,247.631664,0.057791,0.954947,NaN
Image_2,6.089256,0.753590,0.761719,53.309136,0.418111,2.385653,1.833227
Image_3,6.347239,0.446952,0.869792,49.166581,0.385620,3.195577,1.594832
Image_4,6.493966,0.561830,0.864583,40.991245,0.321500,5.406837,2.469238
...,...,...,...,...,...,...,...
Image_65,5.988132,0.720582,0.703125,66.170156,0.518982,1.931913,1.495879
Image_66,NaN,0.124587,0.449219,242.984362,0.094240,0.191730,NaN
Image_67,5.950865,0.572469,0.722656,55.763870,0.437364,1.954092,1.040657
Image_68,6.560753,0.823535,0.902344,47.605618,0.373377,5.266375,4.363043
Image_69,5.933229,0.663928,0.777344,38.902895,0.305121,2.370378,1.163341

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,61.000000,70.000000,70.000000,70.000000,70.000000,70.000000,61.000000
mean,5.824473,0.458929,0.694494,84.473786,0.417236,2.438103,1.157801
std,0.601955,0.194431,0.173694,65.292517,0.182316,1.504539,1.044658
min,4.442724,0.003906,0.252604,30.675945,0.000688,0.003326,-0.936359
25%,5.420799,0.334719,0.578776,46.539134,0.326470,1.296542,0.436158
50%,5.933229,0.457918,0.714193,63.503578,0.400431,2.244083,1.103519
75%,6.347239,0.584579,0.842122,82.315975,0.550912,3.630624,1.680318
max,6.774994,0.875624,0.970052,254.912249,0.730375,6.446859,4.363043

Excel file on RGB_SKIP_RAW_NOISY.xlsx displayng data on sheet "Contrast Fixing Image.jpg"

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
Image_0,6.328243,0.444641,0.695312,31.812313,0.249508,5.262528,1.169500
Image_1,6.021785,0.713154,0.933594,25.275455,0.198239,4.198818,1.645212
Image_2,6.040468,0.661690,0.945312,63.955930,0.501615,3.401817,3.347629
Image_3,6.500115,0.434461,0.976562,51.542580,0.404256,4.062603,2.254737
Image_4,6.650341,0.579856,0.936198,46.636152,0.365774,6.533575,3.575796
...,...,...,...,...,...,...,...
Image_65,6.329395,0.517164,0.957031,49.183508,0.385753,3.090131,1.966944
Image_66,6.240504,0.468945,0.929688,37.833508,0.296733,2.250344,0.944681
Image_67,6.613615,0.482049,1.000000,53.387347,0.418724,3.752763,2.546985
Image_68,6.523674,0.815325,0.906250,47.937387,0.375980,5.705255,4.553079
Image_69,6.019922,0.608635,0.959635,44.328573,0.347675,3.353475,2.133960

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000
mean,6.289659,0.474665,0.932050,41.098731,0.322343,3.856113,1.745092
std,0.348360,0.181891,0.069510,11.325868,0.088830,1.131891,1.030854
min,5.123040,0.135096,0.674479,22.630042,0.177491,2.193473,0.247211
25%,6.041507,0.322984,0.923177,32.087985,0.251670,3.062704,0.984900
50%,6.320125,0.468600,0.951823,40.652696,0.318845,3.584579,1.485964
75%,6.556482,0.625220,0.972331,49.148303,0.385477,4.353652,2.454533
max,6.880865,0.816658,1.000000,68.690850,0.538752,6.953066,4.566943

Excel file on RGB_SKIP_RAW_NOISY.xlsx displayng data on sheet "Denoised Image.jpg"

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
Image_0,5.574826,0.411752,0.415365,18.568122,0.145632,2.902062,0.213427
Image_1,5.598394,0.692102,0.709635,18.454071,0.144738,3.043595,0.639051
Image_2,5.916250,0.823401,0.537760,33.911515,0.265973,1.704529,0.536069
Image_3,6.167342,0.414855,0.584635,29.723228,0.233123,2.317458,0.422827
Image_4,5.698193,0.537482,0.468750,21.689243,0.170112,2.975628,0.384202
...,...,...,...,...,...,...,...
Image_65,6.233273,0.653397,0.720052,36.483219,0.286143,2.290330,1.003252
Image_66,6.153688,0.479837,0.846354,33.166117,0.260126,1.945990,0.624403
Image_67,6.216841,0.544430,0.686198,32.266704,0.253072,2.302992,0.707384
Image_68,5.708072,0.876487,0.384115,20.120260,0.157806,2.366302,0.376845
Image_69,5.770091,0.693669,0.610677,26.083752,0.204578,1.900599,0.463266

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000
mean,5.875837,0.480301,0.638635,26.234337,0.205760,2.382296,0.455122
std,0.314626,0.205112,0.141933,6.858062,0.053789,0.394294,0.272076
min,5.206999,0.138548,0.350260,15.471662,0.121346,1.646286,0.040802
25%,5.655373,0.320060,0.535807,21.421076,0.168008,2.119768,0.266787
50%,5.878200,0.478733,0.678385,25.019898,0.196234,2.315977,0.377944
75%,6.118377,0.649929,0.736654,29.914485,0.234623,2.531407,0.582762
max,6.481312,0.876487,0.930990,44.860648,0.351848,3.640103,1.580363

Excel file on RGB_SKIP_RAW_NOISY.xlsx displayng data on sheet "Global Mean Contrast (Sat. Fix "

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
Image_0,5.248894,0.408920,0.316406,16.454197,0.129053,2.196261,0.099479
Image_1,4.028264,0.514769,0.287760,6.894560,0.054075,1.032052,0.001469
Image_2,5.908478,0.848005,0.466146,35.283953,0.276737,1.555136,0.411747
Image_3,5.680153,0.408495,0.398438,23.891670,0.187386,1.621443,0.120795
Image_4,5.782389,0.547479,0.477865,27.358661,0.214578,3.178759,0.541603
...,...,...,...,...,...,...,...
Image_65,4.959296,0.864771,0.244792,12.781689,0.100249,0.770177,-0.039649
Image_66,3.425514,0.273479,0.180990,7.173275,0.056261,0.398391,-0.012666
Image_67,5.374987,0.596656,0.412760,20.236355,0.158717,1.313920,0.082753
Image_68,6.110522,0.877474,0.473958,29.682890,0.232807,2.980074,0.932020
Image_69,5.507143,0.725133,0.408854,21.482776,0.168492,1.390856,0.130941

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000
mean,4.853743,0.449939,0.335770,16.154866,0.126705,1.357319,0.118303
std,0.904872,0.218383,0.105837,9.455719,0.074163,0.844935,0.219585
min,2.748138,0.101773,0.125000,2.877370,0.022568,0.308022,-0.046369
25%,4.143829,0.261192,0.264648,7.785717,0.061064,0.678620,-0.008219
50%,4.895740,0.445288,0.324870,14.016383,0.109932,1.122291,0.008206
75%,5.659612,0.586749,0.419922,22.616018,0.177381,1.829149,0.133768
max,6.444548,0.924137,0.548177,40.869819,0.320548,3.247049,1.009197

Excel file on RGB_SKIP_RAW_NOISY.xlsx displayng data on sheet "Grayness Index.jpg"

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
Image_0,5.466723,0.436969,0.516927,20.208484,0.158498,4.444156,0.421167
Image_1,6.550858,0.493946,1.000000,165.048313,0.705503,24.387768,10.519555
Image_2,5.306899,0.650573,0.563802,30.229915,0.237097,2.591108,0.633929
Image_3,6.000628,0.446568,0.622396,30.591840,0.239936,4.062676,0.809320
Image_4,6.665578,0.536378,1.000000,47.265710,0.370711,11.349478,4.644915
...,...,...,...,...,...,...,...
Image_65,5.228840,0.598549,0.367188,21.334044,0.167326,1.326699,0.078424
Image_66,6.514659,0.411870,0.997396,154.657742,0.786998,7.521536,6.131106
Image_67,5.416496,0.589448,0.494792,28.301538,0.221973,1.864033,0.315043
Image_68,6.511892,0.701906,1.000000,65.635526,0.514788,13.150372,8.746035
Image_69,5.120963,0.531728,0.458333,19.606269,0.153775,2.274901,0.227572

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000
mean,4.859151,0.419120,0.538225,33.520481,0.237590,4.290202,1.704461
std,1.624032,0.155657,0.301524,39.206011,0.236737,4.888332,2.818496
min,0.159655,0.003906,0.110677,0.099753,0.000782,0.038017,-0.051442
25%,3.401935,0.314021,0.249674,5.009741,0.039292,0.640863,-0.002636
50%,5.441609,0.414001,0.503906,24.574164,0.192739,2.525248,0.334764
75%,6.160041,0.507202,0.838542,39.922139,0.313115,6.201971,1.970781
max,6.844523,0.761146,1.000000,165.048313,0.990605,24.387768,10.519555

Excel file on RGB_SKIP_RAW_NOISY.xlsx displayng data on sheet "Histogram Stretched.jpg"

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
Image_0,6.010435,0.443387,0.595052,30.675945,0.240596,3.758403,0.728774
Image_1,3.749938,0.544211,0.662760,126.118525,0.989165,1.668320,0.987885
Image_2,6.089256,0.753590,0.761719,53.309136,0.418111,2.385653,1.833227
Image_3,6.347239,0.446952,0.869792,49.166581,0.385620,3.195577,1.594832
Image_4,6.493966,0.561830,0.864583,40.991245,0.321500,5.406837,2.469238
...,...,...,...,...,...,...,...
Image_65,5.988132,0.720582,0.703125,66.170156,0.518982,1.931913,1.495879
Image_66,2.803974,0.390138,0.502604,131.047435,0.972177,0.541484,-0.473055
Image_67,5.950865,0.572469,0.722656,55.763870,0.437364,1.954092,1.040657
Image_68,6.560753,0.823535,0.902344,47.605618,0.373377,5.266375,4.363043
Image_69,5.933229,0.663928,0.777344,38.902895,0.305121,2.370378,1.163341

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,67.000000,70.000000,70.000000,70.000000,70.000000,70.000000,67.000000
mean,5.673627,0.479680,0.712035,69.068541,0.522542,2.416106,1.061765
std,0.803734,0.164741,0.146842,30.460853,0.197174,1.467709,1.045756
min,2.803974,0.226172,0.415365,30.675945,0.240596,0.452334,-0.936359
25%,5.227035,0.339356,0.592773,46.539134,0.365013,1.296542,0.388598
50%,5.878648,0.466656,0.707682,63.503578,0.498067,2.047420,0.824486
75%,6.322428,0.584579,0.842122,82.315975,0.645615,3.630624,1.612793
max,6.774994,0.875624,0.970052,163.098670,0.989165,6.446859,4.363043

Excel file on RGB_SKIP_RAW_NOISY.xlsx displayng data on sheet "Noisy Synthetic Image (Without "

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
Image_0,5.680479,0.433319,0.520833,19.541341,0.153265,4.575622,0.431088
Image_1,5.685209,0.650413,0.766927,19.438568,0.152459,4.508577,0.939372
Image_2,6.039642,0.792576,0.699219,34.752187,0.272566,4.732058,2.045800
Image_3,6.251022,0.430661,0.696615,30.662996,0.240494,4.961817,1.042218
Image_4,5.836234,0.520303,0.539062,22.707969,0.178102,4.930977,0.671085
...,...,...,...,...,...,...,...
Image_65,6.270007,0.643864,0.852865,37.361373,0.293030,4.935098,2.323613
Image_66,6.217404,0.472230,0.865885,34.003492,0.266694,4.575140,1.487431
Image_67,6.297018,0.571972,0.753906,33.280736,0.261025,5.224857,1.690710
Image_68,5.798447,0.801232,0.518229,21.000819,0.164712,4.246849,0.827397
Image_69,5.881342,0.679980,0.783854,27.046216,0.212127,4.289286,1.396935

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000
mean,5.963308,0.487940,0.730897,27.178644,0.213166,4.631152,1.029245
std,0.294609,0.172957,0.126551,6.838661,0.053637,0.458906,0.579655
min,5.314451,0.192741,0.454427,16.447220,0.128998,3.658342,0.145146
25%,5.797840,0.354228,0.639974,22.373928,0.175482,4.253037,0.658544
50%,5.954852,0.479837,0.754557,25.945292,0.203492,4.674191,0.858417
75%,6.182686,0.641834,0.826172,30.912613,0.242452,4.954391,1.260043
max,6.537718,0.822070,0.959635,45.767656,0.358962,5.800416,2.814745

Excel file on RGB_SKIP_RAW_NOISY.xlsx displayng data on sheet "S-Curve Correction.jpg"

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
Image_0,5.804004,0.426877,0.505208,23.935243,0.187727,3.259802,0.400588
Image_1,4.414496,0.543306,0.463542,9.344641,0.073291,1.550755,0.051576
Image_2,6.089928,0.748446,0.777344,56.117456,0.440137,2.423814,1.991862
Image_3,6.207065,0.433149,0.662760,36.085570,0.283024,2.482836,0.661657
Image_4,6.426443,0.562705,0.808594,41.135388,0.322630,5.043657,2.202294
...,...,...,...,...,...,...,...
Image_65,5.472784,0.815651,0.389323,18.331653,0.143778,1.169115,0.056325
Image_66,3.810841,0.306491,0.277344,10.195895,0.079968,0.520759,-0.024384
Image_67,5.950989,0.568043,0.690104,29.981730,0.235151,2.073170,0.577007
Image_68,6.543440,0.838571,0.805990,45.836944,0.359505,4.639156,3.519911
Image_69,5.836442,0.676744,0.682292,32.617135,0.255821,2.091869,0.734080

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000
mean,5.305226,0.461062,0.550502,24.000929,0.188243,2.087273,0.572274
std,0.941375,0.191633,0.190417,15.119590,0.118585,1.357615,0.871631
min,3.003569,0.121975,0.175781,3.690035,0.028941,0.397536,-0.053764
25%,4.570888,0.288971,0.417643,10.780719,0.084555,1.005821,0.000447
50%,5.390809,0.463766,0.533854,20.311546,0.159306,1.713333,0.127257
75%,6.106102,0.577962,0.694987,34.005236,0.266708,2.822836,0.774492
max,6.689585,0.899535,0.954427,64.777754,0.508061,5.200409,3.788088

Excel file on RGB_SKIP_RAW_NOISY.xlsx displayng data on sheet "Saturation Fixing.jpg"

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
Image_0,5.396067,0.405537,0.373698,16.631595,0.130444,2.641750,0.149501
Image_1,4.186195,0.535195,0.352865,7.225901,0.056674,1.289649,0.016442
Image_2,5.915624,0.811866,0.540365,35.474563,0.278232,1.846110,0.638662
Image_3,5.863542,0.412546,0.473958,23.986120,0.188126,1.973244,0.211495
Image_4,6.015334,0.552783,0.569010,27.363601,0.214616,3.882810,0.794715
...,...,...,...,...,...,...,...
Image_65,5.051773,0.844400,0.294271,13.112448,0.102843,0.939684,-0.011587
Image_66,3.661865,0.282902,0.223958,7.661403,0.060089,0.453993,-0.015883
Image_67,5.550768,0.586172,0.492188,20.519972,0.160941,1.617943,0.178910
Image_68,6.243239,0.862656,0.562500,29.834862,0.233999,3.597741,1.309400
Image_69,5.557418,0.707442,0.483073,21.615920,0.169537,1.657748,0.234802

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000
mean,4.995422,0.451333,0.401674,16.438176,0.128927,1.656008,0.189435
std,0.892857,0.210254,0.123278,9.352466,0.073353,1.024029,0.312244
min,2.927720,0.127893,0.151042,3.159466,0.024780,0.375711,-0.044816
25%,4.289511,0.258961,0.318034,8.201882,0.064328,0.838891,-0.005366
50%,5.013096,0.448453,0.391276,14.373835,0.112736,1.382973,0.033781
75%,5.807994,0.583271,0.501953,22.865501,0.179337,2.210017,0.234395
max,6.630373,0.909279,0.651042,40.945491,0.321141,3.968767,1.411068

Excel file on RGB_SKIP_RAW_NOISY.xlsx displayng data on sheet "Unsharp Masking.jpg"

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
Image_0,6.169809,0.457030,0.769531,30.958302,0.242810,6.930743,1.471575
Image_1,6.563815,0.480255,1.000000,188.811475,0.519126,26.275691,7.716904
Image_2,6.276521,0.746258,0.885417,53.515606,0.419730,4.430796,3.738284
Image_3,6.516737,0.468303,0.936198,49.320870,0.386830,5.991106,2.854565
Image_4,6.534957,0.534576,0.993490,41.677780,0.326885,9.747200,3.726867
...,...,...,...,...,...,...,...
Image_65,6.227219,0.708559,0.766927,66.165443,0.518945,3.725342,3.331948
Image_66,6.612155,0.293694,0.960938,228.382264,0.208767,2.770340,0.572704
Image_67,6.138337,0.587613,0.846354,55.763266,0.437359,3.731288,2.536363
Image_68,6.513604,0.745047,1.000000,48.556609,0.380836,9.408845,5.977028
Image_69,6.161270,0.641160,0.817708,39.010406,0.305964,4.477784,2.137563

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,67.000000,70.000000,70.000000,70.000000,70.000000,70.000000,67.000000
mean,6.073278,0.471852,0.841239,82.139609,0.437974,5.629594,2.611153
std,0.522313,0.163596,0.153569,59.641336,0.163607,4.499969,1.671168
min,4.648845,0.003906,0.417969,30.958302,0.003796,0.059913,0.044302
25%,5.686483,0.374722,0.762044,46.829538,0.343306,2.658791,1.410910
50%,6.188899,0.462667,0.873047,63.618218,0.406968,4.454290,2.467099
75%,6.513865,0.590316,0.966797,82.315271,0.552998,7.182622,3.274937
max,6.767471,0.865198,1.000000,254.516006,0.730389,26.275691,7.716904

----------
Excel file on RGB_SKIP_RAW_NOISY_global.xlsx displayng data on sheet "After Contrast Conditional Enha"

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
Image_0,6.010435,0.443387,0.595052,30.675945,0.240596,3.758403,0.728774
Image_1,NaN,0.527243,0.436198,247.631664,0.057791,0.954947,NaN
Image_2,6.089256,0.753590,0.761719,53.309136,0.418111,2.385653,1.833227
Image_3,6.347239,0.446952,0.869792,49.166581,0.385620,3.195577,1.594832
Image_4,6.493966,0.561830,0.864583,40.991245,0.321500,5.406837,2.469238
...,...,...,...,...,...,...,...
Image_65,5.988132,0.720582,0.703125,66.170156,0.518982,1.931913,1.495879
Image_66,NaN,0.124587,0.449219,242.984362,0.094240,0.191730,NaN
Image_67,5.950865,0.572469,0.722656,55.763870,0.437364,1.954092,1.040657
Image_68,6.560753,0.823535,0.902344,47.605618,0.373377,5.266375,4.363043
Image_69,5.933229,0.663928,0.777344,38.902895,0.305121,2.370378,1.163341

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,61.000000,70.000000,70.000000,70.000000,70.000000,70.000000,61.000000
mean,5.824473,0.458929,0.694494,84.473786,0.417236,2.438103,1.157801
std,0.601955,0.194431,0.173694,65.292517,0.182316,1.504539,1.044658
min,4.442724,0.003906,0.252604,30.675945,0.000688,0.003326,-0.936359
25%,5.420799,0.334719,0.578776,46.539134,0.326470,1.296542,0.436158
50%,5.933229,0.457918,0.714193,63.503578,0.400431,2.244083,1.103519
75%,6.347239,0.584579,0.842122,82.315975,0.550912,3.630624,1.680318
max,6.774994,0.875624,0.970052,254.912249,0.730375,6.446859,4.363043

Excel file on RGB_SKIP_RAW_NOISY_global.xlsx displayng data on sheet "Denoised Image.jpg"

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
Image_0,5.574826,0.411752,0.415365,18.568122,0.145632,2.902062,0.213427
Image_1,5.598394,0.692102,0.709635,18.454071,0.144738,3.043595,0.639051
Image_2,5.916250,0.823401,0.537760,33.911515,0.265973,1.704529,0.536069
Image_3,6.167342,0.414855,0.584635,29.723228,0.233123,2.317458,0.422827
Image_4,5.698193,0.537482,0.468750,21.689243,0.170112,2.975628,0.384202
...,...,...,...,...,...,...,...
Image_65,6.233273,0.653397,0.720052,36.483219,0.286143,2.290330,1.003252
Image_66,6.153688,0.479837,0.846354,33.166117,0.260126,1.945990,0.624403
Image_67,6.216841,0.544430,0.686198,32.266704,0.253072,2.302992,0.707384
Image_68,5.708072,0.876487,0.384115,20.120260,0.157806,2.366302,0.376845
Image_69,5.770091,0.693669,0.610677,26.083752,0.204578,1.900599,0.463266

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000
mean,5.875837,0.480301,0.638635,26.234337,0.205760,2.382296,0.455122
std,0.314626,0.205112,0.141933,6.858062,0.053789,0.394294,0.272076
min,5.206999,0.138548,0.350260,15.471662,0.121346,1.646286,0.040802
25%,5.655373,0.320060,0.535807,21.421076,0.168008,2.119768,0.266787
50%,5.878200,0.478733,0.678385,25.019898,0.196234,2.315977,0.377944
75%,6.118377,0.649929,0.736654,29.914485,0.234623,2.531407,0.582762
max,6.481312,0.876487,0.930990,44.860648,0.351848,3.640103,1.580363

Excel file on RGB_SKIP_RAW_NOISY_global.xlsx displayng data on sheet "Grayness Index.jpg"

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
Image_0,5.466723,0.436969,0.516927,20.208484,0.158498,4.444156,0.421167
Image_1,6.550858,0.493946,1.000000,165.048313,0.705503,24.387768,10.519555
Image_2,5.306899,0.650573,0.563802,30.229915,0.237097,2.591108,0.633929
Image_3,6.000628,0.446568,0.622396,30.591840,0.239936,4.062676,0.809320
Image_4,6.665578,0.536378,1.000000,47.265710,0.370711,11.349478,4.644915
...,...,...,...,...,...,...,...
Image_65,5.228840,0.598549,0.367188,21.334044,0.167326,1.326699,0.078424
Image_66,6.514659,0.411870,0.997396,154.657742,0.786998,7.521536,6.131106
Image_67,5.416496,0.589448,0.494792,28.301538,0.221973,1.864033,0.315043
Image_68,6.511892,0.701906,1.000000,65.635526,0.514788,13.150372,8.746035
Image_69,5.120963,0.531728,0.458333,19.606269,0.153775,2.274901,0.227572

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000
mean,4.859151,0.419120,0.538225,33.520481,0.237590,4.290202,1.704461
std,1.624032,0.155657,0.301524,39.206011,0.236737,4.888332,2.818496
min,0.159655,0.003906,0.110677,0.099753,0.000782,0.038017,-0.051442
25%,3.401935,0.314021,0.249674,5.009741,0.039292,0.640863,-0.002636
50%,5.441609,0.414001,0.503906,24.574164,0.192739,2.525248,0.334764
75%,6.160041,0.507202,0.838542,39.922139,0.313115,6.201971,1.970781
max,6.844523,0.761146,1.000000,165.048313,0.990605,24.387768,10.519555

Excel file on RGB_SKIP_RAW_NOISY_global.xlsx displayng data on sheet "Unsharp Masking.jpg"

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
Image_0,6.169809,0.457030,0.769531,30.958302,0.242810,6.930743,1.471575
Image_1,6.563815,0.480255,1.000000,188.811475,0.519126,26.275691,7.716904
Image_2,6.276521,0.746258,0.885417,53.515606,0.419730,4.430796,3.738284
Image_3,6.516737,0.468303,0.936198,49.320870,0.386830,5.991106,2.854565
Image_4,6.534957,0.534576,0.993490,41.677780,0.326885,9.747200,3.726867
...,...,...,...,...,...,...,...
Image_65,6.227219,0.708559,0.766927,66.165443,0.518945,3.725342,3.331948
Image_66,6.612155,0.293694,0.960938,228.382264,0.208767,2.770340,0.572704
Image_67,6.138337,0.587613,0.846354,55.763266,0.437359,3.731288,2.536363
Image_68,6.513604,0.745047,1.000000,48.556609,0.380836,9.408845,5.977028
Image_69,6.161270,0.641160,0.817708,39.010406,0.305964,4.477784,2.137563

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,67.000000,70.000000,70.000000,70.000000,70.000000,70.000000,67.000000
mean,6.073278,0.471852,0.841239,82.139609,0.437974,5.629594,2.611153
std,0.522313,0.163596,0.153569,59.641336,0.163607,4.499969,1.671168
min,4.648845,0.003906,0.417969,30.958302,0.003796,0.059913,0.044302
25%,5.686483,0.374722,0.762044,46.829538,0.343306,2.658791,1.410910
50%,6.188899,0.462667,0.873047,63.618218,0.406968,4.454290,2.467099
75%,6.513865,0.590316,0.966797,82.315271,0.552998,7.182622,3.274937
max,6.767471,0.865198,1.000000,254.516006,0.730389,26.275691,7.716904

----------
Excel file on RGB_WITH_RAW_CLEAN.xlsx displayng data on sheet "Clean Synthetic Image (Raw Proc"

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
Image_0,0.000000e+00,0.003904,0.003906,0.021757,0.000171,0.000936,0.000000e+00
Image_1,0.000000e+00,0.003858,0.003906,0.024435,0.000192,0.002220,0.000000e+00
Image_2,0.000000e+00,0.003658,0.003906,0.047007,0.000369,0.001181,0.000000e+00
Image_3,0.000000e+00,0.003902,0.003906,0.041460,0.000325,0.001269,0.000000e+00
Image_4,0.000000e+00,0.003887,0.003906,0.024909,0.000195,0.001429,0.000000e+00
...,...,...,...,...,...,...,...
Image_65,0.000000e+00,0.003253,0.003906,0.053932,0.000423,0.001497,0.000000e+00
Image_66,6.829791e-07,0.003904,0.005208,0.043414,0.000341,0.001512,-4.430340e-14
Image_67,0.000000e+00,0.003727,0.003906,0.041853,0.000328,0.002094,0.000000e+00
Image_68,0.000000e+00,0.003829,0.003906,0.023815,0.000187,0.001116,0.000000e+00
Image_69,0.000000e+00,0.003680,0.003906,0.036719,0.000288,0.000950,0.000000e+00

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,7.000000e+01
mean,0.000002,0.003838,0.003981,0.034536,0.000271,0.001506,-6.619220e-14
std,0.000016,0.000179,0.000304,0.011770,0.000092,0.000425,5.154527e-13
min,0.000000,0.003068,0.003906,0.018706,0.000147,0.000783,-4.310090e-12
25%,0.000000,0.003783,0.003906,0.025156,0.000197,0.001217,0.000000e+00
50%,0.000000,0.003895,0.003906,0.032574,0.000255,0.001444,0.000000e+00
75%,0.000000,0.003925,0.003906,0.040460,0.000317,0.001798,0.000000e+00
max,0.000132,0.004045,0.005208,0.070239,0.000551,0.002711,0.000000e+00

Excel file on RGB_WITH_RAW_CLEAN.xlsx displayng data on sheet "Conditional Contrast Correction"

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
Image_0,5.218611,0.260466,0.565104,21.947609,0.172138,0.290085,-0.236080
Image_1,4.941460,0.666020,0.958333,12.698508,0.099596,0.613524,-0.221398
Image_2,4.778370,0.753765,0.994792,49.739685,0.390115,0.355007,-2.088403
Image_3,5.734833,0.267266,0.986979,32.388794,0.254030,0.360923,-0.564994
Image_4,6.022742,0.552694,0.971354,32.713409,0.256576,0.745870,-0.350927
...,...,...,...,...,...,...,...
Image_65,5.288039,0.647120,0.859375,28.858835,0.226344,0.274007,-1.243202
Image_66,5.160264,0.328661,0.895833,20.506460,0.160835,0.248604,-0.490691
Image_67,5.937198,0.465745,0.924479,29.847519,0.234098,0.635981,-0.390751
Image_68,5.148084,0.880331,1.000000,35.336710,0.277151,0.593480,-0.945464
Image_69,4.855460,0.623902,0.985677,26.931101,0.211224,0.240418,-1.296967

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000
mean,5.238151,0.390470,0.905227,26.042519,0.204255,0.471431,-0.436248
std,0.576016,0.238730,0.105531,10.351184,0.081186,0.227521,0.429747
min,4.020883,0.045203,0.501302,9.295043,0.072902,0.225412,-2.088403
25%,4.859640,0.182656,0.874674,17.894810,0.140351,0.315543,-0.616001
50%,5.193364,0.392875,0.939453,25.946490,0.203502,0.410652,-0.309956
75%,5.643287,0.586739,0.972656,32.835968,0.257537,0.565821,-0.141489
max,6.435975,0.880331,1.000000,59.411589,0.465973,1.431338,0.197600

Excel file on RGB_WITH_RAW_CLEAN.xlsx displayng data on sheet "Contrast Fixing Image.jpg"

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
Image_0,5.125237,0.266748,0.579427,23.525229,0.184512,0.263456,-0.281271
Image_1,5.110245,0.702357,0.972656,13.707084,0.107507,0.612303,-0.265602
Image_2,4.610003,0.729536,1.000000,51.603270,0.404732,0.317525,-2.252827
Image_3,5.610080,0.274719,0.993490,34.560981,0.271067,0.308049,-0.705069
Image_4,6.007522,0.552074,0.983073,35.553279,0.278849,0.732554,-0.408214
...,...,...,...,...,...,...,...
Image_65,5.246413,0.577358,0.975260,32.923397,0.258223,0.246960,-1.539108
Image_66,5.147726,0.349104,0.979167,21.694398,0.170152,0.208891,-0.676416
Image_67,6.091033,0.462755,0.962240,33.292470,0.261117,0.640363,-0.455405
Image_68,4.873031,0.869145,1.000000,37.201069,0.291773,0.564435,-1.019657
Image_69,4.717593,0.623024,0.998698,29.029199,0.227680,0.212015,-1.495543

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000
mean,5.241983,0.380154,0.943899,27.796853,0.218015,0.446881,-0.508802
std,0.621194,0.246252,0.097125,10.702309,0.083940,0.240037,0.504578
min,3.642613,0.021782,0.524740,11.805894,0.092595,0.177279,-2.252827
25%,4.876475,0.160846,0.955078,19.320520,0.151533,0.275586,-0.737083
50%,5.182475,0.381069,0.979818,26.913960,0.211090,0.382159,-0.323509
75%,5.707307,0.573522,0.993490,35.512279,0.278528,0.533239,-0.143278
max,6.519702,0.879083,1.000000,61.507574,0.482412,1.429656,0.200104

Excel file on RGB_WITH_RAW_CLEAN.xlsx displayng data on sheet "Denoised Image.jpg"

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
Image_0,3.691855,0.126592,0.144531,5.113333,0.040105,0.052907,-0.011487
Image_1,3.994562,0.612103,0.432292,5.644616,0.044272,0.234138,-0.098014
Image_2,4.173860,0.942590,0.231771,11.707706,0.091825,0.071467,-0.318725
Image_3,4.410915,0.135750,0.290365,9.995507,0.078396,0.074243,-0.051136
Image_4,3.937894,0.355569,0.179688,5.912899,0.046376,0.097795,-0.039136
...,...,...,...,...,...,...,...
Image_65,4.750271,0.837697,0.386719,13.221179,0.103696,0.102689,-0.523984
Image_66,4.532195,0.300176,0.506510,10.622525,0.083314,0.096819,-0.193391
Image_67,4.687426,0.536305,0.342448,10.120555,0.079377,0.187052,-0.165264
Image_68,3.609504,0.925136,0.148438,5.638042,0.044220,0.069800,-0.084182
Image_69,4.100132,0.706652,0.320312,8.986645,0.070483,0.063125,-0.260713

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000
mean,4.145109,0.335205,0.335491,8.312800,0.065198,0.126883,-0.101677
std,0.434668,0.293428,0.120409,2.994017,0.023482,0.068012,0.127544
min,3.254702,0.011513,0.127604,4.294779,0.033685,0.041250,-0.658421
25%,3.841664,0.073710,0.235352,5.952831,0.046689,0.083024,-0.108535
50%,4.140641,0.233906,0.349609,7.711778,0.060485,0.104490,-0.064614
75%,4.433350,0.541394,0.414388,9.776067,0.076675,0.160748,-0.013444
max,5.277144,0.942590,0.601562,17.455028,0.136902,0.363117,-0.000959

Excel file on RGB_WITH_RAW_CLEAN.xlsx displayng data on sheet "Global Mean Contrast (Sat. Fix "

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
Image_0,4.988940,0.250096,0.416667,20.400827,0.160006,0.214468,-0.184766
Image_1,4.494967,0.631601,0.550781,9.610909,0.075380,0.414362,-0.149817
Image_2,5.287594,0.827463,0.664062,41.952368,0.329038,0.248837,-1.918448
Image_3,5.508912,0.272029,0.615885,26.578066,0.208455,0.242400,-0.393359
Image_4,5.840127,0.557888,0.727865,32.884941,0.257921,0.597209,-0.454883
...,...,...,...,...,...,...,...
Image_65,5.218423,0.794434,0.501302,20.589168,0.161484,0.177485,-0.837070
Image_66,4.651190,0.306832,0.464844,12.307300,0.096528,0.144274,-0.178860
Image_67,5.674828,0.516049,0.595052,24.848303,0.194889,0.437227,-0.405344
Image_68,5.221197,0.900880,0.747396,34.138268,0.267751,0.466876,-1.034361
Image_69,4.719337,0.692143,0.606771,21.385547,0.167730,0.160551,-0.877273

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000
mean,4.992307,0.393901,0.576358,21.165878,0.166007,0.325525,-0.341238
std,0.567701,0.265163,0.109729,10.446777,0.081936,0.171854,0.388170
min,3.690765,0.018446,0.305990,8.118433,0.063674,0.119448,-1.918448
25%,4.586595,0.149012,0.513346,11.803041,0.092573,0.201742,-0.474200
50%,4.968177,0.385361,0.582682,19.986807,0.156759,0.289423,-0.185344
75%,5.468656,0.616792,0.662109,28.278702,0.221794,0.374375,-0.100481
max,6.119422,0.900880,0.783854,55.257633,0.433393,1.034935,0.012852

Excel file on RGB_WITH_RAW_CLEAN.xlsx displayng data on sheet "Grayness Index.jpg"

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
Image_0,5.101288,0.306483,0.563802,20.394151,0.159954,0.579893,-0.110843
Image_1,4.282883,0.575365,0.643229,7.547137,0.059193,0.767288,-0.035856
Image_2,4.768495,0.499947,1.000000,55.131563,0.432404,1.845285,0.911111
Image_3,5.282712,0.245453,0.606771,19.852917,0.155709,0.458086,-0.137982
Image_4,6.395009,0.560940,1.000000,39.865847,0.312673,1.904364,1.042338
...,...,...,...,...,...,...,...
Image_65,4.595645,0.808490,0.436198,14.449693,0.113331,0.315030,-0.306085
Image_66,4.097871,0.256628,0.451823,8.836192,0.069303,0.258683,-0.064237
Image_67,5.512305,0.519257,0.622396,18.391535,0.144247,0.817967,-0.074493
Image_68,5.083067,0.598329,1.000000,58.334801,0.457528,4.494939,3.017194
Image_69,4.933471,0.541827,1.000000,41.315114,0.324040,1.824024,0.751093

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000
mean,4.700005,0.362326,0.666871,21.750521,0.170592,1.099453,0.274023
std,0.732692,0.228814,0.215158,18.027319,0.141391,1.232035,0.837973
min,3.422235,0.029855,0.312500,5.164090,0.040503,0.250035,-0.615749
25%,4.109458,0.154336,0.517253,8.805350,0.069062,0.405401,-0.079540
50%,4.576129,0.359913,0.600260,15.433959,0.121051,0.557397,-0.028727
75%,5.218554,0.556162,0.900391,26.942385,0.211313,1.361825,0.031242
max,6.396697,0.855377,1.000000,72.835866,0.571262,5.334745,3.468571

Excel file on RGB_WITH_RAW_CLEAN.xlsx displayng data on sheet "Histogram Stretched.jpg"

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
Image_0,5.218611,0.260466,0.565104,21.947609,0.172138,0.290085,-0.236080
Image_1,4.941460,0.666020,0.958333,12.698508,0.099596,0.613524,-0.221398
Image_2,4.778370,0.753765,0.994792,49.739685,0.390115,0.355007,-2.088403
Image_3,5.734833,0.267266,0.986979,32.388794,0.254030,0.360923,-0.564994
Image_4,6.022742,0.552694,0.971354,32.713409,0.256576,0.745870,-0.350927
...,...,...,...,...,...,...,...
Image_65,5.288039,0.647120,0.859375,28.858835,0.226344,0.274007,-1.243202
Image_66,5.160264,0.328661,0.895833,20.506460,0.160835,0.248604,-0.490691
Image_67,5.937198,0.465745,0.924479,29.847519,0.234098,0.635981,-0.390751
Image_68,5.148084,0.880331,1.000000,35.336710,0.277151,0.593480,-0.945464
Image_69,4.855460,0.623902,0.985677,26.931101,0.211224,0.240418,-1.296967

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000
mean,5.238151,0.390470,0.905227,26.042519,0.204255,0.471431,-0.436248
std,0.576016,0.238730,0.105531,10.351184,0.081186,0.227521,0.429747
min,4.020883,0.045203,0.501302,9.295043,0.072902,0.225412,-2.088403
25%,4.859640,0.182656,0.874674,17.894810,0.140351,0.315543,-0.616001
50%,5.193364,0.392875,0.939453,25.946490,0.203502,0.410652,-0.309956
75%,5.643287,0.586739,0.972656,32.835968,0.257537,0.565821,-0.141489
max,6.435975,0.880331,1.000000,59.411589,0.465973,1.431338,0.197600

Excel file on RGB_WITH_RAW_CLEAN.xlsx displayng data on sheet "S-Curve Correction.jpg"

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
Image_0,5.346361,0.309446,0.684896,30.463349,0.238928,0.353902,-0.405709
Image_1,4.957794,0.684992,0.951823,12.994475,0.101917,0.601408,-0.241673
Image_2,4.427027,0.711003,0.986979,68.114205,0.534229,0.425468,-2.046158
Image_3,5.674556,0.288522,1.000000,40.821666,0.320170,0.393747,-0.704861
Image_4,6.296724,0.558760,0.997396,50.397012,0.395271,1.016820,0.033379
...,...,...,...,...,...,...,...
Image_65,5.266757,0.652690,0.855469,31.430492,0.246514,0.268887,-1.373687
Image_66,4.980984,0.335277,0.795573,17.397260,0.136449,0.213841,-0.403437
Image_67,6.040420,0.452268,0.988281,37.591318,0.294834,0.711582,-0.390763
Image_68,5.012258,0.844480,1.000000,53.969970,0.423294,0.799423,-0.578662
Image_69,4.708629,0.627973,0.998698,32.904793,0.258077,0.256545,-1.495806

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000
mean,5.233377,0.395298,0.904074,32.179966,0.252392,0.529215,-0.426098
std,0.639607,0.234783,0.133542,17.248818,0.135285,0.309747,0.489681
min,3.989636,0.047808,0.475260,10.841003,0.085027,0.180034,-2.046158
25%,4.783055,0.180191,0.861003,16.545309,0.129767,0.305787,-0.648641
50%,5.091360,0.384145,0.969401,29.702122,0.232958,0.456911,-0.292063
75%,5.721719,0.581906,0.997396,43.435971,0.340674,0.599223,-0.137139
max,6.509057,0.855308,1.000000,88.340468,0.692866,1.838492,0.619452

Excel file on RGB_WITH_RAW_CLEAN.xlsx displayng data on sheet "Saturation Fixing.jpg"

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
Image_0,5.208557,0.271494,0.496094,20.386498,0.159894,0.268405,-0.212843
Image_1,4.643192,0.650114,0.678385,9.547204,0.074880,0.500904,-0.152938
Image_2,4.994927,0.782065,0.800781,41.944900,0.328980,0.303761,-1.769001
Image_3,5.721985,0.251938,0.742188,26.596549,0.208600,0.298975,-0.388771
Image_4,6.053162,0.553934,0.877604,32.788705,0.257166,0.745282,-0.320970
...,...,...,...,...,...,...,...
Image_65,5.219960,0.743029,0.598958,20.702143,0.162370,0.203406,-0.866647
Image_66,4.603834,0.303816,0.569010,12.441798,0.097583,0.167971,-0.199887
Image_67,5.864419,0.494274,0.725260,24.848882,0.194893,0.555759,-0.347222
Image_68,5.189444,0.874557,0.898438,34.195850,0.268203,0.573891,-0.876142
Image_69,4.697969,0.660879,0.735677,21.505315,0.168669,0.194794,-0.909206

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000
mean,5.056495,0.382371,0.697414,21.197670,0.166256,0.400374,-0.323970
std,0.653046,0.261171,0.133288,10.401752,0.081582,0.221165,0.369068
min,3.443630,0.013488,0.360677,8.250900,0.064713,0.144498,-1.769001
25%,4.590240,0.149795,0.620443,11.776021,0.092361,0.237447,-0.458519
50%,5.131338,0.370494,0.707682,19.952866,0.156493,0.345818,-0.198322
75%,5.635978,0.596608,0.799154,28.258619,0.221636,0.470922,-0.073619
max,6.333220,0.874557,0.945312,55.194648,0.432899,1.340236,0.131975

Excel file on RGB_WITH_RAW_CLEAN.xlsx displayng data on sheet "Unsharp Masking.jpg"

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
Image_0,5.353569,0.264482,0.578125,21.988133,0.172456,0.568646,-0.114968
Image_1,5.009818,0.651579,0.994792,12.739958,0.099921,1.183802,0.078986
Image_2,4.897342,0.753501,1.000000,49.778707,0.390421,0.683603,-0.790618
Image_3,5.790375,0.274449,0.997396,32.455899,0.254556,0.697045,-0.210081
Image_4,6.181960,0.546631,0.998698,32.777022,0.257075,1.482269,0.492623
...,...,...,...,...,...,...,...
Image_65,5.358627,0.646982,0.876302,28.836818,0.226171,0.514039,-0.659676
Image_66,5.216834,0.328122,0.998698,20.480358,0.160630,0.459809,-0.307800
Image_67,5.982780,0.470619,0.971354,29.909084,0.234581,1.223485,0.186694
Image_68,5.291870,0.879361,1.000000,35.427837,0.277865,1.064810,0.117144
Image_69,4.901440,0.619323,0.997396,27.001630,0.211777,0.466856,-0.704639

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000
mean,5.313978,0.394235,0.947061,26.074513,0.204506,0.889601,-0.069387
std,0.577702,0.233432,0.092730,10.357625,0.081236,0.421479,0.272920
min,4.067138,0.048673,0.559896,9.341832,0.073269,0.422189,-0.790618
25%,4.947037,0.191825,0.949219,17.905329,0.140434,0.583222,-0.179373
50%,5.298711,0.395422,0.986328,25.958172,0.203594,0.780403,-0.057341
75%,5.745130,0.582213,0.998698,32.865883,0.257772,1.069567,0.032543
max,6.466230,0.879361,1.000000,59.455297,0.466316,2.637867,0.626054

----------
Excel file on RGB_WITH_RAW_CLEAN_global.xlsx displayng data on sheet "After Contrast Conditional Enha"

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
Image_0,5.218611,0.260466,0.565104,21.947609,0.172138,0.290085,-0.236080
Image_1,4.941460,0.666020,0.958333,12.698508,0.099596,0.613524,-0.221398
Image_2,4.778370,0.753765,0.994792,49.739685,0.390115,0.355007,-2.088403
Image_3,5.734833,0.267266,0.986979,32.388794,0.254030,0.360923,-0.564994
Image_4,6.022742,0.552694,0.971354,32.713409,0.256576,0.745870,-0.350927
...,...,...,...,...,...,...,...
Image_65,5.288039,0.647120,0.859375,28.858835,0.226344,0.274007,-1.243202
Image_66,5.160264,0.328661,0.895833,20.506460,0.160835,0.248604,-0.490691
Image_67,5.937198,0.465745,0.924479,29.847519,0.234098,0.635981,-0.390751
Image_68,5.148084,0.880331,1.000000,35.336710,0.277151,0.593480,-0.945464
Image_69,4.855460,0.623902,0.985677,26.931101,0.211224,0.240418,-1.296967

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000
mean,5.238151,0.390470,0.905227,26.042519,0.204255,0.471431,-0.436248
std,0.576016,0.238730,0.105531,10.351184,0.081186,0.227521,0.429747
min,4.020883,0.045203,0.501302,9.295043,0.072902,0.225412,-2.088403
25%,4.859640,0.182656,0.874674,17.894810,0.140351,0.315543,-0.616001
50%,5.193364,0.392875,0.939453,25.946490,0.203502,0.410652,-0.309956
75%,5.643287,0.586739,0.972656,32.835968,0.257537,0.565821,-0.141489
max,6.435975,0.880331,1.000000,59.411589,0.465973,1.431338,0.197600

Excel file on RGB_WITH_RAW_CLEAN_global.xlsx displayng data on sheet "Denoised Image.jpg"

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
Image_0,3.691855,0.126592,0.144531,5.113333,0.040105,0.052907,-0.011487
Image_1,3.994562,0.612103,0.432292,5.644616,0.044272,0.234138,-0.098014
Image_2,4.173860,0.942590,0.231771,11.707706,0.091825,0.071467,-0.318725
Image_3,4.410915,0.135750,0.290365,9.995507,0.078396,0.074243,-0.051136
Image_4,3.937894,0.355569,0.179688,5.912899,0.046376,0.097795,-0.039136
...,...,...,...,...,...,...,...
Image_65,4.750271,0.837697,0.386719,13.221179,0.103696,0.102689,-0.523984
Image_66,4.532195,0.300176,0.506510,10.622525,0.083314,0.096819,-0.193391
Image_67,4.687426,0.536305,0.342448,10.120555,0.079377,0.187052,-0.165264
Image_68,3.609504,0.925136,0.148438,5.638042,0.044220,0.069800,-0.084182
Image_69,4.100132,0.706652,0.320312,8.986645,0.070483,0.063125,-0.260713

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000
mean,4.145109,0.335205,0.335491,8.312800,0.065198,0.126883,-0.101677
std,0.434668,0.293428,0.120409,2.994017,0.023482,0.068012,0.127544
min,3.254702,0.011513,0.127604,4.294779,0.033685,0.041250,-0.658421
25%,3.841664,0.073710,0.235352,5.952831,0.046689,0.083024,-0.108535
50%,4.140641,0.233906,0.349609,7.711778,0.060485,0.104490,-0.064614
75%,4.433350,0.541394,0.414388,9.776067,0.076675,0.160748,-0.013444
max,5.277144,0.942590,0.601562,17.455028,0.136902,0.363117,-0.000959

Excel file on RGB_WITH_RAW_CLEAN_global.xlsx displayng data on sheet "Grayness Index.jpg"

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
Image_0,5.101288,0.306483,0.563802,20.394151,0.159954,0.579893,-0.110843
Image_1,4.282883,0.575365,0.643229,7.547137,0.059193,0.767288,-0.035856
Image_2,4.768495,0.499947,1.000000,55.131563,0.432404,1.845285,0.911111
Image_3,5.282712,0.245453,0.606771,19.852917,0.155709,0.458086,-0.137982
Image_4,6.395009,0.560940,1.000000,39.865847,0.312673,1.904364,1.042338
...,...,...,...,...,...,...,...
Image_65,4.595645,0.808490,0.436198,14.449693,0.113331,0.315030,-0.306085
Image_66,4.097871,0.256628,0.451823,8.836192,0.069303,0.258683,-0.064237
Image_67,5.512305,0.519257,0.622396,18.391535,0.144247,0.817967,-0.074493
Image_68,5.083067,0.598329,1.000000,58.334801,0.457528,4.494939,3.017194
Image_69,4.933471,0.541827,1.000000,41.315114,0.324040,1.824024,0.751093

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000
mean,4.700005,0.362326,0.666871,21.750521,0.170592,1.099453,0.274023
std,0.732692,0.228814,0.215158,18.027319,0.141391,1.232035,0.837973
min,3.422235,0.029855,0.312500,5.164090,0.040503,0.250035,-0.615749
25%,4.109458,0.154336,0.517253,8.805350,0.069062,0.405401,-0.079540
50%,4.576129,0.359913,0.600260,15.433959,0.121051,0.557397,-0.028727
75%,5.218554,0.556162,0.900391,26.942385,0.211313,1.361825,0.031242
max,6.396697,0.855377,1.000000,72.835866,0.571262,5.334745,3.468571

Excel file on RGB_WITH_RAW_CLEAN_global.xlsx displayng data on sheet "Unsharp Masking.jpg"

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
Image_0,5.353569,0.264482,0.578125,21.988133,0.172456,0.568646,-0.114968
Image_1,5.009818,0.651579,0.994792,12.739958,0.099921,1.183802,0.078986
Image_2,4.897342,0.753501,1.000000,49.778707,0.390421,0.683603,-0.790618
Image_3,5.790375,0.274449,0.997396,32.455899,0.254556,0.697045,-0.210081
Image_4,6.181960,0.546631,0.998698,32.777022,0.257075,1.482269,0.492623
...,...,...,...,...,...,...,...
Image_65,5.358627,0.646982,0.876302,28.836818,0.226171,0.514039,-0.659676
Image_66,5.216834,0.328122,0.998698,20.480358,0.160630,0.459809,-0.307800
Image_67,5.982780,0.470619,0.971354,29.909084,0.234581,1.223485,0.186694
Image_68,5.291870,0.879361,1.000000,35.427837,0.277865,1.064810,0.117144
Image_69,4.901440,0.619323,0.997396,27.001630,0.211777,0.466856,-0.704639

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000
mean,5.313978,0.394235,0.947061,26.074513,0.204506,0.889601,-0.069387
std,0.577702,0.233432,0.092730,10.357625,0.081236,0.421479,0.272920
min,4.067138,0.048673,0.559896,9.341832,0.073269,0.422189,-0.790618
25%,4.947037,0.191825,0.949219,17.905329,0.140434,0.583222,-0.179373
50%,5.298711,0.395422,0.986328,25.958172,0.203594,0.780403,-0.057341
75%,5.745130,0.582213,0.998698,32.865883,0.257772,1.069567,0.032543
max,6.466230,0.879361,1.000000,59.455297,0.466316,2.637867,0.626054

----------
Excel file on RGB_WITH_RAW_NOISY.xlsx displayng data on sheet "Conditional Contrast Correction"

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
Image_0,5.422553,0.267289,0.533854,19.936646,0.156366,0.832704,-0.031956
Image_1,4.806218,0.641544,0.912760,12.205779,0.095732,0.770341,-0.101421
Image_2,4.577249,0.760331,0.994792,48.446834,0.379975,0.731871,-0.592427
Image_3,5.855888,0.339884,0.986979,32.108063,0.251828,0.803585,-0.156065
Image_4,6.075109,0.525721,0.960938,29.688575,0.232852,1.322741,0.288377
...,...,...,...,...,...,...,...
Image_65,5.345237,0.682152,0.787760,26.556700,0.208288,0.534771,-0.540253
Image_66,5.030484,0.336019,0.871094,18.698970,0.146659,0.410735,-0.277215
Image_67,5.929484,0.481363,0.940104,29.280458,0.229651,0.936503,-0.058322
Image_68,5.422913,0.897641,0.993490,33.540325,0.263061,1.274788,0.445597
Image_69,4.857992,0.641843,0.981771,26.491741,0.207778,0.503676,-0.629335

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000
mean,5.237642,0.391656,0.894736,24.517080,0.192291,0.797966,-0.092232
std,0.614379,0.238557,0.109095,9.864775,0.077371,0.310629,0.224237
min,3.889020,0.041204,0.493490,8.361506,0.065580,0.374755,-0.751468
25%,4.854685,0.180121,0.871419,16.869412,0.132309,0.559113,-0.170060
50%,5.254728,0.365091,0.934896,24.579674,0.192782,0.729260,-0.085489
75%,5.711356,0.561580,0.967448,31.494680,0.247017,0.924324,-0.021524
max,6.429746,0.897641,1.000000,55.487388,0.435195,1.868609,0.684174

Excel file on RGB_WITH_RAW_NOISY.xlsx displayng data on sheet "Contrast Fixing Image.jpg"

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
Image_0,5.327547,0.266920,0.545573,21.318848,0.167207,0.729965,-0.058907
Image_1,4.911485,0.698744,0.941406,12.045004,0.094471,0.726086,-0.140944
Image_2,4.317516,0.735259,0.996094,50.434642,0.395566,0.651539,-0.773099
Image_3,5.783666,0.314798,0.994792,33.477987,0.262572,0.661733,-0.283288
Image_4,6.124955,0.522520,0.975260,32.148074,0.252142,1.294620,0.293178
...,...,...,...,...,...,...,...
Image_65,5.392009,0.581215,0.967448,32.148051,0.252142,0.505638,-0.752101
Image_66,5.057833,0.333626,0.972656,20.132201,0.157900,0.348725,-0.393878
Image_67,6.113978,0.467461,0.981771,32.835597,0.257534,0.945761,-0.058137
Image_68,5.054261,0.887428,0.994792,35.259627,0.276546,1.163882,0.270162
Image_69,4.677838,0.627117,0.998698,27.737356,0.217548,0.427114,-0.782233

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000
mean,5.240816,0.379682,0.935714,25.858490,0.202812,0.733739,-0.152662
std,0.676051,0.245735,0.100263,10.478101,0.082181,0.317803,0.265819
min,3.522570,0.017519,0.497396,9.967174,0.078174,0.312764,-1.012152
25%,4.794755,0.167911,0.937500,17.822490,0.139784,0.489187,-0.240555
50%,5.254891,0.357264,0.972656,24.258705,0.190264,0.664201,-0.115576
75%,5.732086,0.565011,0.990885,33.425391,0.262160,0.889959,-0.026129
max,6.538557,0.890911,1.000000,57.561754,0.451465,1.833400,0.449578

Excel file on RGB_WITH_RAW_NOISY.xlsx displayng data on sheet "Denoised Image.jpg"

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
Image_0,3.749766,0.111291,0.138021,4.658350,0.036536,0.124533,-0.006325
Image_1,3.933518,0.608702,0.414062,5.221097,0.040950,0.292012,-0.072098
Image_2,4.226920,0.944279,0.238281,11.314354,0.088740,0.146950,-0.233497
Image_3,4.457197,0.173582,0.289062,9.503778,0.074539,0.170140,-0.042596
Image_4,3.854969,0.323855,0.182292,5.571932,0.043701,0.178074,-0.024759
...,...,...,...,...,...,...,...
Image_65,4.826391,0.841623,0.395833,12.986208,0.101853,0.190933,-0.391216
Image_66,4.533513,0.295166,0.510417,10.232500,0.080255,0.172960,-0.138763
Image_67,4.666211,0.557646,0.351562,9.855080,0.077295,0.272004,-0.132813
Image_68,3.744405,0.917578,0.145833,5.193621,0.040734,0.138274,-0.058258
Image_69,4.086858,0.721478,0.321615,8.588912,0.067364,0.129714,-0.188233

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000
mean,4.172566,0.350902,0.334914,7.947827,0.062336,0.200660,-0.078557
std,0.427946,0.294390,0.121214,3.006193,0.023578,0.066798,0.096704
min,3.397701,0.010991,0.130208,3.898084,0.030573,0.103746,-0.480418
25%,3.852147,0.093830,0.240560,5.635029,0.044196,0.158133,-0.088399
50%,4.159227,0.258368,0.349609,7.430017,0.058275,0.181496,-0.046839
75%,4.473690,0.590607,0.407227,9.386414,0.073619,0.224314,-0.012151
max,5.309102,0.944279,0.636719,16.999255,0.133327,0.431313,-0.000619

Excel file on RGB_WITH_RAW_NOISY.xlsx displayng data on sheet "Global Mean Contrast (Sat. Fix "

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
Image_0,5.075338,0.253319,0.388021,18.523482,0.145282,0.608986,-0.051859
Image_1,4.326164,0.615491,0.502604,8.135098,0.063805,0.500098,-0.085365
Image_2,4.931812,0.829460,0.670573,40.831649,0.320248,0.489068,-0.906503
Image_3,5.585430,0.295345,0.622396,25.821358,0.202520,0.519657,-0.196365
Image_4,5.820223,0.531366,0.712240,29.523657,0.231558,1.015329,0.011195
...,...,...,...,...,...,...,...
Image_65,5.193697,0.797747,0.496094,20.144944,0.158000,0.381209,-0.451852
Image_66,4.360851,0.286368,0.444010,10.844754,0.085057,0.262846,-0.090916
Image_67,5.679037,0.525329,0.614583,24.647354,0.193313,0.652597,-0.218244
Image_68,5.591549,0.914405,0.744792,32.381400,0.253972,1.024023,0.033123
Image_69,4.604581,0.688373,0.602865,20.385443,0.159886,0.315945,-0.507857

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000
mean,4.919371,0.390096,0.558557,19.439193,0.152464,0.552234,-0.128537
std,0.673380,0.263914,0.115522,10.143596,0.079558,0.262700,0.176370
min,3.343148,0.019518,0.296875,5.869353,0.046034,0.230068,-0.906503
25%,4.371526,0.148893,0.489258,9.908156,0.077711,0.360670,-0.194481
50%,4.928329,0.356103,0.557943,18.368292,0.144065,0.486861,-0.082974
75%,5.416706,0.591655,0.656576,26.733915,0.209678,0.628263,-0.027324
max,6.178645,0.914405,0.777344,51.468346,0.403673,1.387033,0.124032

Excel file on RGB_WITH_RAW_NOISY.xlsx displayng data on sheet "Grayness Index.jpg"

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
Image_0,5.561136,0.277617,0.970052,33.380340,0.261807,2.724776,0.567015
Image_1,4.397015,0.618335,0.748698,7.976098,0.062558,1.142067,0.024405
Image_2,4.957929,0.538870,1.000000,53.435523,0.419102,6.112051,2.924287
Image_3,5.522733,0.304996,0.675781,21.237505,0.166569,1.098711,0.025750
Image_4,6.594997,0.512950,1.000000,46.547462,0.365078,4.242334,2.574849
...,...,...,...,...,...,...,...
Image_65,4.782902,0.802534,0.436198,13.874900,0.108823,0.622735,-0.124502
Image_66,4.166379,0.262531,0.503906,8.593664,0.067401,0.468512,-0.040636
Image_67,5.693813,0.532051,0.733073,20.554336,0.161210,1.437716,0.187519
Image_68,5.192959,0.495540,1.000000,61.551420,0.482756,13.453411,4.658447
Image_69,4.695576,0.638023,0.964844,24.170658,0.189574,1.015827,0.012414

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000
mean,4.847511,0.371792,0.735807,23.138538,0.181479,2.606600,0.617885
std,0.792116,0.215764,0.210422,18.503039,0.145122,3.775947,1.329789
min,3.450869,0.028651,0.328125,4.594978,0.036039,0.402892,-0.124502
25%,4.174420,0.187691,0.544271,8.653008,0.067867,0.715969,-0.013008
50%,4.730242,0.374204,0.736328,16.093022,0.126220,1.078611,0.013701
75%,5.518771,0.519788,0.990560,32.922125,0.258213,2.355650,0.469627
max,6.594997,0.872950,1.000000,81.594405,0.639956,16.516855,7.321373

Excel file on RGB_WITH_RAW_NOISY.xlsx displayng data on sheet "Histogram Stretched.jpg"

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
Image_0,5.422553,0.267289,0.533854,19.936646,0.156366,0.832704,-0.031956
Image_1,4.806218,0.641544,0.912760,12.205779,0.095732,0.770341,-0.101421
Image_2,4.577249,0.760331,0.994792,48.446834,0.379975,0.731871,-0.592427
Image_3,5.855888,0.339884,0.986979,32.108063,0.251828,0.803585,-0.156065
Image_4,6.075109,0.525721,0.960938,29.688575,0.232852,1.322741,0.288377
...,...,...,...,...,...,...,...
Image_65,5.345237,0.682152,0.787760,26.556700,0.208288,0.534771,-0.540253
Image_66,5.030484,0.336019,0.871094,18.698970,0.146659,0.410735,-0.277215
Image_67,5.929484,0.481363,0.940104,29.280458,0.229651,0.936503,-0.058322
Image_68,5.422913,0.897641,0.993490,33.540325,0.263061,1.274788,0.445597
Image_69,4.857992,0.641843,0.981771,26.491741,0.207778,0.503676,-0.629335

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000
mean,5.237642,0.391656,0.894736,24.517080,0.192291,0.797966,-0.092232
std,0.614379,0.238557,0.109095,9.864775,0.077371,0.310629,0.224237
min,3.889020,0.041204,0.493490,8.361506,0.065580,0.374755,-0.751468
25%,4.854685,0.180121,0.871419,16.869412,0.132309,0.559113,-0.170060
50%,5.254728,0.365091,0.934896,24.579674,0.192782,0.729260,-0.085489
75%,5.711356,0.561580,0.967448,31.494680,0.247017,0.924324,-0.021524
max,6.429746,0.897641,1.000000,55.487388,0.435195,1.868609,0.684174

Excel file on RGB_WITH_RAW_NOISY.xlsx displayng data on sheet "Noisy Synthetic Image (Raw Proc"

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
Image_0,0.000000e+00,0.003905,0.003906,0.021504,0.000169,0.004133,0.000000e+00
Image_1,0.000000e+00,0.003864,0.003906,0.024467,0.000192,0.005147,0.000000e+00
Image_2,0.000000e+00,0.003671,0.003906,0.047413,0.000372,0.005418,0.000000e+00
Image_3,0.000000e+00,0.003902,0.003906,0.040697,0.000319,0.005401,0.000000e+00
Image_4,0.000000e+00,0.003889,0.003906,0.025224,0.000198,0.004721,0.000000e+00
...,...,...,...,...,...,...,...
Image_65,6.829791e-07,0.003265,0.005208,0.054425,0.000427,0.005912,-3.669893e-14
Image_66,1.311281e-06,0.003904,0.005208,0.043654,0.000342,0.005441,-6.866358e-14
Image_67,0.000000e+00,0.003735,0.003906,0.042506,0.000333,0.005982,0.000000e+00
Image_68,0.000000e+00,0.003837,0.003906,0.023515,0.000184,0.004212,0.000000e+00
Image_69,0.000000e+00,0.003691,0.003906,0.036806,0.000289,0.004546,0.000000e+00

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,7.000000e+01
mean,0.000001,0.003843,0.004111,0.034645,0.000272,0.005074,-4.988960e-14
std,0.000005,0.000170,0.000477,0.011796,0.000093,0.000748,1.853078e-13
min,0.000000,0.003141,0.003906,0.018808,0.000148,0.003761,-1.001431e-12
25%,0.000000,0.003798,0.003906,0.025529,0.000200,0.004551,0.000000e+00
50%,0.000000,0.003897,0.003906,0.032836,0.000258,0.005046,0.000000e+00
75%,0.000000,0.003923,0.003906,0.040314,0.000316,0.005519,0.000000e+00
max,0.000036,0.004034,0.005208,0.070209,0.000551,0.007026,0.000000e+00

Excel file on RGB_WITH_RAW_NOISY.xlsx displayng data on sheet "S-Curve Correction.jpg"

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
Image_0,5.694190,0.280423,0.641927,27.339847,0.214430,1.026707,0.008358
Image_1,4.748978,0.655970,0.864583,10.929055,0.085718,0.724479,-0.107350
Image_2,4.417055,0.719325,0.993490,66.550462,0.521964,0.908741,-0.227472
Image_3,5.808649,0.343159,1.000000,39.834475,0.312427,0.877289,-0.117624
Image_4,6.388091,0.537377,1.000000,44.936940,0.352447,1.790506,1.016747
...,...,...,...,...,...,...,...
Image_65,5.375157,0.658689,0.854167,30.718791,0.240932,0.572768,-0.585803
Image_66,4.896566,0.303129,0.751302,15.347370,0.120372,0.373849,-0.190539
Image_67,6.052573,0.466241,1.000000,37.341801,0.292877,1.091464,0.104356
Image_68,5.348417,0.863250,1.000000,51.273900,0.402148,1.704423,1.428349
Image_69,4.700000,0.635363,0.998698,31.320965,0.245655,0.533965,-0.663156

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000
mean,5.225833,0.392361,0.885249,29.420641,0.230750,0.896748,0.035501
std,0.700023,0.232826,0.148736,16.731150,0.131225,0.478882,0.424077
min,3.570496,0.029501,0.454427,7.631690,0.059856,0.288933,-0.858848
25%,4.712084,0.194233,0.808268,14.071758,0.110367,0.529592,-0.123844
50%,5.250897,0.370982,0.957682,27.305401,0.214160,0.762460,-0.064995
75%,5.772084,0.572619,1.000000,40.955371,0.321219,1.081428,0.075019
max,6.574813,0.869690,1.000000,83.020342,0.651140,2.416639,1.794022

Excel file on RGB_WITH_RAW_NOISY.xlsx displayng data on sheet "Saturation Fixing.jpg"

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
Image_0,5.232761,0.268882,0.463542,18.373390,0.144105,0.763321,-0.036620
Image_1,4.408055,0.655384,0.618490,8.065392,0.063258,0.576839,-0.089718
Image_2,4.661996,0.786920,0.805990,40.942661,0.321119,0.616552,-0.662475
Image_3,5.785987,0.310787,0.750000,25.855251,0.202786,0.650365,-0.169749
Image_4,6.043487,0.530648,0.855469,29.483557,0.231244,1.294928,0.236553
...,...,...,...,...,...,...,...
Image_65,5.272731,0.746870,0.600260,20.162095,0.158134,0.435508,-0.448278
Image_66,4.458715,0.301502,0.540365,10.985724,0.086163,0.286989,-0.112720
Image_67,5.867974,0.507927,0.742188,24.644741,0.193292,0.839505,-0.107916
Image_68,5.292227,0.891888,0.898438,32.337173,0.253625,1.238167,0.331490
Image_69,4.644470,0.666191,0.726562,20.403101,0.160024,0.409508,-0.463364

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000
mean,4.989350,0.388287,0.675856,19.438726,0.152461,0.677155,-0.079877
std,0.717908,0.258869,0.138989,10.131228,0.079461,0.339936,0.185359
min,3.069346,0.017814,0.346354,5.954086,0.046699,0.256401,-0.697504
25%,4.474219,0.153080,0.580729,10.028607,0.078656,0.414562,-0.121514
50%,5.040851,0.371598,0.673828,18.350192,0.143923,0.592525,-0.064302
75%,5.573818,0.591929,0.792643,26.733963,0.209678,0.782189,-0.013261
max,6.320780,0.891888,0.936198,51.385442,0.403023,1.763233,0.529857

Excel file on RGB_WITH_RAW_NOISY.xlsx displayng data on sheet "Unsharp Masking.jpg"

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
Image_0,5.462298,0.258574,0.559896,20.075352,0.157454,1.652308,0.090209
Image_1,4.922563,0.605464,0.992188,12.196641,0.095660,1.563715,0.182452
Image_2,4.722906,0.759910,1.000000,48.490970,0.380321,1.471624,0.760845
Image_3,5.909518,0.356181,1.000000,32.191554,0.252483,1.625751,0.372596
Image_4,6.140488,0.508290,1.000000,29.768552,0.233479,2.607935,1.007756
...,...,...,...,...,...,...,...
Image_65,5.466934,0.681942,0.811198,26.588236,0.208535,1.126274,0.108195
Image_66,5.151782,0.323378,0.994792,18.649534,0.146271,0.903066,-0.035658
Image_67,5.982434,0.492337,0.998698,29.327534,0.230020,1.933323,0.643515
Image_68,5.478651,0.888221,0.998698,33.770262,0.264865,2.284088,1.533877
Image_69,4.889200,0.628126,1.000000,26.557102,0.208291,1.055339,0.049707

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000
mean,5.316925,0.398507,0.949275,24.568417,0.192693,1.587837,0.304341
std,0.590958,0.225379,0.094324,9.888591,0.077558,0.548298,0.398266
min,4.061705,0.057250,0.555990,8.411821,0.065975,0.800783,-0.049534
25%,4.937789,0.205673,0.952148,16.969668,0.133095,1.128931,0.033184
50%,5.309245,0.367344,0.992188,24.586148,0.192833,1.523309,0.172183
75%,5.777959,0.552423,1.000000,31.580707,0.247692,1.760276,0.402556
max,6.454745,0.888221,1.000000,55.606441,0.436129,3.391121,1.981570

----------
Excel file on RGB_WITH_RAW_NOISY_global.xlsx displayng data on sheet "After Contrast Conditional Enha"

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
Image_0,5.422553,0.267289,0.533854,19.936646,0.156366,0.832704,-0.031956
Image_1,4.806218,0.641544,0.912760,12.205779,0.095732,0.770341,-0.101421
Image_2,4.577249,0.760331,0.994792,48.446834,0.379975,0.731871,-0.592427
Image_3,5.855888,0.339884,0.986979,32.108063,0.251828,0.803585,-0.156065
Image_4,6.075109,0.525721,0.960938,29.688575,0.232852,1.322741,0.288377
...,...,...,...,...,...,...,...
Image_65,5.345237,0.682152,0.787760,26.556700,0.208288,0.534771,-0.540253
Image_66,5.030484,0.336019,0.871094,18.698970,0.146659,0.410735,-0.277215
Image_67,5.929484,0.481363,0.940104,29.280458,0.229651,0.936503,-0.058322
Image_68,5.422913,0.897641,0.993490,33.540325,0.263061,1.274788,0.445597
Image_69,4.857992,0.641843,0.981771,26.491741,0.207778,0.503676,-0.629335

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000
mean,5.237642,0.391656,0.894736,24.517080,0.192291,0.797966,-0.092232
std,0.614379,0.238557,0.109095,9.864775,0.077371,0.310629,0.224237
min,3.889020,0.041204,0.493490,8.361506,0.065580,0.374755,-0.751468
25%,4.854685,0.180121,0.871419,16.869412,0.132309,0.559113,-0.170060
50%,5.254728,0.365091,0.934896,24.579674,0.192782,0.729260,-0.085489
75%,5.711356,0.561580,0.967448,31.494680,0.247017,0.924324,-0.021524
max,6.429746,0.897641,1.000000,55.487388,0.435195,1.868609,0.684174

Excel file on RGB_WITH_RAW_NOISY_global.xlsx displayng data on sheet "Denoised Image.jpg"

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
Image_0,3.749766,0.111291,0.138021,4.658350,0.036536,0.124533,-0.006325
Image_1,3.933518,0.608702,0.414062,5.221097,0.040950,0.292012,-0.072098
Image_2,4.226920,0.944279,0.238281,11.314354,0.088740,0.146950,-0.233497
Image_3,4.457197,0.173582,0.289062,9.503778,0.074539,0.170140,-0.042596
Image_4,3.854969,0.323855,0.182292,5.571932,0.043701,0.178074,-0.024759
...,...,...,...,...,...,...,...
Image_65,4.826391,0.841623,0.395833,12.986208,0.101853,0.190933,-0.391216
Image_66,4.533513,0.295166,0.510417,10.232500,0.080255,0.172960,-0.138763
Image_67,4.666211,0.557646,0.351562,9.855080,0.077295,0.272004,-0.132813
Image_68,3.744405,0.917578,0.145833,5.193621,0.040734,0.138274,-0.058258
Image_69,4.086858,0.721478,0.321615,8.588912,0.067364,0.129714,-0.188233

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000
mean,4.172566,0.350902,0.334914,7.947827,0.062336,0.200660,-0.078557
std,0.427946,0.294390,0.121214,3.006193,0.023578,0.066798,0.096704
min,3.397701,0.010991,0.130208,3.898084,0.030573,0.103746,-0.480418
25%,3.852147,0.093830,0.240560,5.635029,0.044196,0.158133,-0.088399
50%,4.159227,0.258368,0.349609,7.430017,0.058275,0.181496,-0.046839
75%,4.473690,0.590607,0.407227,9.386414,0.073619,0.224314,-0.012151
max,5.309102,0.944279,0.636719,16.999255,0.133327,0.431313,-0.000619

Excel file on RGB_WITH_RAW_NOISY_global.xlsx displayng data on sheet "Grayness Index.jpg"

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
Image_0,5.561136,0.277617,0.970052,33.380340,0.261807,2.724776,0.567015
Image_1,4.397015,0.618335,0.748698,7.976098,0.062558,1.142067,0.024405
Image_2,4.957929,0.538870,1.000000,53.435523,0.419102,6.112051,2.924287
Image_3,5.522733,0.304996,0.675781,21.237505,0.166569,1.098711,0.025750
Image_4,6.594997,0.512950,1.000000,46.547462,0.365078,4.242334,2.574849
...,...,...,...,...,...,...,...
Image_65,4.782902,0.802534,0.436198,13.874900,0.108823,0.622735,-0.124502
Image_66,4.166379,0.262531,0.503906,8.593664,0.067401,0.468512,-0.040636
Image_67,5.693813,0.532051,0.733073,20.554336,0.161210,1.437716,0.187519
Image_68,5.192959,0.495540,1.000000,61.551420,0.482756,13.453411,4.658447
Image_69,4.695576,0.638023,0.964844,24.170658,0.189574,1.015827,0.012414

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000
mean,4.847511,0.371792,0.735807,23.138538,0.181479,2.606600,0.617885
std,0.792116,0.215764,0.210422,18.503039,0.145122,3.775947,1.329789
min,3.450869,0.028651,0.328125,4.594978,0.036039,0.402892,-0.124502
25%,4.174420,0.187691,0.544271,8.653008,0.067867,0.715969,-0.013008
50%,4.730242,0.374204,0.736328,16.093022,0.126220,1.078611,0.013701
75%,5.518771,0.519788,0.990560,32.922125,0.258213,2.355650,0.469627
max,6.594997,0.872950,1.000000,81.594405,0.639956,16.516855,7.321373

Excel file on RGB_WITH_RAW_NOISY_global.xlsx displayng data on sheet "Unsharp Masking.jpg"

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
Image_0,5.462298,0.258574,0.559896,20.075352,0.157454,1.652308,0.090209
Image_1,4.922563,0.605464,0.992188,12.196641,0.095660,1.563715,0.182452
Image_2,4.722906,0.759910,1.000000,48.490970,0.380321,1.471624,0.760845
Image_3,5.909518,0.356181,1.000000,32.191554,0.252483,1.625751,0.372596
Image_4,6.140488,0.508290,1.000000,29.768552,0.233479,2.607935,1.007756
...,...,...,...,...,...,...,...
Image_65,5.466934,0.681942,0.811198,26.588236,0.208535,1.126274,0.108195
Image_66,5.151782,0.323378,0.994792,18.649534,0.146271,0.903066,-0.035658
Image_67,5.982434,0.492337,0.998698,29.327534,0.230020,1.933323,0.643515
Image_68,5.478651,0.888221,0.998698,33.770262,0.264865,2.284088,1.533877
Image_69,4.889200,0.628126,1.000000,26.557102,0.208291,1.055339,0.049707

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000
mean,5.316925,0.398507,0.949275,24.568417,0.192693,1.587837,0.304341
std,0.590958,0.225379,0.094324,9.888591,0.077558,0.548298,0.398266
min,4.061705,0.057250,0.555990,8.411821,0.065975,0.800783,-0.049534
25%,4.937789,0.205673,0.952148,16.969668,0.133095,1.128931,0.033184
50%,5.309245,0.367344,0.992188,24.586148,0.192833,1.523309,0.172183
75%,5.777959,0.552423,1.000000,31.580707,0.247692,1.760276,0.402556
max,6.454745,0.888221,1.000000,55.606441,0.436129,3.391121,1.981570

----------

In [35]:
print('VPMI QUALITY DARI DATA BARU\n')

for i in range(len(filename_vpmi_baru)):
    file = filename_vpmi_baru[i]
    
    desc_stat_vpmi(vpmi_baru,file)
    
    print('-'*10)

VPMI QUALITY DARI DATA BARU

Excel file on RAW_ALL_DATA_VPMI.xlsx displayng data on sheet "clean"

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
Image_0,5.796038,0.187032,0.861979,36.551744,0.286680,0.900011,-0.040714
Image_1,5.965835,0.463977,0.994792,32.652017,0.256094,2.033022,0.721839
Image_2,5.329245,0.835441,0.997396,40.863047,0.320494,0.815325,-0.419210
Image_3,6.471235,0.479624,0.924479,50.659834,0.397332,1.224689,0.333379
Image_4,5.940742,0.264794,0.954427,36.132058,0.283389,1.208267,0.116129
...,...,...,...,...,...,...,...
Image_65,5.487237,0.741008,0.766927,21.675822,0.170006,0.680471,-0.294441
Image_66,5.091956,0.415727,1.000000,38.996929,0.305858,0.862366,-0.138315
Image_67,5.746235,0.776781,0.949219,27.459027,0.215365,1.249403,0.293124
Image_68,5.260127,0.842733,0.886719,29.835508,0.234004,0.876746,-0.174551
Image_69,5.264004,0.539571,1.000000,39.189948,0.307372,0.690872,-0.465770

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000
mean,5.656301,0.466586,0.937221,33.131026,0.259851,1.081268,0.107789
std,0.376660,0.176032,0.085579,7.676035,0.060204,0.349692,0.363051
min,4.792493,0.132953,0.643229,20.483415,0.160654,0.582951,-0.465770
25%,5.407485,0.331897,0.916667,27.531670,0.215935,0.821699,-0.101455
50%,5.655673,0.463406,0.972656,32.272954,0.253121,0.980854,-0.015547
75%,5.920873,0.585804,0.997396,38.254627,0.300036,1.276389,0.291384
max,6.477856,0.842733,1.000000,56.708942,0.444776,2.161034,1.298368

Excel file on RAW_ALL_DATA_VPMI.xlsx displayng data on sheet "noisy"

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
Image_0,5.942700,0.326517,0.980469,36.737363,0.288136,6.920593,1.529905
Image_1,5.909621,0.430569,1.000000,32.693277,0.256418,6.808013,1.805496
Image_2,5.601393,0.662178,1.000000,41.482521,0.325353,6.161261,3.165640
Image_3,6.397844,0.419240,0.981771,49.909101,0.391444,7.983115,3.089268
Image_4,5.959493,0.361900,0.989583,36.085960,0.283027,6.747395,1.663772
...,...,...,...,...,...,...,...
Image_65,5.567713,0.595716,0.920573,22.109347,0.173407,5.976108,1.365608
Image_66,5.394021,0.445578,1.000000,39.869732,0.312704,5.457845,1.840093
Image_67,5.790558,0.598537,0.994792,27.621786,0.216641,6.409904,2.002022
Image_68,5.443041,0.565356,0.971354,30.626964,0.240211,5.854266,1.830579
Image_69,5.582615,0.535696,1.000000,39.991413,0.313658,5.602853,2.332071

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000
mean,5.759169,0.444513,0.977083,33.504653,0.262782,6.343200,1.816214
std,0.270639,0.087607,0.041563,7.355217,0.057688,0.605883,0.757317
min,5.135607,0.299561,0.829427,21.480003,0.168471,5.325540,0.614857
25%,5.575673,0.376577,0.977865,28.495262,0.223492,5.873895,1.320286
50%,5.764300,0.427764,0.997396,32.537103,0.255193,6.371558,1.728317
75%,5.936642,0.498608,1.000000,38.336169,0.300676,6.744827,2.062829
max,6.397844,0.662178,1.000000,56.115891,0.440125,7.983115,4.173671

----------
Excel file on RAW_PROCESSED_DATA_VPMI.xlsx displayng data on sheet "clean"

               AIE      ABWF      ACLF       AAL      LNPF        AG      VPMI
Image_0   3.581478  0.006690  0.319010  6.244716  0.048978  0.204941 -0.000856
Image_1   3.400240  0.029319  1.000000  5.766457  0.045227  0.572984 -0.003622
Image_2   3.502498  0.574216  0.537760  8.463391  0.066380  0.191032 -0.171447
Image_3   4.280601  0.088147  0.369792  8.938947  0.070109  0.312463 -0.016417
Image_4   3.422990  0.019489  0.445312  5.495319  0.043101  0.312369 -0.002149
...            ...       ...       ...       ...       ...       ...       ...
Image_65  2.599346  0.337799  0.294271  2.952577  0.023157  0.168208 -0.015388
Image_66  3.235496  0.121793  0.707031  7.602443  0.059627  0.268684 -0.031498
Image_67  2.976592  0.398183  0.562500  4.049403  0.031760  0.317178 -0.035078
Image_68  2.902004  0.335111  0.328125  5.172138  0.040566  0.184565 -0.031556
Image_69  3.421644  0.365495  0.765625  8.478016  0.066494  0.220992 -0.138663

[70 rows x 7 columns]

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000
mean,3.258161,0.137598,0.571726,5.742095,0.045036,0.285941,-0.027124
std,0.443012,0.175672,0.215378,1.809683,0.014194,0.107962,0.044314
min,2.411461,0.004003,0.205729,2.952577,0.023157,0.134483,-0.205642
25%,2.934883,0.009643,0.397461,4.594957,0.036039,0.204837,-0.031542
50%,3.239526,0.064871,0.559896,5.519023,0.043286,0.257630,-0.008132
75%,3.530311,0.219867,0.750977,6.808636,0.053401,0.352603,-0.000928
max,4.514136,0.688775,1.000000,10.984836,0.086156,0.623783,-0.000198

Excel file on RAW_PROCESSED_DATA_VPMI.xlsx displayng data on sheet "noisy"

               AIE      ABWF      ACLF       AAL      LNPF        AG      VPMI
Image_0   3.683571  0.058167  0.441406  6.258137  0.049083  0.903758 -0.000678
Image_1   3.473988  0.100615  1.000000  5.883996  0.046149  1.135042  0.002948
Image_2   3.599850  0.521623  0.704427  8.493252  0.066614  0.888322 -0.015054
Image_3   4.316745  0.144396  0.468750  9.033048  0.070847  1.170639  0.004705
Image_4   3.469732  0.072250  0.503906  5.599751  0.043920  0.922817 -0.000643
...            ...       ...       ...       ...       ...       ...       ...
Image_65  2.825749  0.389465  0.377604  3.008870  0.023599  0.715618 -0.004734
Image_66  3.337913  0.148983  0.742188  7.664309  0.060112  0.956295 -0.001430
Image_67  3.136626  0.400051  0.587240  4.098178  0.032143  0.852939 -0.005435
Image_68  3.073116  0.295792  0.433594  5.152545  0.040412  0.730973 -0.007201
Image_69  3.486300  0.386932  0.838542  8.517776  0.066806  0.943962 -0.006287

[70 rows x 7 columns]

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000
mean,3.357076,0.173290,0.636458,5.795820,0.045457,0.910256,0.000225
std,0.406328,0.150325,0.192512,1.802719,0.014139,0.167443,0.008032
min,2.583355,0.038686,0.309896,3.008870,0.023599,0.616473,-0.015054
25%,3.074208,0.066527,0.496094,4.659704,0.036547,0.794063,-0.002042
50%,3.334278,0.112983,0.623698,5.529419,0.043368,0.896999,-0.000936
75%,3.598989,0.247952,0.796549,6.850161,0.053727,1.024309,0.000326
max,4.493354,0.647435,1.000000,11.052658,0.086688,1.471367,0.035049

----------
Excel file on RGB_SKIP_RAW_CLEAN.xlsx displayng data on sheet "Clean Synthetic Image (Without "

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
Image_0,5.909237,0.193395,0.856771,36.555532,0.286710,0.851078,-0.065307
Image_1,6.092440,0.479839,0.986979,32.676377,0.256285,2.014323,0.747079
Image_2,5.506339,0.836269,1.000000,40.895826,0.320752,0.757190,-0.592678
Image_3,6.518792,0.483073,0.920573,50.640349,0.397179,1.173842,0.266248
Image_4,6.058856,0.275565,0.954427,36.125706,0.283339,1.159018,0.096127
...,...,...,...,...,...,...,...
Image_65,5.600770,0.743521,0.760417,21.675371,0.170003,0.621581,-0.369287
Image_66,5.236832,0.424378,0.994792,39.008022,0.305945,0.825032,-0.187683
Image_67,5.861895,0.786355,0.946615,27.474881,0.215489,1.208863,0.257308
Image_68,5.410322,0.845938,0.880208,29.846115,0.234087,0.818389,-0.272668
Image_69,5.384317,0.543999,1.000000,39.202539,0.307471,0.650975,-0.557765

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000
mean,5.786892,0.476076,0.935398,33.146929,0.259976,1.036998,0.065568
std,0.351440,0.173720,0.085571,7.672171,0.060174,0.356885,0.384748
min,4.961566,0.143622,0.640625,20.496051,0.160753,0.492633,-0.597683
25%,5.553907,0.342117,0.916667,27.542563,0.216020,0.769557,-0.134455
50%,5.818129,0.476836,0.968750,32.294502,0.253290,0.937635,-0.041402
75%,6.030349,0.590934,1.000000,38.259812,0.300077,1.231148,0.252987
max,6.544482,0.845938,1.000000,56.710557,0.444789,2.137102,1.291532

Excel file on RGB_SKIP_RAW_CLEAN.xlsx displayng data on sheet "Conditional Contrast Correction"

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
Image_0,NaN,0.279853,0.772135,211.680226,0.339763,0.339986,NaN
Image_1,NaN,0.003906,0.358073,254.748542,0.001972,0.008053,NaN
Image_2,NaN,0.538113,0.563802,240.992175,0.109865,0.232892,NaN
Image_3,NaN,0.060323,0.493490,249.869574,0.040239,0.042825,NaN
Image_4,4.817331,0.232818,0.553385,68.389536,0.536389,0.188929,-0.800352
...,...,...,...,...,...,...,...
Image_65,5.370259,0.676673,0.574219,57.471603,0.450758,0.283789,-1.709131
Image_66,NaN,0.003906,0.355469,254.785965,0.001679,0.006059,NaN
Image_67,4.076655,0.590019,0.682292,194.988153,0.470681,0.356165,-1.150465
Image_68,NaN,0.534363,0.552083,200.580823,0.426817,0.557577,NaN
Image_69,NaN,0.069298,0.345052,240.134632,0.116591,0.092262,NaN

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,19.000000,70.000000,70.000000,70.000000,70.000000,70.000000,19.000000
mean,4.879547,0.182424,0.526339,202.361153,0.203599,0.141869,-1.106430
std,0.596051,0.197826,0.151970,75.277994,0.234266,0.127099,0.468878
min,3.705464,0.003905,0.289062,33.187099,0.000023,0.000150,-2.202493
25%,4.644073,0.003906,0.361003,195.367403,0.017348,0.032332,-1.331643
50%,4.996809,0.112810,0.512370,245.135916,0.077365,0.099545,-0.914125
75%,5.343576,0.322342,0.616862,252.788174,0.371330,0.249673,-0.818702
max,5.647691,0.676673,0.898438,254.997006,0.746843,0.557577,-0.333674

Excel file on RGB_SKIP_RAW_CLEAN.xlsx displayng data on sheet "Contrast Fixing Image.jpg"

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
Image_0,5.831123,0.154867,0.839844,35.543345,0.278771,0.235616,-0.440925
Image_1,6.045826,0.463599,0.962240,32.015234,0.251100,1.085094,0.079789
Image_2,5.359802,0.833898,1.000000,39.875499,0.312749,0.282179,-2.551506
Image_3,6.528808,0.470365,0.938802,52.099950,0.408627,0.350752,-1.780621
Image_4,6.094986,0.257567,0.968750,37.433354,0.293595,0.303219,-0.768683
...,...,...,...,...,...,...,...
Image_65,5.847011,0.799264,0.951823,27.194763,0.213292,0.277346,-1.755432
Image_66,5.083205,0.392840,0.971354,38.396360,0.301148,0.242967,-1.192313
Image_67,5.895225,0.786962,0.984375,28.071150,0.220166,0.540439,-0.892644
Image_68,5.371941,0.799041,0.972656,33.038547,0.259126,0.335958,-1.702464
Image_69,5.252264,0.529026,1.000000,38.233278,0.299869,0.252033,-1.656688

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000
mean,5.768941,0.454002,0.971261,34.774283,0.272739,0.427771,-0.917514
std,0.364981,0.176530,0.032445,7.972477,0.062529,0.233452,0.624753
min,4.842891,0.129274,0.839844,19.281232,0.151225,0.184656,-2.907244
25%,5.520776,0.315684,0.958659,28.459925,0.223215,0.275845,-1.191741
50%,5.827439,0.450993,0.981120,33.092439,0.259549,0.358015,-0.899797
75%,6.041550,0.557469,0.998372,39.690576,0.311299,0.485402,-0.504159
max,6.528808,0.833898,1.000000,57.209326,0.448701,1.265069,0.371009

Excel file on RGB_SKIP_RAW_CLEAN.xlsx displayng data on sheet "Denoised Image.jpg"

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
Image_0,5.881247,0.173393,0.838542,36.145170,0.283492,0.209055,-0.547392
Image_1,6.071507,0.487675,0.957031,32.084130,0.251640,1.038946,0.039305
Image_2,5.446397,0.836523,1.000000,40.481073,0.317499,0.262804,-2.788835
Image_3,6.510935,0.482994,0.898438,50.158309,0.393399,0.297858,-1.942109
Image_4,6.065916,0.262348,0.924479,35.626127,0.279421,0.255364,-0.809576
...,...,...,...,...,...,...,...
Image_65,5.571936,0.741331,0.739583,21.196443,0.166247,0.196268,-1.193055
Image_66,5.203134,0.409860,0.968750,38.659297,0.303210,0.221421,-1.362522
Image_67,5.858660,0.797195,0.942708,26.941244,0.211304,0.476620,-0.994630
Image_68,5.376767,0.846383,0.867188,29.419726,0.230743,0.269880,-1.720690
Image_69,5.356327,0.545722,1.000000,38.855678,0.304750,0.234083,-1.866156

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000
mean,5.764135,0.469260,0.919159,32.665386,0.256199,0.379536,-0.967393
std,0.359916,0.177741,0.095875,7.671832,0.060171,0.236818,0.671465
min,4.922538,0.137322,0.608073,20.024636,0.157056,0.137440,-3.034351
25%,5.514267,0.338936,0.886719,27.028777,0.211990,0.226049,-1.210371
50%,5.816654,0.468406,0.955078,31.819286,0.249563,0.309072,-0.821674
75%,6.002833,0.588671,0.992839,37.815991,0.296596,0.418119,-0.546128
max,6.536748,0.846383,1.000000,56.241997,0.441114,1.203282,0.299166

Excel file on RGB_SKIP_RAW_CLEAN.xlsx displayng data on sheet "Global Mean Contrast (Sat. Fix "

               AIE      ABWF      ACLF       AAL      LNPF        AG      VPMI
Image_0   2.836144  0.008184  0.160156  4.410533  0.034592  0.080499 -0.000467
Image_1   2.362356  0.066366  0.132812  2.501109  0.019617  0.196355 -0.000959
Image_2   2.253221  0.452921  0.111979  3.161101  0.024793  0.072852 -0.010707
Image_3   3.383737  0.147120  0.195312  6.355696  0.049849  0.123036 -0.014651
Image_4   3.177346  0.106427  0.255208  5.914382  0.046387  0.129132 -0.011822
...            ...       ...       ...       ...       ...       ...       ...
Image_65  3.871039  0.632272  0.208333  6.495344  0.050944  0.134676 -0.075136
Image_66  2.201650  0.145215  0.162760  3.235037  0.025373  0.069031 -0.005092
Image_67  2.800259  0.403027  0.230469  3.348575  0.026263  0.158998 -0.018123
Image_68  3.418603  0.421336  0.161458  5.606492  0.043972  0.125348 -0.030638
Image_69  2.164331  0.394726  0.071615  2.438396  0.019125  0.076855 -0.004331

[70 rows x 7 columns]

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000
mean,2.967725,0.204692,0.221782,5.096079,0.039969,0.128820,-0.022366
std,0.758320,0.133397,0.077560,4.071813,0.031936,0.037722,0.033660
min,1.982619,0.006618,0.071615,1.438930,0.011286,0.066989,-0.165740
25%,2.454741,0.101192,0.160482,2.700710,0.021182,0.099596,-0.023838
50%,2.769280,0.158316,0.216146,3.765448,0.029533,0.127263,-0.009985
75%,3.354933,0.284022,0.262370,6.071191,0.047617,0.151919,-0.003798
max,5.377047,0.632272,0.460938,25.448166,0.199593,0.244395,-0.000235

Excel file on RGB_SKIP_RAW_CLEAN.xlsx displayng data on sheet "Grayness Index.jpg"

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
Image_0,3.458508,0.103559,0.326823,7.635784,0.059888,0.301950,-1.211101e-02
Image_1,0.180842,0.003906,0.108073,0.140409,0.001101,0.039504,-3.919414e-07
Image_2,5.531865,0.252670,0.919271,88.088935,0.690894,2.274738,1.052580e+00
Image_3,1.685909,0.027643,0.141927,2.066614,0.016209,0.204465,-2.455218e-04
Image_4,2.693346,0.114835,0.186198,5.347360,0.041940,0.138299,-6.893606e-03
...,...,...,...,...,...,...,...
Image_65,2.440989,0.327552,0.141927,2.446275,0.019186,0.188363,-5.243691e-03
Image_66,0.359238,0.003906,0.111979,0.198259,0.001555,0.085429,-8.672125e-07
Image_67,5.068903,0.512347,0.614583,87.689665,0.687762,0.591443,-8.317418e-01
Image_68,5.316928,0.518046,0.768229,87.667811,0.687591,1.017580,3.658070e-02
Image_69,2.280231,0.365495,0.113281,3.581607,0.028091,0.267478,-5.045605e-03

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,7.000000e+01
mean,2.647423,0.138749,0.340941,30.984381,0.140702,0.830452,1.970934e-01
std,1.874218,0.146447,0.296586,61.507865,0.254875,2.561944,8.412322e-01
min,0.009321,0.003906,0.101562,0.004369,0.000034,0.001499,-8.317418e-01
25%,1.249679,0.003917,0.139974,1.077133,0.008448,0.116842,-5.406922e-03
50%,2.534596,0.092084,0.231771,3.180723,0.024947,0.196414,-2.252658e-04
75%,3.451845,0.209942,0.332682,6.830394,0.053572,0.614614,-5.696234e-07
max,6.513693,0.573014,1.000000,244.471509,0.942292,20.726879,5.629185e+00

Excel file on RGB_SKIP_RAW_CLEAN.xlsx displayng data on sheet "Histogram Stretched.jpg"

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
Image_0,4.940046,0.253207,0.667969,110.190963,0.864243,0.194387,-1.706326
Image_1,NaN,0.248182,0.438802,201.703452,0.418012,0.234252,NaN
Image_2,4.118345,0.520456,0.559896,125.072695,0.980962,0.222545,-2.552064
Image_3,NaN,0.354878,0.622396,145.436345,0.859323,0.196847,NaN
Image_4,4.817331,0.232818,0.553385,68.389536,0.536389,0.188929,-0.800352
...,...,...,...,...,...,...,...
Image_65,5.370259,0.676673,0.574219,57.471603,0.450758,0.283789,-1.709131
Image_66,NaN,0.186145,0.484375,172.293136,0.648681,0.103848,NaN
Image_67,4.263352,0.459693,0.513021,98.449634,0.772154,0.201692,-1.793193
Image_68,4.545859,0.513864,0.597656,105.467266,0.827194,0.308600,-1.958836
Image_69,NaN,0.552316,0.458333,148.427952,0.835859,0.222690,NaN

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,49.000000,70.000000,70.000000,70.000000,70.000000,70.000000,49.000000
mean,4.290074,0.297935,0.562072,123.420269,0.764876,0.192597,-1.346786
std,0.741788,0.126120,0.105779,38.126561,0.185402,0.068589,0.542980
min,2.512312,0.019415,0.414062,33.187099,0.260291,0.087509,-2.567596
25%,3.725622,0.205119,0.475586,98.883517,0.649700,0.147373,-1.709131
50%,4.263352,0.274229,0.554688,127.430766,0.813069,0.178287,-1.324956
75%,4.822908,0.376968,0.621094,148.650934,0.933038,0.234067,-0.893717
max,5.647691,0.676673,0.898438,201.703452,0.999760,0.466132,-0.333674

Excel file on RGB_SKIP_RAW_CLEAN.xlsx displayng data on sheet "S-Curve Correction.jpg"

               AIE      ABWF      ACLF       AAL      LNPF        AG      VPMI
Image_0   3.012864  0.008423  0.243490  6.128725  0.048068  0.092024 -0.001022
Image_1   2.593814  0.103484  0.197917  3.201329  0.025108  0.257983 -0.002607
Image_2   2.440914  0.467935  0.166667  4.374433  0.034309  0.093675 -0.022312
Image_3   3.699338  0.190299  0.303385  8.978364  0.070419  0.164322 -0.039185
Image_4   3.380344  0.125611  0.417969  8.530668  0.066907  0.179226 -0.029450
...            ...       ...       ...       ...       ...       ...       ...
Image_65  4.228370  0.640722  0.329427  8.621823  0.067622  0.180915 -0.148865
Image_66  2.418759  0.167098  0.251302  4.432775  0.034767  0.091462 -0.012185
Image_67  3.057554  0.449637  0.367188  4.356357  0.034168  0.201462 -0.039867
Image_68  3.692292  0.491868  0.247396  7.691658  0.060327  0.167626 -0.069840
Image_69  2.378546  0.391593  0.101562  3.209355  0.025171  0.097670 -0.007991

[70 rows x 7 columns]

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000
mean,3.205899,0.228278,0.353925,7.157438,0.056137,0.165252,-0.051764
std,0.808692,0.138010,0.136297,6.271405,0.049187,0.053163,0.076761
min,2.100397,0.008423,0.101562,1.786227,0.014010,0.080637,-0.401581
25%,2.599143,0.111305,0.244466,3.568339,0.027987,0.124405,-0.056330
50%,3.013024,0.199993,0.343750,5.166595,0.040522,0.162691,-0.022509
75%,3.662842,0.314866,0.417969,8.527241,0.066880,0.196463,-0.008411
max,5.544958,0.640722,0.791667,39.491904,0.309740,0.345895,-0.001022

Excel file on RGB_SKIP_RAW_CLEAN.xlsx displayng data on sheet "Saturation Fixing.jpg"

               AIE      ABWF      ACLF       AAL      LNPF        AG      VPMI
Image_0   3.032143  0.039105  0.196615  5.165851  0.040516  0.105043 -0.003071
Image_1   2.547937  0.088704  0.164062  2.682970  0.021043  0.238984 -0.001611
Image_2   2.449911  0.474478  0.132812  3.808818  0.029873  0.091899 -0.015883
Image_3   3.569852  0.203094  0.236979  7.386864  0.057936  0.147127 -0.027522
Image_4   3.228859  0.095124  0.312500  6.567828  0.051512  0.164833 -0.012860
...            ...       ...       ...       ...       ...       ...       ...
Image_65  4.003333  0.647917  0.255208  6.751741  0.052955  0.177005 -0.087570
Image_66  2.249944  0.168758  0.201823  3.372318  0.026450  0.086122 -0.007170
Image_67  2.963154  0.387102  0.285156  3.651699  0.028641  0.191039 -0.022371
Image_68  3.373050  0.505474  0.194010  6.098064  0.047828  0.156576 -0.042322
Image_69  2.346483  0.377103  0.088542  2.734946  0.021451  0.089974 -0.005839

[70 rows x 7 columns]

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000
mean,3.096924,0.226698,0.273289,5.580728,0.043770,0.157894,-0.029288
std,0.706338,0.130396,0.093912,4.099968,0.032157,0.042693,0.041169
min,2.156801,0.039105,0.088542,1.750357,0.013728,0.086122,-0.222522
25%,2.597687,0.131347,0.196940,3.180072,0.024942,0.124476,-0.030862
50%,2.931413,0.194561,0.268229,4.418623,0.034656,0.157977,-0.014822
75%,3.432462,0.309399,0.323568,6.551927,0.051388,0.188094,-0.006204
max,5.263759,0.647917,0.559896,25.817171,0.202488,0.277444,-0.001004

Excel file on RGB_SKIP_RAW_CLEAN.xlsx displayng data on sheet "Unsharp Masking.jpg"

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
Image_0,6.476413,0.288042,0.962240,210.341689,0.350261,1.502568,0.369336
Image_1,NaN,0.003906,0.419271,254.298708,0.005500,0.062318,NaN
Image_2,6.626002,0.530136,1.000000,236.129321,0.148005,4.141364,1.065841
Image_3,NaN,0.073939,0.759115,248.518647,0.050834,0.326520,NaN
Image_4,4.843478,0.242305,0.566406,68.412176,0.536566,0.288571,-0.639518
...,...,...,...,...,...,...,...
Image_65,5.399346,0.672802,0.610677,57.449801,0.450587,0.500677,-0.997630
Image_66,NaN,0.003906,0.421875,254.035677,0.007563,0.136516,NaN
Image_67,6.092529,0.586129,0.955729,194.076592,0.477831,1.178358,0.386137
Image_68,6.431273,0.539194,0.998698,197.806488,0.448577,2.255761,1.823216
Image_69,NaN,0.073228,0.421875,238.395502,0.130231,0.355426,NaN

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,49.000000,70.000000,70.000000,70.000000,70.000000,70.000000,49.000000
mean,5.818999,0.189648,0.745219,200.677982,0.216778,1.021842,-0.027081
std,0.765102,0.196561,0.218748,74.391664,0.228672,1.480582,0.711757
min,3.728478,0.003906,0.394531,33.173514,0.000159,0.002415,-1.722535
25%,5.358592,0.004321,0.554688,194.545501,0.039105,0.216645,-0.534022
50%,6.192676,0.141947,0.787760,241.221322,0.108068,0.460478,-0.001295
75%,6.431273,0.313500,0.944336,250.014056,0.376254,1.077706,0.382476
max,6.626002,0.672802,1.000000,254.979675,0.746781,7.024814,1.823216

----------
Excel file on RGB_SKIP_RAW_CLEAN_global.xlsx displayng data on sheet "After Contrast Conditional Enha"

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
Image_0,NaN,0.279853,0.772135,211.680226,0.339763,0.339986,NaN
Image_1,NaN,0.003906,0.358073,254.748542,0.001972,0.008053,NaN
Image_2,NaN,0.538113,0.563802,240.992175,0.109865,0.232892,NaN
Image_3,NaN,0.060323,0.493490,249.869574,0.040239,0.042825,NaN
Image_4,4.817331,0.232818,0.553385,68.389536,0.536389,0.188929,-0.800352
...,...,...,...,...,...,...,...
Image_65,5.370259,0.676673,0.574219,57.471603,0.450758,0.283789,-1.709131
Image_66,NaN,0.003906,0.355469,254.785965,0.001679,0.006059,NaN
Image_67,4.076655,0.590019,0.682292,194.988153,0.470681,0.356165,-1.150465
Image_68,NaN,0.534363,0.552083,200.580823,0.426817,0.557577,NaN
Image_69,NaN,0.069298,0.345052,240.134632,0.116591,0.092262,NaN

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,19.000000,70.000000,70.000000,70.000000,70.000000,70.000000,19.000000
mean,4.879547,0.182424,0.526339,202.361153,0.203599,0.141869,-1.106430
std,0.596051,0.197826,0.151970,75.277994,0.234266,0.127099,0.468878
min,3.705464,0.003905,0.289062,33.187099,0.000023,0.000150,-2.202493
25%,4.644073,0.003906,0.361003,195.367403,0.017348,0.032332,-1.331643
50%,4.996809,0.112810,0.512370,245.135916,0.077365,0.099545,-0.914125
75%,5.343576,0.322342,0.616862,252.788174,0.371330,0.249673,-0.818702
max,5.647691,0.676673,0.898438,254.997006,0.746843,0.557577,-0.333674

Excel file on RGB_SKIP_RAW_CLEAN_global.xlsx displayng data on sheet "Denoised Image.jpg"

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
Image_0,5.881247,0.173393,0.838542,36.145170,0.283492,0.209055,-0.547392
Image_1,6.071507,0.487675,0.957031,32.084130,0.251640,1.038946,0.039305
Image_2,5.446397,0.836523,1.000000,40.481073,0.317499,0.262804,-2.788835
Image_3,6.510935,0.482994,0.898438,50.158309,0.393399,0.297858,-1.942109
Image_4,6.065916,0.262348,0.924479,35.626127,0.279421,0.255364,-0.809576
...,...,...,...,...,...,...,...
Image_65,5.571936,0.741331,0.739583,21.196443,0.166247,0.196268,-1.193055
Image_66,5.203134,0.409860,0.968750,38.659297,0.303210,0.221421,-1.362522
Image_67,5.858660,0.797195,0.942708,26.941244,0.211304,0.476620,-0.994630
Image_68,5.376767,0.846383,0.867188,29.419726,0.230743,0.269880,-1.720690
Image_69,5.356327,0.545722,1.000000,38.855678,0.304750,0.234083,-1.866156

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000
mean,5.764135,0.469260,0.919159,32.665386,0.256199,0.379536,-0.967393
std,0.359916,0.177741,0.095875,7.671832,0.060171,0.236818,0.671465
min,4.922538,0.137322,0.608073,20.024636,0.157056,0.137440,-3.034351
25%,5.514267,0.338936,0.886719,27.028777,0.211990,0.226049,-1.210371
50%,5.816654,0.468406,0.955078,31.819286,0.249563,0.309072,-0.821674
75%,6.002833,0.588671,0.992839,37.815991,0.296596,0.418119,-0.546128
max,6.536748,0.846383,1.000000,56.241997,0.441114,1.203282,0.299166

Excel file on RGB_SKIP_RAW_CLEAN_global.xlsx displayng data on sheet "Grayness Index.jpg"

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
Image_0,3.458508,0.103559,0.326823,7.635784,0.059888,0.301950,-1.211101e-02
Image_1,0.180842,0.003906,0.108073,0.140409,0.001101,0.039504,-3.919414e-07
Image_2,5.531865,0.252670,0.919271,88.088935,0.690894,2.274738,1.052580e+00
Image_3,1.685909,0.027643,0.141927,2.066614,0.016209,0.204465,-2.455218e-04
Image_4,2.693346,0.114835,0.186198,5.347360,0.041940,0.138299,-6.893606e-03
...,...,...,...,...,...,...,...
Image_65,2.440989,0.327552,0.141927,2.446275,0.019186,0.188363,-5.243691e-03
Image_66,0.359238,0.003906,0.111979,0.198259,0.001555,0.085429,-8.672125e-07
Image_67,5.068903,0.512347,0.614583,87.689665,0.687762,0.591443,-8.317418e-01
Image_68,5.316928,0.518046,0.768229,87.667811,0.687591,1.017580,3.658070e-02
Image_69,2.280231,0.365495,0.113281,3.581607,0.028091,0.267478,-5.045605e-03

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,7.000000e+01
mean,2.647423,0.138749,0.340941,30.984381,0.140702,0.830452,1.970934e-01
std,1.874218,0.146447,0.296586,61.507865,0.254875,2.561944,8.412322e-01
min,0.009321,0.003906,0.101562,0.004369,0.000034,0.001499,-8.317418e-01
25%,1.249679,0.003917,0.139974,1.077133,0.008448,0.116842,-5.406922e-03
50%,2.534596,0.092084,0.231771,3.180723,0.024947,0.196414,-2.252658e-04
75%,3.451845,0.209942,0.332682,6.830394,0.053572,0.614614,-5.696234e-07
max,6.513693,0.573014,1.000000,244.471509,0.942292,20.726879,5.629185e+00

Excel file on RGB_SKIP_RAW_CLEAN_global.xlsx displayng data on sheet "Unsharp Masking.jpg"

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
Image_0,6.476413,0.288042,0.962240,210.341689,0.350261,1.502568,0.369336
Image_1,NaN,0.003906,0.419271,254.298708,0.005500,0.062318,NaN
Image_2,6.626002,0.530136,1.000000,236.129321,0.148005,4.141364,1.065841
Image_3,NaN,0.073939,0.759115,248.518647,0.050834,0.326520,NaN
Image_4,4.843478,0.242305,0.566406,68.412176,0.536566,0.288571,-0.639518
...,...,...,...,...,...,...,...
Image_65,5.399346,0.672802,0.610677,57.449801,0.450587,0.500677,-0.997630
Image_66,NaN,0.003906,0.421875,254.035677,0.007563,0.136516,NaN
Image_67,6.092529,0.586129,0.955729,194.076592,0.477831,1.178358,0.386137
Image_68,6.431273,0.539194,0.998698,197.806488,0.448577,2.255761,1.823216
Image_69,NaN,0.073228,0.421875,238.395502,0.130231,0.355426,NaN

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,49.000000,70.000000,70.000000,70.000000,70.000000,70.000000,49.000000
mean,5.818999,0.189648,0.745219,200.677982,0.216778,1.021842,-0.027081
std,0.765102,0.196561,0.218748,74.391664,0.228672,1.480582,0.711757
min,3.728478,0.003906,0.394531,33.173514,0.000159,0.002415,-1.722535
25%,5.358592,0.004321,0.554688,194.545501,0.039105,0.216645,-0.534022
50%,6.192676,0.141947,0.787760,241.221322,0.108068,0.460478,-0.001295
75%,6.431273,0.313500,0.944336,250.014056,0.376254,1.077706,0.382476
max,6.626002,0.672802,1.000000,254.979675,0.746781,7.024814,1.823216

----------
Excel file on RGB_SKIP_RAW_NOISY.xlsx displayng data on sheet "Conditional Contrast Correction"

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
Image_0,4.640563,0.327977,0.486979,80.656182,0.632598,0.418116,-0.589849
Image_1,NaN,0.003906,0.358073,254.225940,0.006071,0.029152,NaN
Image_2,NaN,0.448427,0.595052,207.785004,0.370314,0.757148,NaN
Image_3,NaN,0.423984,0.652344,210.534543,0.348749,0.819708,NaN
Image_4,NaN,0.407427,0.658854,218.171846,0.288848,1.074549,NaN
...,...,...,...,...,...,...,...
Image_65,5.247440,0.564855,0.566406,69.299081,0.543522,2.084321,0.966857
Image_66,NaN,0.003966,0.359375,253.068437,0.015150,0.070995,NaN
Image_67,NaN,0.469095,0.585938,228.559119,0.207379,0.881881,NaN
Image_68,4.593251,0.417556,0.436198,68.973689,0.540970,0.691748,-0.240627
Image_69,NaN,0.053438,0.481771,245.109100,0.077576,0.348447,NaN

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,24.000000,70.000000,70.000000,70.000000,70.000000,70.000000,24.000000
mean,4.755006,0.246557,0.539658,192.412764,0.264355,0.657483,-0.090818
std,0.443595,0.187061,0.124407,74.915236,0.243274,0.594436,0.481238
min,3.909649,0.003906,0.308594,43.064862,0.000151,0.001617,-0.940539
25%,4.525457,0.012527,0.437826,98.724931,0.031563,0.133986,-0.427613
50%,4.683419,0.308802,0.537760,222.783276,0.252680,0.487710,-0.214124
75%,5.094312,0.406718,0.631510,250.975663,0.407273,0.898855,0.279383
max,5.595620,0.564855,0.851562,254.980726,0.780635,2.693938,0.966857

Excel file on RGB_SKIP_RAW_NOISY.xlsx displayng data on sheet "Contrast Fixing Image.jpg"

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
Image_0,6.072838,0.319538,0.895833,35.141150,0.275617,4.374158,1.020057
Image_1,6.054722,0.454909,0.963542,31.727638,0.248844,5.552656,1.633325
Image_2,5.730808,0.725497,1.000000,40.157291,0.314959,3.761006,2.502610
Image_3,6.550953,0.427924,0.960938,50.366806,0.395034,4.962675,2.459364
Image_4,6.148543,0.374547,0.966146,36.745819,0.288203,5.560719,1.587239
...,...,...,...,...,...,...,...
Image_65,5.983735,0.667755,0.958333,27.076097,0.212362,6.282282,2.155952
Image_66,5.535281,0.481886,0.976562,38.981491,0.305737,3.229641,1.347013
Image_67,5.969599,0.657332,0.981771,27.522402,0.215862,5.421977,2.028131
Image_68,5.616095,0.644140,0.964844,32.703074,0.256495,4.587439,1.967508
Image_69,5.722970,0.589299,1.000000,38.666571,0.303267,3.663672,1.915965

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000
mean,5.954778,0.473283,0.974628,34.255664,0.268672,4.856608,1.691321
std,0.263695,0.105059,0.027393,7.288798,0.057167,0.689730,0.610397
min,5.337575,0.311863,0.890625,20.066551,0.157385,3.229641,0.608180
25%,5.766288,0.387350,0.962240,28.535005,0.223804,4.382299,1.330553
50%,5.988382,0.456814,0.983724,32.574450,0.255486,4.732050,1.585716
75%,6.145077,0.544864,0.999674,39.243268,0.307790,5.230240,1.978619
max,6.550953,0.725497,1.000000,55.156156,0.432597,6.558499,3.418303

Excel file on RGB_SKIP_RAW_NOISY.xlsx displayng data on sheet "Denoised Image.jpg"

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
Image_0,6.157282,0.332340,0.897135,36.033726,0.282617,4.416254,1.111771
Image_1,6.121343,0.465171,0.958333,32.055303,0.251414,5.495777,1.686569
Image_2,5.840025,0.731224,1.000000,40.954077,0.321208,3.826277,2.655490
Image_3,6.575065,0.436488,0.940104,49.172204,0.385664,4.758445,2.341718
Image_4,6.177942,0.376383,0.932292,35.582095,0.279075,5.266736,1.450104
...,...,...,...,...,...,...,...
Image_65,5.780952,0.650768,0.761719,21.536327,0.168912,4.866747,1.105044
Image_66,5.656953,0.495813,0.972656,39.409046,0.309091,3.275310,1.443299
Image_67,6.002841,0.658970,0.953125,27.044673,0.212115,5.191004,1.900170
Image_68,5.670994,0.641774,0.880208,30.149903,0.236470,4.147815,1.554728
Image_69,5.829930,0.599897,1.000000,39.458162,0.309476,3.720755,2.051691

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000
mean,5.988511,0.479916,0.934654,32.924919,0.258235,4.556496,1.567464
std,0.258799,0.103874,0.078990,7.328949,0.057482,0.510981,0.659050
min,5.433921,0.301389,0.688802,20.977633,0.164530,3.275310,0.443784
25%,5.815491,0.397012,0.902995,27.945837,0.219183,4.218913,1.106726
50%,5.995712,0.464255,0.962240,31.895182,0.250158,4.502800,1.503799
75%,6.161026,0.551142,0.999023,37.763447,0.296184,4.855629,1.881460
max,6.575065,0.731224,1.000000,55.475297,0.435100,6.137018,3.497948

Excel file on RGB_SKIP_RAW_NOISY.xlsx displayng data on sheet "Global Mean Contrast (Sat. Fix "

               AIE      ABWF      ACLF       AAL      LNPF        AG      VPMI
Image_0   3.405071  0.190604  0.256510  5.180426  0.040631  0.400404 -0.008932
Image_1   3.159001  0.227744  0.209635  3.211287  0.025187  0.451447 -0.004358
Image_2   3.064138  0.403425  0.203125  4.307123  0.033781  0.338031 -0.013273
Image_3   3.953593  0.269879  0.264323  6.708019  0.052612  0.468932 -0.016211
Image_4   3.716853  0.251290  0.332031  6.373335  0.049987  0.540039 -0.013779
...            ...       ...       ...       ...       ...       ...       ...
Image_65  4.348887  0.554781  0.272135  7.406940  0.058094  1.355929  0.016755
Image_66  2.877415  0.255003  0.195312  3.827502  0.030020  0.280134 -0.007898
Image_67  3.337827  0.413847  0.294271  3.693882  0.028972  0.486242 -0.012251
Image_68  3.889875  0.426961  0.226562  6.005508  0.047102  0.574052 -0.014192
Image_69  2.929372  0.340284  0.152344  3.075295  0.024120  0.308421 -0.006216

[70 rows x 7 columns]

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000
mean,3.537300,0.291164,0.279129,5.346151,0.041931,0.576410,-0.005035
std,0.574045,0.078684,0.060291,2.895884,0.022713,0.381232,0.018935
min,2.841356,0.172722,0.152344,2.543725,0.019951,0.280134,-0.028899
25%,3.157988,0.232829,0.229167,3.484217,0.027327,0.387609,-0.012526
50%,3.357904,0.278843,0.274740,4.390365,0.034434,0.426346,-0.008734
75%,3.869647,0.340250,0.322591,6.442905,0.050533,0.550394,-0.005255
max,5.484980,0.554781,0.428385,19.840268,0.155610,2.092631,0.096360

Excel file on RGB_SKIP_RAW_NOISY.xlsx displayng data on sheet "Grayness Index.jpg"

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
Image_0,3.475251,0.240038,0.255208,5.464973,0.042863,0.547109,-0.007940
Image_1,0.676156,0.003906,0.115885,0.599921,0.004705,0.206812,-0.000003
Image_2,4.081554,0.525064,0.203125,7.078552,0.055518,1.268163,0.008283
Image_3,4.115907,0.356361,0.319010,7.001083,0.054910,1.089742,0.003186
Image_4,4.132118,0.376323,0.279948,7.478637,0.058656,1.460734,0.013959
...,...,...,...,...,...,...,...
Image_65,3.638622,0.419682,0.259115,4.896463,0.038404,0.855478,-0.003422
Image_66,1.517517,0.023281,0.223958,1.467772,0.011512,0.534359,-0.000082
Image_67,5.328283,0.416751,0.593750,77.609865,0.608705,2.789955,1.187976
Image_68,3.492365,0.421468,0.246094,5.449033,0.042738,0.634918,-0.010145
Image_69,6.315672,0.283360,1.000000,198.075792,0.446464,6.759601,2.202783

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000
mean,3.764849,0.268275,0.426618,34.231137,0.237846,2.800855,0.924055
std,1.670162,0.163766,0.285628,47.610228,0.304989,5.203016,2.341620
min,0.117084,0.003906,0.115885,0.066850,0.000524,0.031313,-0.010145
25%,2.861397,0.135813,0.246094,3.802068,0.029820,0.600189,-0.000258
50%,3.861851,0.298828,0.279948,5.899174,0.046268,1.100373,0.003039
75%,5.235028,0.410693,0.590495,72.022167,0.547399,2.441149,0.983309
max,6.806978,0.525064,1.000000,198.075792,0.920619,29.283661,12.982075

Excel file on RGB_SKIP_RAW_NOISY.xlsx displayng data on sheet "Histogram Stretched.jpg"

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
Image_0,4.640563,0.327977,0.486979,80.656182,0.632598,0.418116,-0.589849
Image_1,NaN,0.287456,0.447917,164.164899,0.712432,0.366659,NaN
Image_2,4.019716,0.383172,0.421875,104.379742,0.818665,0.398281,-0.706517
Image_3,4.735221,0.332318,0.457031,105.835526,0.830083,0.407858,-0.772412
Image_4,4.472790,0.308305,0.557292,110.320208,0.865257,0.495813,-0.673014
...,...,...,...,...,...,...,...
Image_65,5.247440,0.564855,0.566406,69.299081,0.543522,2.084321,0.966857
Image_66,NaN,0.295871,0.484375,155.516125,0.780266,0.330397,NaN
Image_67,4.086979,0.384013,0.489583,113.242519,0.888177,0.439275,-0.809941
Image_68,4.593251,0.417556,0.436198,68.973689,0.540970,0.691748,-0.240627
Image_69,3.465654,0.419100,0.455729,128.148149,0.994916,0.464225,-0.729097

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,64.000000,70.000000,70.000000,70.000000,70.000000,70.000000,64.000000
mean,4.051840,0.326325,0.523958,113.018425,0.792652,0.601403,-0.513092
std,0.872816,0.067942,0.061437,30.278921,0.160838,0.489341,0.443231
min,1.433548,0.199955,0.415365,43.064862,0.337764,0.291925,-1.217767
25%,3.459409,0.288902,0.479818,98.724931,0.731112,0.372741,-0.737680
50%,4.220456,0.320433,0.522135,111.119363,0.826055,0.418904,-0.593993
75%,4.645040,0.358533,0.560221,136.615521,0.899290,0.525971,-0.369942
max,5.595620,0.564855,0.721354,164.164899,0.999292,2.693938,0.966857

Excel file on RGB_SKIP_RAW_NOISY.xlsx displayng data on sheet "Noisy Synthetic Image (Without "

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
Image_0,6.194813,0.352710,0.984375,36.940573,0.289730,6.697942,1.709779
Image_1,6.151599,0.469842,0.992188,32.893025,0.257985,6.637882,2.020249
Image_2,5.885550,0.707072,1.000000,41.694415,0.327015,5.969750,3.507889
Image_3,6.583340,0.436230,0.989583,50.037912,0.392454,7.762806,3.297557
Image_4,6.203204,0.394039,0.983073,36.262789,0.284414,6.489550,1.843965
...,...,...,...,...,...,...,...
Image_65,5.822196,0.636162,0.907552,22.336480,0.175188,5.794593,1.492653
Image_66,5.709247,0.504050,1.000000,40.087837,0.314414,5.305564,2.178323
Image_67,6.034442,0.641545,0.992188,27.836401,0.218325,6.210039,2.209407
Image_68,5.725933,0.630249,0.976562,30.854782,0.241998,5.666175,2.134142
Image_69,5.880326,0.589234,1.000000,40.206197,0.315343,5.456229,2.674647

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000
mean,6.024216,0.484939,0.976990,33.717025,0.264447,6.147684,2.040035
std,0.243077,0.092445,0.038345,7.329946,0.057490,0.590479,0.815032
min,5.514774,0.320292,0.847656,21.725787,0.170398,5.172422,0.720607
25%,5.860272,0.412670,0.975586,28.739069,0.225404,5.696488,1.500365
50%,6.033000,0.472455,0.996094,32.727724,0.256688,6.157409,1.988399
75%,6.191795,0.547518,1.000000,38.528095,0.302181,6.513807,2.309863
max,6.583340,0.707072,1.000000,56.239219,0.441092,7.762806,4.660380

Excel file on RGB_SKIP_RAW_NOISY.xlsx displayng data on sheet "S-Curve Correction.jpg"

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
Image_0,3.705901,0.213700,0.415365,7.316414,0.057384,0.526192,-0.017486
Image_1,3.457848,0.261683,0.321615,4.192068,0.032879,0.610137,-0.006820
Image_2,3.341702,0.428916,0.322917,5.980234,0.046904,0.437251,-0.025909
Image_3,4.307218,0.294068,0.433594,9.510295,0.074591,0.638498,-0.026514
Image_4,3.978084,0.279164,0.549479,9.309811,0.073018,0.801198,-0.014248
...,...,...,...,...,...,...,...
Image_65,4.765956,0.567699,0.440104,10.117513,0.079353,1.996681,0.094264
Image_66,3.177190,0.277732,0.305990,5.272359,0.041352,0.364361,-0.016263
Image_67,3.647459,0.441612,0.479167,4.958640,0.038891,0.659455,-0.018030
Image_68,4.255864,0.465797,0.360677,8.262628,0.064805,0.797828,-0.015098
Image_69,3.207167,0.364354,0.233073,4.074373,0.031956,0.394394,-0.011682

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000
mean,3.852861,0.318887,0.453144,7.505263,0.058865,0.805906,0.008842
std,0.617806,0.078964,0.107229,4.399729,0.034508,0.590528,0.082956
min,3.101747,0.197097,0.233073,3.266785,0.025622,0.364361,-0.050446
25%,3.440821,0.260371,0.362630,4.720842,0.037026,0.504843,-0.019981
50%,3.646853,0.304165,0.443359,6.011214,0.047147,0.565516,-0.013599
75%,4.234980,0.364672,0.519206,9.224261,0.072347,0.792239,-0.007965
max,5.872986,0.567699,0.716146,30.072526,0.235863,3.116711,0.495888

Excel file on RGB_SKIP_RAW_NOISY.xlsx displayng data on sheet "Saturation Fixing.jpg"

               AIE      ABWF      ACLF       AAL      LNPF        AG      VPMI
Image_0   3.596153  0.205957  0.313802  6.054917  0.047490  0.468716 -0.012066
Image_1   3.422150  0.268640  0.264323  3.935713  0.030868  0.557155 -0.006330
Image_2   3.237905  0.431179  0.252604  4.934312  0.038700  0.398643 -0.018109
Image_3   4.122619  0.282813  0.330729  7.949605  0.062350  0.557143 -0.020289
Image_4   3.840700  0.247913  0.414062  7.463421  0.058537  0.687282 -0.012486
...            ...       ...       ...       ...       ...       ...       ...
Image_65  4.429206  0.559544  0.338542  7.930680  0.062201  1.653311  0.037855
Image_66  3.145305  0.276130  0.242188  4.591491  0.036012  0.355233 -0.011310
Image_67  3.538632  0.426087  0.364583  4.448775  0.034892  0.596919 -0.014278
Image_68  3.971165  0.448699  0.279948  6.590227  0.051688  0.690932 -0.013752
Image_69  3.204861  0.356975  0.191406  3.826493  0.030012  0.368783 -0.009458

[70 rows x 7 columns]

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000
mean,3.718424,0.305436,0.344327,6.177008,0.048447,0.690624,-0.004643
std,0.498185,0.076008,0.072284,2.886254,0.022637,0.448829,0.027458
min,3.059575,0.193426,0.191406,3.245625,0.025456,0.355233,-0.035006
25%,3.378050,0.251784,0.282552,4.287079,0.033624,0.465889,-0.015802
50%,3.557849,0.283442,0.338542,5.227265,0.040998,0.507379,-0.011209
75%,3.982151,0.346409,0.393229,7.386526,0.057934,0.678060,-0.007214
max,5.431500,0.559544,0.514323,20.319940,0.159372,2.473512,0.139179

Excel file on RGB_SKIP_RAW_NOISY.xlsx displayng data on sheet "Unsharp Masking.jpg"

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
Image_0,4.802300,0.356650,0.539062,80.696351,0.632913,0.648640,-0.364934
Image_1,NaN,0.003906,0.420573,251.994929,0.023569,0.320023,NaN
Image_2,6.280968,0.434758,0.930990,197.948672,0.447461,3.529608,2.069801
Image_3,6.495072,0.455173,1.000000,204.695049,0.394549,3.489845,2.103274
Image_4,6.370246,0.461290,1.000000,207.927544,0.369196,5.445824,2.652727
...,...,...,...,...,...,...,...
Image_65,5.601525,0.538402,0.692708,69.275086,0.543334,4.024465,2.280163
Image_66,NaN,0.008000,0.591146,247.612566,0.057941,0.804679,NaN
Image_67,6.691186,0.485265,0.998698,214.932417,0.314256,7.328735,2.928333
Image_68,4.863054,0.438259,0.510417,68.963216,0.540888,1.367006,0.265379
Image_69,6.647154,0.158644,1.000000,224.375884,0.240189,4.698650,0.565400

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,62.000000,70.000000,70.000000,70.000000,70.000000,70.000000,62.000000
mean,6.031686,0.288860,0.824609,182.967877,0.338409,3.939377,1.456127
std,0.807700,0.187552,0.189301,69.649884,0.215345,4.549418,1.650589
min,3.783961,0.003906,0.420573,43.077687,0.002537,0.050829,-0.581077
25%,5.441317,0.049904,0.646484,98.762122,0.137055,0.944666,0.009406
50%,6.463840,0.366974,0.921224,208.671046,0.361961,3.139972,0.940403
75%,6.653632,0.452872,1.000000,237.525433,0.457021,4.968896,2.446134
max,6.776246,0.538402,1.000000,254.676523,0.780900,23.593377,6.551893

----------
Excel file on RGB_SKIP_RAW_NOISY_global.xlsx displayng data on sheet "After Contrast Conditional Enha"

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
Image_0,4.640563,0.327977,0.486979,80.656182,0.632598,0.418116,-0.589849
Image_1,NaN,0.003906,0.358073,254.225940,0.006071,0.029152,NaN
Image_2,NaN,0.448427,0.595052,207.785004,0.370314,0.757148,NaN
Image_3,NaN,0.423984,0.652344,210.534543,0.348749,0.819708,NaN
Image_4,NaN,0.407427,0.658854,218.171846,0.288848,1.074549,NaN
...,...,...,...,...,...,...,...
Image_65,5.247440,0.564855,0.566406,69.299081,0.543522,2.084321,0.966857
Image_66,NaN,0.003966,0.359375,253.068437,0.015150,0.070995,NaN
Image_67,NaN,0.469095,0.585938,228.559119,0.207379,0.881881,NaN
Image_68,4.593251,0.417556,0.436198,68.973689,0.540970,0.691748,-0.240627
Image_69,NaN,0.053438,0.481771,245.109100,0.077576,0.348447,NaN

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,24.000000,70.000000,70.000000,70.000000,70.000000,70.000000,24.000000
mean,4.755006,0.246557,0.539658,192.412764,0.264355,0.657483,-0.090818
std,0.443595,0.187061,0.124407,74.915236,0.243274,0.594436,0.481238
min,3.909649,0.003906,0.308594,43.064862,0.000151,0.001617,-0.940539
25%,4.525457,0.012527,0.437826,98.724931,0.031563,0.133986,-0.427613
50%,4.683419,0.308802,0.537760,222.783276,0.252680,0.487710,-0.214124
75%,5.094312,0.406718,0.631510,250.975663,0.407273,0.898855,0.279383
max,5.595620,0.564855,0.851562,254.980726,0.780635,2.693938,0.966857

Excel file on RGB_SKIP_RAW_NOISY_global.xlsx displayng data on sheet "Denoised Image.jpg"

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
Image_0,6.157282,0.332340,0.897135,36.033726,0.282617,4.416254,1.111771
Image_1,6.121343,0.465171,0.958333,32.055303,0.251414,5.495777,1.686569
Image_2,5.840025,0.731224,1.000000,40.954077,0.321208,3.826277,2.655490
Image_3,6.575065,0.436488,0.940104,49.172204,0.385664,4.758445,2.341718
Image_4,6.177942,0.376383,0.932292,35.582095,0.279075,5.266736,1.450104
...,...,...,...,...,...,...,...
Image_65,5.780952,0.650768,0.761719,21.536327,0.168912,4.866747,1.105044
Image_66,5.656953,0.495813,0.972656,39.409046,0.309091,3.275310,1.443299
Image_67,6.002841,0.658970,0.953125,27.044673,0.212115,5.191004,1.900170
Image_68,5.670994,0.641774,0.880208,30.149903,0.236470,4.147815,1.554728
Image_69,5.829930,0.599897,1.000000,39.458162,0.309476,3.720755,2.051691

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000
mean,5.988511,0.479916,0.934654,32.924919,0.258235,4.556496,1.567464
std,0.258799,0.103874,0.078990,7.328949,0.057482,0.510981,0.659050
min,5.433921,0.301389,0.688802,20.977633,0.164530,3.275310,0.443784
25%,5.815491,0.397012,0.902995,27.945837,0.219183,4.218913,1.106726
50%,5.995712,0.464255,0.962240,31.895182,0.250158,4.502800,1.503799
75%,6.161026,0.551142,0.999023,37.763447,0.296184,4.855629,1.881460
max,6.575065,0.731224,1.000000,55.475297,0.435100,6.137018,3.497948

Excel file on RGB_SKIP_RAW_NOISY_global.xlsx displayng data on sheet "Grayness Index.jpg"

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
Image_0,3.475251,0.240038,0.255208,5.464973,0.042863,0.547109,-0.007940
Image_1,0.676156,0.003906,0.115885,0.599921,0.004705,0.206812,-0.000003
Image_2,4.081554,0.525064,0.203125,7.078552,0.055518,1.268163,0.008283
Image_3,4.115907,0.356361,0.319010,7.001083,0.054910,1.089742,0.003186
Image_4,4.132118,0.376323,0.279948,7.478637,0.058656,1.460734,0.013959
...,...,...,...,...,...,...,...
Image_65,3.638622,0.419682,0.259115,4.896463,0.038404,0.855478,-0.003422
Image_66,1.517517,0.023281,0.223958,1.467772,0.011512,0.534359,-0.000082
Image_67,5.328283,0.416751,0.593750,77.609865,0.608705,2.789955,1.187976
Image_68,3.492365,0.421468,0.246094,5.449033,0.042738,0.634918,-0.010145
Image_69,6.315672,0.283360,1.000000,198.075792,0.446464,6.759601,2.202783

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000
mean,3.764849,0.268275,0.426618,34.231137,0.237846,2.800855,0.924055
std,1.670162,0.163766,0.285628,47.610228,0.304989,5.203016,2.341620
min,0.117084,0.003906,0.115885,0.066850,0.000524,0.031313,-0.010145
25%,2.861397,0.135813,0.246094,3.802068,0.029820,0.600189,-0.000258
50%,3.861851,0.298828,0.279948,5.899174,0.046268,1.100373,0.003039
75%,5.235028,0.410693,0.590495,72.022167,0.547399,2.441149,0.983309
max,6.806978,0.525064,1.000000,198.075792,0.920619,29.283661,12.982075

Excel file on RGB_SKIP_RAW_NOISY_global.xlsx displayng data on sheet "Unsharp Masking.jpg"

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
Image_0,4.802300,0.356650,0.539062,80.696351,0.632913,0.648640,-0.364934
Image_1,NaN,0.003906,0.420573,251.994929,0.023569,0.320023,NaN
Image_2,6.280968,0.434758,0.930990,197.948672,0.447461,3.529608,2.069801
Image_3,6.495072,0.455173,1.000000,204.695049,0.394549,3.489845,2.103274
Image_4,6.370246,0.461290,1.000000,207.927544,0.369196,5.445824,2.652727
...,...,...,...,...,...,...,...
Image_65,5.601525,0.538402,0.692708,69.275086,0.543334,4.024465,2.280163
Image_66,NaN,0.008000,0.591146,247.612566,0.057941,0.804679,NaN
Image_67,6.691186,0.485265,0.998698,214.932417,0.314256,7.328735,2.928333
Image_68,4.863054,0.438259,0.510417,68.963216,0.540888,1.367006,0.265379
Image_69,6.647154,0.158644,1.000000,224.375884,0.240189,4.698650,0.565400

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,62.000000,70.000000,70.000000,70.000000,70.000000,70.000000,62.000000
mean,6.031686,0.288860,0.824609,182.967877,0.338409,3.939377,1.456127
std,0.807700,0.187552,0.189301,69.649884,0.215345,4.549418,1.650589
min,3.783961,0.003906,0.420573,43.077687,0.002537,0.050829,-0.581077
25%,5.441317,0.049904,0.646484,98.762122,0.137055,0.944666,0.009406
50%,6.463840,0.366974,0.921224,208.671046,0.361961,3.139972,0.940403
75%,6.653632,0.452872,1.000000,237.525433,0.457021,4.968896,2.446134
max,6.776246,0.538402,1.000000,254.676523,0.780900,23.593377,6.551893

----------
Excel file on RGB_WITH_RAW_CLEAN.xlsx displayng data on sheet "Clean Synthetic Image (Raw Proc"

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
Image_0,6.829791e-07,0.003918,0.005208,0.025799,0.000202,0.000818,-2.892353e-14
Image_1,2.107509e-03,0.003905,0.007812,0.023898,0.000187,0.002256,-1.059534e-10
Image_2,0.000000e+00,0.003851,0.003906,0.034265,0.000269,0.000760,0.000000e+00
Image_3,0.000000e+00,0.003927,0.003906,0.036653,0.000287,0.001225,0.000000e+00
Image_4,0.000000e+00,0.003909,0.003906,0.022784,0.000179,0.001230,0.000000e+00
...,...,...,...,...,...,...,...
Image_65,0.000000e+00,0.003880,0.003906,0.012855,0.000101,0.000670,0.000000e+00
Image_66,2.298920e-05,0.003898,0.005208,0.030751,0.000241,0.001072,-1.110590e-12
Image_67,6.829791e-07,0.003856,0.005208,0.017028,0.000134,0.001258,-1.764834e-14
Image_68,0.000000e+00,0.003884,0.003906,0.021290,0.000167,0.000750,0.000000e+00
Image_69,2.249354e-05,0.003869,0.005208,0.034280,0.000269,0.000864,-1.240221e-12

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,7.000000e+01,70.000000,70.000000,70.000000,70.000000,70.000000,7.000000e+01
mean,3.497706e-04,0.003896,0.004855,0.023683,0.000186,0.001138,-1.709108e-11
std,1.811567e-03,0.000029,0.001061,0.007175,0.000056,0.000424,9.500061e-11
min,0.000000e+00,0.003805,0.003906,0.012621,0.000099,0.000550,-7.832701e-10
25%,0.000000e+00,0.003893,0.003906,0.019110,0.000150,0.000819,-1.207814e-12
50%,6.829791e-07,0.003903,0.005208,0.022886,0.000179,0.001017,-1.887650e-14
75%,2.180204e-05,0.003910,0.005208,0.027990,0.000220,0.001393,0.000000e+00
max,1.481331e-02,0.003947,0.007812,0.044525,0.000349,0.002478,0.000000e+00

Excel file on RGB_WITH_RAW_CLEAN.xlsx displayng data on sheet "Conditional Contrast Correction"

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
Image_0,4.025451,0.058931,0.458333,14.030059,0.110040,0.155109,-0.032168
Image_1,NaN,0.003906,0.417969,254.882396,0.000922,0.004800,NaN
Image_2,3.683977,0.501455,0.889323,17.404376,0.136505,0.158902,-0.595146
Image_3,5.226499,0.126868,0.707031,21.910083,0.171844,0.264036,-0.154777
Image_4,4.519089,0.062357,0.920573,14.480048,0.113569,0.279792,-0.054137
...,...,...,...,...,...,...,...
Image_65,3.838487,0.601963,0.971354,10.882918,0.085356,0.227696,-0.408982
Image_66,3.235888,0.072424,0.756510,35.697094,0.279977,0.132454,-0.144765
Image_67,3.809290,0.432793,0.893229,8.898074,0.069789,0.287056,-0.185050
Image_68,3.459035,0.374315,0.976562,16.552311,0.129822,0.241063,-0.336920
Image_69,3.583064,0.259405,0.743490,15.970596,0.125260,0.137941,-0.247378

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,68.000000,70.000000,70.000000,70.000000,70.000000,70.000000,68.000000
mean,3.697419,0.129456,0.789881,28.600703,0.179557,0.215954,-0.128465
std,0.668743,0.163186,0.186240,39.896401,0.159477,0.093209,0.173971
min,2.056818,0.003906,0.305990,5.304425,0.000922,0.004800,-0.818229
25%,3.333746,0.017201,0.648112,10.911787,0.084070,0.157069,-0.162285
50%,3.677872,0.057170,0.876953,16.261453,0.120255,0.205483,-0.051193
75%,4.092683,0.166969,0.932943,21.751212,0.166453,0.269962,-0.013822
max,5.226499,0.625611,0.984375,254.882396,0.769592,0.495121,-0.001037

Excel file on RGB_WITH_RAW_CLEAN.xlsx displayng data on sheet "Contrast Fixing Image.jpg"

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
Image_0,4.019969,0.007730,0.505208,10.783306,0.084575,0.110738,-0.004215
Image_1,3.433082,0.016696,0.960938,5.433820,0.042618,0.283340,-0.004271
Image_2,3.616935,0.578125,0.968750,16.213170,0.127162,0.136680,-0.739579
Image_3,5.351252,0.119835,0.725260,23.094043,0.181130,0.223929,-0.181866
Image_4,4.643474,0.034652,0.976562,16.021321,0.125657,0.264386,-0.037897
...,...,...,...,...,...,...,...
Image_65,3.746863,0.605334,0.989583,11.638626,0.091283,0.217097,-0.451478
Image_66,3.277714,0.109053,0.929688,10.638276,0.083437,0.105003,-0.090155
Image_67,4.017614,0.475016,0.975260,10.061466,0.078913,0.303905,-0.252376
Image_68,3.446172,0.448282,0.989583,17.293771,0.135637,0.220474,-0.452314
Image_69,3.535479,0.402343,0.979167,12.215588,0.095809,0.112607,-0.420439

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000
mean,3.811826,0.152635,0.932552,12.812263,0.100488,0.222537,-0.126848
std,0.569808,0.192459,0.095412,6.188747,0.048539,0.092109,0.196883
min,2.480965,0.003759,0.505208,3.368252,0.026418,0.078593,-0.969772
25%,3.450759,0.014960,0.924479,9.085586,0.071259,0.147429,-0.114544
50%,3.726941,0.053781,0.970052,11.541608,0.090522,0.215999,-0.036769
75%,4.144951,0.239069,0.981445,16.206236,0.127108,0.281580,-0.009321
max,5.351252,0.660790,1.000000,36.158452,0.283596,0.473726,-0.000947

Excel file on RGB_WITH_RAW_CLEAN.xlsx displayng data on sheet "Denoised Image.jpg"

               AIE      ABWF      ACLF       AAL      LNPF        AG      VPMI
Image_0   3.567124  0.006822  0.291667  6.180444  0.048474  0.057939 -0.001414
Image_1   3.636557  0.012731  0.944010  5.541902  0.043466  0.240936 -0.003901
Image_2   3.523272  0.539604  0.494792  8.439592  0.066193  0.069412 -0.239644
Image_3   4.290638  0.085872  0.298177  8.805888  0.069066  0.083486 -0.027182
Image_4   3.603532  0.018060  0.358073  5.486649  0.043033  0.078317 -0.003685
...            ...       ...       ...       ...       ...       ...       ...
Image_65  2.691843  0.296923  0.246094  2.846767  0.022328  0.045634 -0.019560
Image_66  3.209023  0.091788  0.667969  7.535031  0.059098  0.067764 -0.045154
Image_67  3.142610  0.371472  0.460938  3.914270  0.030700  0.104516 -0.053824
Image_68  2.986990  0.313752  0.279948  5.129459  0.040231  0.066071 -0.041374
Image_69  3.410993  0.328563  0.734375  8.382077  0.065742  0.072683 -0.204648

[70 rows x 7 columns]

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000
mean,3.344222,0.124450,0.508650,5.637701,0.044217,0.101197,-0.041056
std,0.439578,0.170215,0.216017,1.805491,0.014161,0.063714,0.068505
min,2.499192,0.003718,0.180990,2.846767,0.022328,0.035284,-0.334007
25%,3.000093,0.005970,0.335938,4.516148,0.035421,0.064681,-0.044209
50%,3.335179,0.043185,0.475260,5.438482,0.042655,0.082548,-0.011102
75%,3.641265,0.193951,0.660807,6.654576,0.052193,0.115436,-0.001197
max,4.572984,0.644896,1.000000,10.868919,0.085246,0.328320,-0.000279

Excel file on RGB_WITH_RAW_CLEAN.xlsx displayng data on sheet "Global Mean Contrast (Sat. Fix "

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
Image_0,3.369001,0.013805,0.230469,5.385164,0.042237,0.078706,-0.001660
Image_1,1.818580,0.016016,0.264323,0.987828,0.007748,0.115079,-0.000186
Image_2,3.498389,0.454121,0.411458,8.685904,0.068125,0.090329,-0.154466
Image_3,4.760857,0.081546,0.411458,15.346794,0.120367,0.159568,-0.050910
Image_4,4.333860,0.063629,0.584635,11.851322,0.092952,0.204801,-0.034283
...,...,...,...,...,...,...,...
Image_65,3.742491,0.557028,0.674479,10.266212,0.080519,0.183265,-0.277151
Image_66,2.778708,0.049158,0.286458,3.926223,0.030794,0.063608,-0.004789
Image_67,3.704205,0.477736,0.567708,7.456176,0.058480,0.221271,-0.127849
Image_68,3.654547,0.395252,0.604167,13.522415,0.106058,0.163465,-0.241846
Image_69,2.954886,0.269075,0.324219,4.641824,0.036406,0.067702,-0.036457

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000
mean,3.325415,0.118260,0.460212,8.313955,0.065207,0.147604,-0.039479
std,0.824377,0.159646,0.148819,6.181517,0.048482,0.062503,0.070023
min,1.425379,0.003843,0.173177,0.876585,0.006875,0.049799,-0.277151
25%,2.916026,0.015067,0.358073,4.692897,0.036807,0.098488,-0.035104
50%,3.478794,0.045013,0.457031,6.784581,0.053212,0.131242,-0.007381
75%,3.859933,0.128325,0.581706,11.301744,0.088641,0.183075,-0.002588
max,4.974484,0.590023,0.757812,32.565131,0.255413,0.295287,-0.000069

Excel file on RGB_WITH_RAW_CLEAN.xlsx displayng data on sheet "Grayness Index.jpg"

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
Image_0,3.082945,0.175961,0.223958,5.229208,0.041013,0.165911,-0.012913
Image_1,0.223051,0.003906,0.285156,0.144377,0.001132,0.063276,-0.000001
Image_2,3.105398,0.389338,0.424479,7.525620,0.059024,0.181303,-0.074626
Image_3,4.574961,0.077780,0.514323,13.615160,0.106786,0.370237,-0.028015
Image_4,4.122313,0.032509,0.825521,11.159668,0.087527,0.472863,-0.010462
...,...,...,...,...,...,...,...
Image_65,3.933293,0.587933,0.997396,14.871772,0.116641,0.673399,-0.153474
Image_66,1.599488,0.070876,0.158854,1.187841,0.009316,0.082579,-0.000604
Image_67,3.399104,0.435754,0.772135,6.355974,0.049851,0.429349,-0.069543
Image_68,3.381934,0.451254,1.000000,26.610270,0.208708,1.538111,0.197847
Image_69,2.794580,0.135079,0.346354,5.329047,0.041796,0.148567,-0.015032

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000
mean,3.029222,0.122966,0.599870,11.435048,0.089687,0.768928,0.015524
std,0.936503,0.149605,0.284602,14.142994,0.110925,1.641738,0.154845
min,0.223051,0.003906,0.158854,0.144377,0.001132,0.049645,-0.196718
25%,2.506466,0.021249,0.306315,3.646356,0.028599,0.164011,-0.012034
50%,3.086473,0.060131,0.613281,6.699796,0.052547,0.288206,-0.003454
75%,3.670221,0.167314,0.838867,14.100881,0.110595,0.495632,-0.000467
max,5.203634,0.587933,1.000000,65.551557,0.514130,10.061021,1.092810

Excel file on RGB_WITH_RAW_CLEAN.xlsx displayng data on sheet "Histogram Stretched.jpg"

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
Image_0,4.025451,0.058931,0.458333,14.030059,0.110040,0.155109,-0.032168
Image_1,0.764537,0.011878,0.454427,127.469616,0.999762,0.112446,-0.013007
Image_2,3.683977,0.501455,0.889323,17.404376,0.136505,0.158902,-0.595146
Image_3,5.226499,0.126868,0.707031,21.910083,0.171844,0.264036,-0.154777
Image_4,4.519089,0.062357,0.920573,14.480048,0.113569,0.279792,-0.054137
...,...,...,...,...,...,...,...
Image_65,3.838487,0.601963,0.971354,10.882918,0.085356,0.227696,-0.408982
Image_66,3.235888,0.072424,0.756510,35.697094,0.279977,0.132454,-0.144765
Image_67,3.809290,0.432793,0.893229,8.898074,0.069789,0.287056,-0.185050
Image_68,3.459035,0.374315,0.976562,16.552311,0.129822,0.241063,-0.336920
Image_69,3.583064,0.259405,0.743490,15.970596,0.125260,0.137941,-0.247378

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000
mean,3.635004,0.127965,0.789751,25.361741,0.198916,0.216332,-0.126960
std,0.764761,0.163365,0.186382,25.111523,0.196953,0.091876,0.171991
min,0.764537,0.003906,0.305990,5.304425,0.041603,0.061624,-0.818229
25%,3.237557,0.017201,0.648112,10.911787,0.085583,0.157069,-0.155586
50%,3.667245,0.054223,0.876953,16.261453,0.127541,0.205483,-0.051193
75%,4.086236,0.166969,0.932943,21.751212,0.170598,0.269962,-0.013313
max,5.226499,0.625611,0.984375,127.469616,0.999762,0.495121,-0.001037

Excel file on RGB_WITH_RAW_CLEAN.xlsx displayng data on sheet "S-Curve Correction.jpg"

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
Image_0,3.605100,0.007015,0.334635,7.116646,0.055817,0.108699,-0.001512
Image_1,1.954273,0.018682,0.421875,1.186033,0.009302,0.142293,-0.000403
Image_2,3.644584,0.480602,0.695312,12.355876,0.096909,0.124949,-0.354148
Image_3,5.253827,0.103456,0.674479,22.592276,0.177194,0.255500,-0.127882
Image_4,4.644507,0.091568,0.979167,17.433882,0.136736,0.313821,-0.095204
...,...,...,...,...,...,...,...
Image_65,3.957854,0.584705,1.000000,14.670447,0.115062,0.280124,-0.488843
Image_66,2.944542,0.048336,0.454427,5.113789,0.040108,0.088162,-0.009089
Image_67,3.865498,0.474793,0.950521,10.286858,0.080681,0.320815,-0.230854
Image_68,3.511593,0.421352,1.000000,20.084477,0.157525,0.261056,-0.451603
Image_69,3.121063,0.258052,0.527344,6.347586,0.049785,0.094939,-0.071825

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000
mean,3.483647,0.123027,0.743769,12.017268,0.094253,0.218635,-0.078193
std,0.867342,0.163085,0.229824,9.687271,0.075979,0.108936,0.135387
min,1.433237,0.003906,0.268229,1.109587,0.008703,0.061682,-0.566829
25%,3.032087,0.018156,0.564779,6.353103,0.049828,0.132278,-0.068735
50%,3.629510,0.048637,0.779948,9.362397,0.073431,0.187541,-0.016171
75%,3.946069,0.133021,0.967122,16.473842,0.129207,0.284552,-0.004774
max,5.253827,0.616894,1.000000,51.466578,0.403659,0.498811,-0.000141

Excel file on RGB_WITH_RAW_CLEAN.xlsx displayng data on sheet "Saturation Fixing.jpg"

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
Image_0,3.358870,0.006558,0.266927,5.505273,0.043179,0.092675,-0.000871
Image_1,1.962373,0.018683,0.328125,1.169851,0.009175,0.144097,-0.000308
Image_2,3.398925,0.499638,0.502604,8.636505,0.067737,0.100564,-0.191593
Image_3,4.816880,0.107178,0.492188,15.418088,0.120926,0.199911,-0.071366
Image_4,4.407363,0.031505,0.723958,12.034266,0.094386,0.251297,-0.018905
...,...,...,...,...,...,...,...
Image_65,3.829655,0.586722,0.832031,10.266952,0.080525,0.225947,-0.323059
Image_66,2.594465,0.072123,0.350260,3.900917,0.030595,0.079872,-0.007311
Image_67,3.611854,0.418922,0.703125,7.308722,0.057323,0.261198,-0.118116
Image_68,3.550178,0.411488,0.738281,13.360476,0.104788,0.195560,-0.266076
Image_69,2.863137,0.281645,0.395833,4.758925,0.037325,0.086616,-0.042047

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000
mean,3.318468,0.120777,0.563486,8.383070,0.065750,0.177646,-0.044151
std,0.795081,0.164449,0.181734,6.079487,0.047682,0.077179,0.079575
min,1.518656,0.003759,0.212240,1.060608,0.008318,0.061498,-0.323059
25%,2.866284,0.011891,0.433919,4.781865,0.037505,0.116001,-0.035756
50%,3.418652,0.045999,0.567708,6.923579,0.054303,0.155768,-0.007615
75%,3.829258,0.138783,0.718750,11.385735,0.089300,0.225298,-0.002989
max,5.023791,0.623048,0.920573,32.263675,0.253048,0.367501,-0.000100

Excel file on RGB_WITH_RAW_CLEAN.xlsx displayng data on sheet "Unsharp Masking.jpg"

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
Image_0,4.071659,0.064119,0.470052,14.028522,0.110028,0.291205,-0.024033
Image_1,6.388304,0.003906,0.932292,254.401735,0.004692,0.178139,-0.000272
Image_2,3.770887,0.503663,0.914062,17.399388,0.136466,0.301940,-0.409301
Image_3,5.293028,0.131265,0.781250,21.925036,0.171961,0.520814,-0.087849
Image_4,4.560130,0.064373,0.986979,14.523290,0.113908,0.558338,-0.027748
...,...,...,...,...,...,...,...
Image_65,3.908743,0.596284,0.985677,10.916930,0.085623,0.430814,-0.238970
Image_66,3.280735,0.073396,0.889323,35.687644,0.279903,0.251437,-0.119383
Image_67,3.856833,0.436204,0.962240,8.950908,0.070203,0.540115,-0.100994
Image_68,3.526653,0.368235,0.998698,16.582801,0.130061,0.439194,-0.200237
Image_69,3.619845,0.259478,0.773438,15.970867,0.125262,0.246840,-0.183667

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000
mean,3.836746,0.131319,0.849033,28.605905,0.179750,0.409054,-0.090526
std,0.796169,0.162393,0.170186,39.837294,0.159376,0.174659,0.131819
min,2.128745,0.003906,0.355469,5.287499,0.004692,0.102941,-0.632050
25%,3.424781,0.019999,0.729492,10.945680,0.084255,0.295881,-0.114786
50%,3.767389,0.063250,0.927083,16.276834,0.120215,0.381784,-0.028348
75%,4.188887,0.164859,0.977539,21.765034,0.166542,0.518203,-0.007475
max,6.476592,0.622711,1.000000,254.401735,0.769496,0.888010,-0.000272

----------
Excel file on RGB_WITH_RAW_CLEAN_global.xlsx displayng data on sheet "After Contrast Conditional Enha"

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
Image_0,4.025451,0.058931,0.458333,14.030059,0.110040,0.155109,-0.032168
Image_1,NaN,0.003906,0.417969,254.882396,0.000922,0.004800,NaN
Image_2,3.683977,0.501455,0.889323,17.404376,0.136505,0.158902,-0.595146
Image_3,5.226499,0.126868,0.707031,21.910083,0.171844,0.264036,-0.154777
Image_4,4.519089,0.062357,0.920573,14.480048,0.113569,0.279792,-0.054137
...,...,...,...,...,...,...,...
Image_65,3.838487,0.601963,0.971354,10.882918,0.085356,0.227696,-0.408982
Image_66,3.235888,0.072424,0.756510,35.697094,0.279977,0.132454,-0.144765
Image_67,3.809290,0.432793,0.893229,8.898074,0.069789,0.287056,-0.185050
Image_68,3.459035,0.374315,0.976562,16.552311,0.129822,0.241063,-0.336920
Image_69,3.583064,0.259405,0.743490,15.970596,0.125260,0.137941,-0.247378

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,68.000000,70.000000,70.000000,70.000000,70.000000,70.000000,68.000000
mean,3.697419,0.129456,0.789881,28.600703,0.179557,0.215954,-0.128465
std,0.668743,0.163186,0.186240,39.896401,0.159477,0.093209,0.173971
min,2.056818,0.003906,0.305990,5.304425,0.000922,0.004800,-0.818229
25%,3.333746,0.017201,0.648112,10.911787,0.084070,0.157069,-0.162285
50%,3.677872,0.057170,0.876953,16.261453,0.120255,0.205483,-0.051193
75%,4.092683,0.166969,0.932943,21.751212,0.166453,0.269962,-0.013822
max,5.226499,0.625611,0.984375,254.882396,0.769592,0.495121,-0.001037

Excel file on RGB_WITH_RAW_CLEAN_global.xlsx displayng data on sheet "Denoised Image.jpg"

               AIE      ABWF      ACLF       AAL      LNPF        AG      VPMI
Image_0   3.567124  0.006822  0.291667  6.180444  0.048474  0.057939 -0.001414
Image_1   3.636557  0.012731  0.944010  5.541902  0.043466  0.240936 -0.003901
Image_2   3.523272  0.539604  0.494792  8.439592  0.066193  0.069412 -0.239644
Image_3   4.290638  0.085872  0.298177  8.805888  0.069066  0.083486 -0.027182
Image_4   3.603532  0.018060  0.358073  5.486649  0.043033  0.078317 -0.003685
...            ...       ...       ...       ...       ...       ...       ...
Image_65  2.691843  0.296923  0.246094  2.846767  0.022328  0.045634 -0.019560
Image_66  3.209023  0.091788  0.667969  7.535031  0.059098  0.067764 -0.045154
Image_67  3.142610  0.371472  0.460938  3.914270  0.030700  0.104516 -0.053824
Image_68  2.986990  0.313752  0.279948  5.129459  0.040231  0.066071 -0.041374
Image_69  3.410993  0.328563  0.734375  8.382077  0.065742  0.072683 -0.204648

[70 rows x 7 columns]

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000
mean,3.344222,0.124450,0.508650,5.637701,0.044217,0.101197,-0.041056
std,0.439578,0.170215,0.216017,1.805491,0.014161,0.063714,0.068505
min,2.499192,0.003718,0.180990,2.846767,0.022328,0.035284,-0.334007
25%,3.000093,0.005970,0.335938,4.516148,0.035421,0.064681,-0.044209
50%,3.335179,0.043185,0.475260,5.438482,0.042655,0.082548,-0.011102
75%,3.641265,0.193951,0.660807,6.654576,0.052193,0.115436,-0.001197
max,4.572984,0.644896,1.000000,10.868919,0.085246,0.328320,-0.000279

Excel file on RGB_WITH_RAW_CLEAN_global.xlsx displayng data on sheet "Grayness Index.jpg"

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
Image_0,3.082945,0.175961,0.223958,5.229208,0.041013,0.165911,-0.012913
Image_1,0.223051,0.003906,0.285156,0.144377,0.001132,0.063276,-0.000001
Image_2,3.105398,0.389338,0.424479,7.525620,0.059024,0.181303,-0.074626
Image_3,4.574961,0.077780,0.514323,13.615160,0.106786,0.370237,-0.028015
Image_4,4.122313,0.032509,0.825521,11.159668,0.087527,0.472863,-0.010462
...,...,...,...,...,...,...,...
Image_65,3.933293,0.587933,0.997396,14.871772,0.116641,0.673399,-0.153474
Image_66,1.599488,0.070876,0.158854,1.187841,0.009316,0.082579,-0.000604
Image_67,3.399104,0.435754,0.772135,6.355974,0.049851,0.429349,-0.069543
Image_68,3.381934,0.451254,1.000000,26.610270,0.208708,1.538111,0.197847
Image_69,2.794580,0.135079,0.346354,5.329047,0.041796,0.148567,-0.015032

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000
mean,3.029222,0.122966,0.599870,11.435048,0.089687,0.768928,0.015524
std,0.936503,0.149605,0.284602,14.142994,0.110925,1.641738,0.154845
min,0.223051,0.003906,0.158854,0.144377,0.001132,0.049645,-0.196718
25%,2.506466,0.021249,0.306315,3.646356,0.028599,0.164011,-0.012034
50%,3.086473,0.060131,0.613281,6.699796,0.052547,0.288206,-0.003454
75%,3.670221,0.167314,0.838867,14.100881,0.110595,0.495632,-0.000467
max,5.203634,0.587933,1.000000,65.551557,0.514130,10.061021,1.092810

Excel file on RGB_WITH_RAW_CLEAN_global.xlsx displayng data on sheet "Unsharp Masking.jpg"

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
Image_0,4.071659,0.064119,0.470052,14.028522,0.110028,0.291205,-0.024033
Image_1,6.388304,0.003906,0.932292,254.401735,0.004692,0.178139,-0.000272
Image_2,3.770887,0.503663,0.914062,17.399388,0.136466,0.301940,-0.409301
Image_3,5.293028,0.131265,0.781250,21.925036,0.171961,0.520814,-0.087849
Image_4,4.560130,0.064373,0.986979,14.523290,0.113908,0.558338,-0.027748
...,...,...,...,...,...,...,...
Image_65,3.908743,0.596284,0.985677,10.916930,0.085623,0.430814,-0.238970
Image_66,3.280735,0.073396,0.889323,35.687644,0.279903,0.251437,-0.119383
Image_67,3.856833,0.436204,0.962240,8.950908,0.070203,0.540115,-0.100994
Image_68,3.526653,0.368235,0.998698,16.582801,0.130061,0.439194,-0.200237
Image_69,3.619845,0.259478,0.773438,15.970867,0.125262,0.246840,-0.183667

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000
mean,3.836746,0.131319,0.849033,28.605905,0.179750,0.409054,-0.090526
std,0.796169,0.162393,0.170186,39.837294,0.159376,0.174659,0.131819
min,2.128745,0.003906,0.355469,5.287499,0.004692,0.102941,-0.632050
25%,3.424781,0.019999,0.729492,10.945680,0.084255,0.295881,-0.114786
50%,3.767389,0.063250,0.927083,16.276834,0.120215,0.381784,-0.028348
75%,4.188887,0.164859,0.977539,21.765034,0.166542,0.518203,-0.007475
max,6.476592,0.622711,1.000000,254.401735,0.769496,0.888010,-0.000272

----------
Excel file on RGB_WITH_RAW_NOISY.xlsx displayng data on sheet "Conditional Contrast Correction"

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
Image_0,4.032936,0.080534,0.446615,13.691171,0.107382,0.316624,-0.025843
Image_1,NaN,0.003906,0.361979,254.934212,0.000516,0.002262,NaN
Image_2,3.653871,0.531913,0.875000,16.684161,0.130856,0.276137,-0.413144
Image_3,5.338346,0.172126,0.694010,20.867912,0.163670,0.536193,-0.093850
Image_4,4.542405,0.055258,0.929688,14.291530,0.112090,0.451825,-0.029980
...,...,...,...,...,...,...,...
Image_65,4.113420,0.599530,0.975260,10.134804,0.079489,0.595037,-0.143183
Image_66,3.111492,0.076470,0.739583,36.818284,0.288771,0.233327,-0.106692
Image_67,3.774421,0.499559,0.864583,7.722538,0.060569,0.405730,-0.128501
Image_68,3.588793,0.412566,0.944010,15.495420,0.121533,0.445860,-0.197953
Image_69,3.434912,0.297487,0.802083,18.110951,0.142047,0.272914,-0.218114

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,62.000000,70.000000,70.000000,70.000000,70.000000,70.000000,62.000000
mean,3.841562,0.138901,0.767708,45.207090,0.143902,0.372892,-0.091501
std,0.618609,0.170395,0.209319,73.842539,0.120503,0.178429,0.127270
min,2.194631,0.003906,0.192708,5.312211,0.000031,0.000326,-0.567342
25%,3.500724,0.018160,0.644206,10.529559,0.075348,0.273720,-0.115648
50%,3.790738,0.054357,0.859375,16.656753,0.110900,0.344727,-0.036224
75%,4.170350,0.177680,0.929362,27.405177,0.153921,0.478005,-0.014208
max,5.338346,0.639044,0.981771,254.996075,0.554102,0.787359,-0.001625

Excel file on RGB_WITH_RAW_NOISY.xlsx displayng data on sheet "Contrast Fixing Image.jpg"

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
Image_0,3.962079,0.006830,0.477865,9.733618,0.076342,0.216871,-0.002177
Image_1,3.389423,0.018898,0.906250,4.997567,0.039197,0.333445,-0.003605
Image_2,3.577016,0.554106,0.958333,15.587058,0.122251,0.230536,-0.491577
Image_3,5.354234,0.140983,0.704427,21.599991,0.169412,0.418687,-0.113150
Image_4,4.397847,0.020994,0.984375,15.129881,0.118666,0.402888,-0.014145
...,...,...,...,...,...,...,...
Image_65,3.970475,0.617108,0.981771,10.447631,0.081942,0.512885,-0.189880
Image_66,3.304111,0.108280,0.899740,9.967557,0.078177,0.165429,-0.065321
Image_67,3.926849,0.498036,0.984375,8.926889,0.070015,0.425983,-0.165944
Image_68,3.358995,0.424127,0.967448,16.370675,0.128397,0.379120,-0.247623
Image_69,3.569578,0.424721,0.989583,11.583164,0.090848,0.196032,-0.320415

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000
mean,3.772168,0.153741,0.917653,11.869994,0.093098,0.353924,-0.080744
std,0.589460,0.192931,0.102169,6.018305,0.047202,0.139176,0.128242
min,2.348500,0.003870,0.477865,2.856810,0.022406,0.125698,-0.689529
25%,3.369810,0.014740,0.906250,8.139191,0.063837,0.251794,-0.085570
50%,3.634551,0.058765,0.953776,10.253659,0.080421,0.338393,-0.023631
75%,4.105025,0.241282,0.980794,15.835882,0.124203,0.424159,-0.004066
max,5.354234,0.668963,1.000000,34.231196,0.268480,0.711032,-0.000572

Excel file on RGB_WITH_RAW_NOISY.xlsx displayng data on sheet "Denoised Image.jpg"

               AIE      ABWF      ACLF       AAL      LNPF        AG      VPMI
Image_0   3.696319  0.013029  0.291667  5.815619  0.045613  0.110201 -0.002039
Image_1   3.688567  0.071099  0.891927  5.237399  0.041078  0.291139 -0.017105
Image_2   3.604320  0.581816  0.500000  8.106173  0.063578  0.114940 -0.208058
Image_3   4.384958  0.094717  0.302083  8.520022  0.066824  0.154686 -0.022575
Image_4   3.588429  0.045575  0.329427  5.083374  0.039870  0.123162 -0.006490
...            ...       ...       ...       ...       ...       ...       ...
Image_65  2.904792  0.394212  0.213542  2.527949  0.019827  0.091922 -0.016695
Image_66  3.391094  0.145107  0.652344  7.155805  0.056124  0.105091 -0.058557
Image_67  3.251192  0.478424  0.419271  3.563276  0.027947  0.149870 -0.049906
Image_68  3.054945  0.352409  0.268229  4.731785  0.037112  0.102834 -0.035169
Image_69  3.594675  0.420093  0.705729  8.034854  0.063018  0.116251 -0.208511

[70 rows x 7 columns]

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000
mean,3.449643,0.161719,0.488951,5.283731,0.041441,0.147826,-0.040444
std,0.435272,0.189153,0.214258,1.797829,0.014101,0.067685,0.060923
min,2.593865,0.003913,0.167969,2.527949,0.019827,0.070007,-0.282921
25%,3.148993,0.019946,0.313802,4.155764,0.032594,0.107241,-0.049280
50%,3.426991,0.083057,0.444010,5.032524,0.039471,0.127752,-0.015201
75%,3.699571,0.252225,0.641602,6.304903,0.049450,0.159419,-0.002635
max,4.648890,0.739282,1.000000,10.553516,0.082773,0.398325,-0.000234

Excel file on RGB_WITH_RAW_NOISY.xlsx displayng data on sheet "Global Mean Contrast (Sat. Fix "

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
Image_0,3.138849,0.004949,0.214844,4.517296,0.035430,0.149474,-0.000324
Image_1,1.675433,0.018528,0.221354,0.807708,0.006335,0.141368,-0.000123
Image_2,3.440753,0.514269,0.402344,7.918926,0.062109,0.162222,-0.116025
Image_3,4.741101,0.124539,0.393229,14.075484,0.110396,0.305347,-0.043869
Image_4,4.128721,0.030349,0.576823,11.162739,0.087551,0.304959,-0.010842
...,...,...,...,...,...,...,...
Image_65,3.879354,0.604909,0.652344,9.398990,0.073718,0.457761,-0.127218
Image_66,2.532284,0.045652,0.266927,3.198067,0.025083,0.107877,-0.002487
Image_67,3.591997,0.496838,0.552083,6.258376,0.049085,0.326685,-0.078058
Image_68,3.792685,0.397172,0.588542,12.665849,0.099340,0.311019,-0.148391
Image_69,2.827816,0.233300,0.311198,4.151373,0.032560,0.126266,-0.019957

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000
mean,3.255321,0.121418,0.432682,7.527182,0.059037,0.252445,-0.025722
std,0.914451,0.162227,0.155370,5.955296,0.046708,0.125825,0.043198
min,1.263063,0.003906,0.136719,0.526862,0.004132,0.080443,-0.163922
25%,2.790772,0.023401,0.326497,3.719255,0.029171,0.159589,-0.023127
50%,3.377497,0.044874,0.440755,6.213610,0.048734,0.231116,-0.006342
75%,3.871105,0.136120,0.569661,10.250683,0.080398,0.309601,-0.001758
max,4.992068,0.604909,0.735677,30.343439,0.237988,0.656118,-0.000024

Excel file on RGB_WITH_RAW_NOISY.xlsx displayng data on sheet "Grayness Index.jpg"

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
Image_0,2.960728,0.088932,0.243490,4.414829,0.034626,0.295452,-3.904867e-03
Image_1,0.054124,0.003906,0.105469,0.036177,0.000284,0.009577,-4.242978e-08
Image_2,3.135431,0.460576,0.425781,6.859179,0.053797,0.305690,-5.655971e-02
Image_3,4.955589,0.134342,0.636719,15.399415,0.120780,0.897987,-7.947552e-03
Image_4,4.258328,0.036792,0.863281,11.272501,0.088412,0.819006,-3.444571e-03
...,...,...,...,...,...,...,...
Image_65,4.345708,0.580304,1.000000,20.504910,0.160823,2.911697,6.253295e-01
Image_66,1.707270,0.086068,0.156250,0.914636,0.007174,0.184731,-4.013001e-04
Image_67,3.482891,0.478060,0.773438,5.385261,0.042237,0.650710,-3.371896e-02
Image_68,3.409061,0.422717,1.000000,30.716770,0.240916,5.786952,8.793294e-01
Image_69,3.032868,0.329635,0.375000,5.103289,0.040026,0.301281,-2.597226e-02

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000
mean,3.181820,0.141640,0.644661,13.262214,0.104017,1.621844,0.049245
std,1.064698,0.153174,0.291823,15.061671,0.118131,3.067002,0.211793
min,0.009439,0.003906,0.098958,0.004382,0.000034,0.001888,-0.091630
25%,2.858114,0.033699,0.389648,4.385081,0.034393,0.302370,-0.011761
50%,3.357929,0.074811,0.708333,6.839944,0.053647,0.574590,-0.002825
75%,3.789931,0.183871,0.900065,16.132929,0.126533,0.891889,-0.000089
max,4.955589,0.580304,1.000000,60.091108,0.471303,13.560187,1.131487

Excel file on RGB_WITH_RAW_NOISY.xlsx displayng data on sheet "Histogram Stretched.jpg"

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
Image_0,4.032936,0.080534,0.446615,13.691171,0.107382,0.316624,-0.025843
Image_1,NaN,0.010523,0.462240,161.176733,0.735869,0.130486,NaN
Image_2,3.653871,0.531913,0.875000,16.684161,0.130856,0.276137,-0.413144
Image_3,5.338346,0.172126,0.694010,20.867912,0.163670,0.536193,-0.093850
Image_4,4.542405,0.055258,0.929688,14.291530,0.112090,0.451825,-0.029980
...,...,...,...,...,...,...,...
Image_65,4.113420,0.599530,0.975260,10.134804,0.079489,0.595037,-0.143183
Image_66,3.111492,0.076470,0.739583,36.818284,0.288771,0.233327,-0.106692
Image_67,3.774421,0.499559,0.864583,7.722538,0.060569,0.405730,-0.128501
Image_68,3.588793,0.412566,0.944010,15.495420,0.121533,0.445860,-0.197953
Image_69,3.434912,0.297487,0.802083,18.110951,0.142047,0.272914,-0.218114

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,68.000000,70.000000,70.000000,70.000000,70.000000,70.000000,68.000000
mean,3.678283,0.142783,0.774628,31.912609,0.238140,0.376576,-0.101175
std,0.817988,0.169089,0.197519,38.198899,0.266685,0.170066,0.153771
min,0.760379,0.003913,0.225260,5.312211,0.041664,0.073145,-0.855576
25%,3.257157,0.026023,0.644206,10.529559,0.082585,0.273720,-0.120984
50%,3.684777,0.058618,0.859375,16.656753,0.130641,0.344727,-0.038193
75%,4.117562,0.183301,0.929362,27.405177,0.214943,0.478005,-0.015887
max,5.338346,0.639044,0.981771,161.176733,0.997572,0.787359,-0.001625

Excel file on RGB_WITH_RAW_NOISY.xlsx displayng data on sheet "Noisy Synthetic Image (Raw Proc"

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
Image_0,6.829791e-07,0.003917,0.005208,0.025735,0.000202,0.003669,-2.275204e-14
Image_1,2.113466e-03,0.003903,0.007812,0.024274,0.000190,0.004602,-9.526297e-11
Image_2,0.000000e+00,0.003850,0.003906,0.034402,0.000270,0.003646,0.000000e+00
Image_3,0.000000e+00,0.003924,0.003906,0.036902,0.000289,0.004707,0.000000e+00
Image_4,0.000000e+00,0.003910,0.003906,0.023089,0.000181,0.003759,0.000000e+00
...,...,...,...,...,...,...,...
Image_65,0.000000e+00,0.003883,0.003906,0.012941,0.000101,0.002986,0.000000e+00
Image_66,2.100086e-05,0.003897,0.005208,0.031011,0.000243,0.003895,-8.299192e-13
Image_67,0.000000e+00,0.003864,0.003906,0.017210,0.000135,0.003514,0.000000e+00
Image_68,0.000000e+00,0.003882,0.003906,0.021251,0.000167,0.003057,0.000000e+00
Image_69,8.456099e-04,0.003864,0.005208,0.034474,0.000270,0.003835,-3.693631e-11

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,7.000000e+01,70.000000,70.000000,70.000000,70.000000,70.000000,7.000000e+01
mean,2.330598e-04,0.003896,0.004874,0.023863,0.000187,0.003725,-1.016787e-11
std,1.130501e-03,0.000027,0.001145,0.007146,0.000056,0.000645,5.182670e-11
min,0.000000e+00,0.003812,0.003906,0.012908,0.000101,0.002590,-4.204157e-10
25%,0.000000e+00,0.003890,0.003906,0.019368,0.000152,0.003279,-8.683015e-13
50%,3.414896e-07,0.003903,0.004557,0.022876,0.000179,0.003670,-8.336188e-15
75%,2.137476e-05,0.003910,0.005208,0.028106,0.000220,0.004172,0.000000e+00
max,9.117291e-03,0.003943,0.007812,0.044761,0.000351,0.005903,0.000000e+00

Excel file on RGB_WITH_RAW_NOISY.xlsx displayng data on sheet "S-Curve Correction.jpg"

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
Image_0,3.397353,0.006863,0.311198,5.895840,0.046242,0.204490,-0.000768
Image_1,1.799046,0.033412,0.351562,0.956745,0.007504,0.167093,-0.000409
Image_2,3.726456,0.552869,0.675781,11.327387,0.088842,0.227050,-0.264568
Image_3,5.339651,0.138262,0.630208,20.458287,0.160457,0.491644,-0.076470
Image_4,4.581143,0.053566,0.984375,16.366258,0.128363,0.497713,-0.031212
...,...,...,...,...,...,...,...
Image_65,4.188826,0.601121,1.000000,13.208741,0.103598,0.730007,-0.118434
Image_66,2.682362,0.052435,0.424479,4.114591,0.032271,0.131761,-0.005634
Image_67,4.166637,0.485846,0.946615,8.735517,0.068514,0.499948,-0.131311
Image_68,3.566066,0.415502,0.970052,18.885618,0.148122,0.497954,-0.214161
Image_69,3.036501,0.247036,0.510417,5.579518,0.043761,0.178320,-0.041677

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000
mean,3.457286,0.132509,0.703125,10.841454,0.085031,0.378317,-0.043954
std,0.962416,0.165647,0.249445,9.297994,0.072925,0.229992,0.074422
min,1.305782,0.003941,0.200521,0.595259,0.004669,0.097648,-0.354772
25%,2.959168,0.027754,0.528646,4.754974,0.037294,0.205078,-0.041591
50%,3.609496,0.053304,0.748047,8.635010,0.067726,0.301229,-0.012298
75%,4.145439,0.162985,0.956380,14.614187,0.114621,0.490645,-0.002055
max,5.339651,0.621184,1.000000,48.361093,0.379303,1.023638,0.000654

Excel file on RGB_WITH_RAW_NOISY.xlsx displayng data on sheet "Saturation Fixing.jpg"

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
Image_0,3.210414,0.009003,0.248698,4.532982,0.035553,0.183927,-0.000624
Image_1,1.822411,0.037903,0.278646,0.957998,0.007514,0.169909,-0.000370
Image_2,3.367249,0.508430,0.490885,8.079011,0.063365,0.182649,-0.130619
Image_3,4.883542,0.136277,0.467448,14.035565,0.110083,0.380683,-0.047716
Image_4,4.195587,0.029074,0.709635,11.232866,0.088101,0.372711,-0.010859
...,...,...,...,...,...,...,...
Image_65,3.962785,0.601461,0.805990,9.325109,0.073138,0.568200,-0.114583
Image_66,2.533647,0.058280,0.330729,3.228116,0.025319,0.140870,-0.003496
Image_67,3.616147,0.499397,0.679688,6.351497,0.049816,0.368210,-0.088136
Image_68,3.486346,0.422707,0.718750,12.595250,0.098786,0.376617,-0.147415
Image_69,2.862468,0.274143,0.388021,4.172893,0.032729,0.170442,-0.025439

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000
mean,3.258587,0.134073,0.530618,7.555119,0.059256,0.302205,-0.027924
std,0.871196,0.169783,0.190165,5.892950,0.046219,0.156259,0.046822
min,1.314471,0.003913,0.165365,0.597192,0.004684,0.098022,-0.197584
25%,2.856948,0.020560,0.402669,3.793421,0.029752,0.182969,-0.024963
50%,3.387799,0.047992,0.543620,6.304810,0.049449,0.269941,-0.005976
75%,3.785075,0.184175,0.696289,10.280210,0.080629,0.375640,-0.001559
max,4.904408,0.639813,0.902344,30.392076,0.238369,0.783430,-0.000035

Excel file on RGB_WITH_RAW_NOISY.xlsx displayng data on sheet "Unsharp Masking.jpg"

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
Image_0,4.098486,0.093121,0.475260,13.677667,0.107276,0.654772,-0.011888
Image_1,NaN,0.003906,0.412760,254.820457,0.001408,0.014859,NaN
Image_2,3.772562,0.518416,0.907552,16.685112,0.130864,0.599715,-0.171339
Image_3,5.394604,0.174671,0.792969,20.848796,0.163520,1.137315,0.022681
Image_4,4.566083,0.074783,0.997396,14.353141,0.112574,0.960047,-0.002255
...,...,...,...,...,...,...,...
Image_65,4.160576,0.558686,0.986979,10.294203,0.080739,1.183499,0.045022
Image_66,3.239186,0.078994,0.881510,36.784368,0.288505,0.509365,-0.063332
Image_67,3.851659,0.491394,0.967448,7.809410,0.061250,0.840698,-0.028077
Image_68,3.650677,0.392647,0.983073,15.627017,0.122565,0.879768,-0.031918
Image_69,3.592010,0.291981,0.838542,18.063547,0.141675,0.591033,-0.094531

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,68.000000,70.000000,70.000000,70.000000,70.000000,70.000000,68.000000
mean,4.143815,0.141375,0.870629,44.994553,0.145919,0.824917,-0.029712
std,0.912831,0.164903,0.165655,73.176206,0.119079,0.415114,0.076477
min,2.356348,0.003906,0.393229,5.305823,0.000167,0.003089,-0.360041
25%,3.634901,0.025495,0.819010,10.564807,0.076516,0.595297,-0.027962
50%,3.999868,0.067241,0.952474,16.661025,0.111278,0.780225,-0.006847
75%,4.361449,0.184707,0.984049,27.448510,0.154218,0.998641,0.000069
max,6.642849,0.645346,1.000000,254.978706,0.553990,3.003784,0.092549

----------
Excel file on RGB_WITH_RAW_NOISY_global.xlsx displayng data on sheet "After Contrast Conditional Enha"

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
Image_0,4.032936,0.080534,0.446615,13.691171,0.107382,0.316624,-0.025843
Image_1,NaN,0.003906,0.361979,254.934212,0.000516,0.002262,NaN
Image_2,3.653871,0.531913,0.875000,16.684161,0.130856,0.276137,-0.413144
Image_3,5.338346,0.172126,0.694010,20.867912,0.163670,0.536193,-0.093850
Image_4,4.542405,0.055258,0.929688,14.291530,0.112090,0.451825,-0.029980
...,...,...,...,...,...,...,...
Image_65,4.113420,0.599530,0.975260,10.134804,0.079489,0.595037,-0.143183
Image_66,3.111492,0.076470,0.739583,36.818284,0.288771,0.233327,-0.106692
Image_67,3.774421,0.499559,0.864583,7.722538,0.060569,0.405730,-0.128501
Image_68,3.588793,0.412566,0.944010,15.495420,0.121533,0.445860,-0.197953
Image_69,3.434912,0.297487,0.802083,18.110951,0.142047,0.272914,-0.218114

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,62.000000,70.000000,70.000000,70.000000,70.000000,70.000000,62.000000
mean,3.841562,0.138901,0.767708,45.207090,0.143902,0.372892,-0.091501
std,0.618609,0.170395,0.209319,73.842539,0.120503,0.178429,0.127270
min,2.194631,0.003906,0.192708,5.312211,0.000031,0.000326,-0.567342
25%,3.500724,0.018160,0.644206,10.529559,0.075348,0.273720,-0.115648
50%,3.790738,0.054357,0.859375,16.656753,0.110900,0.344727,-0.036224
75%,4.170350,0.177680,0.929362,27.405177,0.153921,0.478005,-0.014208
max,5.338346,0.639044,0.981771,254.996075,0.554102,0.787359,-0.001625

Excel file on RGB_WITH_RAW_NOISY_global.xlsx displayng data on sheet "Denoised Image.jpg"

               AIE      ABWF      ACLF       AAL      LNPF        AG      VPMI
Image_0   3.696319  0.013029  0.291667  5.815619  0.045613  0.110201 -0.002039
Image_1   3.688567  0.071099  0.891927  5.237399  0.041078  0.291139 -0.017105
Image_2   3.604320  0.581816  0.500000  8.106173  0.063578  0.114940 -0.208058
Image_3   4.384958  0.094717  0.302083  8.520022  0.066824  0.154686 -0.022575
Image_4   3.588429  0.045575  0.329427  5.083374  0.039870  0.123162 -0.006490
...            ...       ...       ...       ...       ...       ...       ...
Image_65  2.904792  0.394212  0.213542  2.527949  0.019827  0.091922 -0.016695
Image_66  3.391094  0.145107  0.652344  7.155805  0.056124  0.105091 -0.058557
Image_67  3.251192  0.478424  0.419271  3.563276  0.027947  0.149870 -0.049906
Image_68  3.054945  0.352409  0.268229  4.731785  0.037112  0.102834 -0.035169
Image_69  3.594675  0.420093  0.705729  8.034854  0.063018  0.116251 -0.208511

[70 rows x 7 columns]

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000
mean,3.449643,0.161719,0.488951,5.283731,0.041441,0.147826,-0.040444
std,0.435272,0.189153,0.214258,1.797829,0.014101,0.067685,0.060923
min,2.593865,0.003913,0.167969,2.527949,0.019827,0.070007,-0.282921
25%,3.148993,0.019946,0.313802,4.155764,0.032594,0.107241,-0.049280
50%,3.426991,0.083057,0.444010,5.032524,0.039471,0.127752,-0.015201
75%,3.699571,0.252225,0.641602,6.304903,0.049450,0.159419,-0.002635
max,4.648890,0.739282,1.000000,10.553516,0.082773,0.398325,-0.000234

Excel file on RGB_WITH_RAW_NOISY_global.xlsx displayng data on sheet "Grayness Index.jpg"

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
Image_0,2.960728,0.088932,0.243490,4.414829,0.034626,0.295452,-3.904867e-03
Image_1,0.054124,0.003906,0.105469,0.036177,0.000284,0.009577,-4.242978e-08
Image_2,3.135431,0.460576,0.425781,6.859179,0.053797,0.305690,-5.655971e-02
Image_3,4.955589,0.134342,0.636719,15.399415,0.120780,0.897987,-7.947552e-03
Image_4,4.258328,0.036792,0.863281,11.272501,0.088412,0.819006,-3.444571e-03
...,...,...,...,...,...,...,...
Image_65,4.345708,0.580304,1.000000,20.504910,0.160823,2.911697,6.253295e-01
Image_66,1.707270,0.086068,0.156250,0.914636,0.007174,0.184731,-4.013001e-04
Image_67,3.482891,0.478060,0.773438,5.385261,0.042237,0.650710,-3.371896e-02
Image_68,3.409061,0.422717,1.000000,30.716770,0.240916,5.786952,8.793294e-01
Image_69,3.032868,0.329635,0.375000,5.103289,0.040026,0.301281,-2.597226e-02

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000
mean,3.181820,0.141640,0.644661,13.262214,0.104017,1.621844,0.049245
std,1.064698,0.153174,0.291823,15.061671,0.118131,3.067002,0.211793
min,0.009439,0.003906,0.098958,0.004382,0.000034,0.001888,-0.091630
25%,2.858114,0.033699,0.389648,4.385081,0.034393,0.302370,-0.011761
50%,3.357929,0.074811,0.708333,6.839944,0.053647,0.574590,-0.002825
75%,3.789931,0.183871,0.900065,16.132929,0.126533,0.891889,-0.000089
max,4.955589,0.580304,1.000000,60.091108,0.471303,13.560187,1.131487

Excel file on RGB_WITH_RAW_NOISY_global.xlsx displayng data on sheet "Unsharp Masking.jpg"

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
Image_0,4.098486,0.093121,0.475260,13.677667,0.107276,0.654772,-0.011888
Image_1,NaN,0.003906,0.412760,254.820457,0.001408,0.014859,NaN
Image_2,3.772562,0.518416,0.907552,16.685112,0.130864,0.599715,-0.171339
Image_3,5.394604,0.174671,0.792969,20.848796,0.163520,1.137315,0.022681
Image_4,4.566083,0.074783,0.997396,14.353141,0.112574,0.960047,-0.002255
...,...,...,...,...,...,...,...
Image_65,4.160576,0.558686,0.986979,10.294203,0.080739,1.183499,0.045022
Image_66,3.239186,0.078994,0.881510,36.784368,0.288505,0.509365,-0.063332
Image_67,3.851659,0.491394,0.967448,7.809410,0.061250,0.840698,-0.028077
Image_68,3.650677,0.392647,0.983073,15.627017,0.122565,0.879768,-0.031918
Image_69,3.592010,0.291981,0.838542,18.063547,0.141675,0.591033,-0.094531

,AIE,ABWF,ACLF,AAL,LNPF,AG,VPMI
count,68.000000,70.000000,70.000000,70.000000,70.000000,70.000000,68.000000
mean,4.143815,0.141375,0.870629,44.994553,0.145919,0.824917,-0.029712
std,0.912831,0.164903,0.165655,73.176206,0.119079,0.415114,0.076477
min,2.356348,0.003906,0.393229,5.305823,0.000167,0.003089,-0.360041
25%,3.634901,0.025495,0.819010,10.564807,0.076516,0.595297,-0.027962
50%,3.999868,0.067241,0.952474,16.661025,0.111278,0.780225,-0.006847
75%,4.361449,0.184707,0.984049,27.448510,0.154218,0.998641,0.000069
max,6.642849,0.645346,1.000000,254.978706,0.553990,3.003784,0.092549

----------

####